### ISSUE TITLE
Update contribution docs with docblock expectations

### ISSUE THREAD

**Issue by bahiirwa** [ClassicPress/ClassicPress#1023]
We have a codebase with WordPress an ClassicPress code. In a few years ClassicPress  will have `@since 2.1.3` making it hard to differentiate the same version with WordPress. So the docblocks have always been prefixed with cp or wp to make it `@since wp-2.3.0`

This needs to be added to the [contribution.md](https://github.com/ClassicPress/ClassicPress/blob/develop/.github/CONTRIBUTING.md) file

**Comment by smileBeda** [comment]
Also see https://github.com/ClassicPress/site-docs/pull/10#discussion_r754836779

**Comment by bahiirwa** [comment]
Thanks @smileBeda. Does this link to any live page? Something we can link back to without large duplication?

**Comment by smileBeda** [comment]
Currently, it is not working on the DOC page. Not sure why.

In any case the link in the ToolTip would, as per the comment linked above, link to a page in the DOC (which as of now is private and pending long due review)

**Comment by viktorix** [comment]
We will need to update CONTRIBUTING.md with any new changes for v2.0. This will most likely include keeping original WP `@since` and prefixing ClassicPress tags `@since CP-2.0.0`.
- https://github.com/ClassicPress/wp-cms-experimental/issues/4#issuecomment-1382724927
