### ISSUE TITLE
Upstream: Media Metadata Improvements

### ISSUE THREAD

**Issue by dshanske** [ClassicPress/ClassicPress#1026]
Add these media metadata improvements from upstream

https://core.trac.wordpress.org/ticket/49412 - Store filesize media metadata
https://core.trac.wordpress.org/ticket/48164 - Store original URL when using media_sideload_image

Both of these are simple enhancements to store specific information around media metadata

**Comment by bahiirwa** [comment]
@dshanske Are you able to backport these? They look very helpful.

**Comment by mattyrob** [comment]
Ticket 49412 is already back ported and covered here, it includes the original change, a fix for the location of `wp_filesize()` and I've added the more recent change just now:
https://github.com/ClassicPress/ClassicPress/pull/950

Ticket 48164 needs a new backport but looks like a simpler one.

**Comment by mattyrob** [comment]
@dshanske - Not a problem, trying to figure out what we have already merged from WordPress into ClassicPress is often hard to identify - I only realised when I looked at the linked tickets that one looked familiar.

**Comment by dshanske** [comment]
@mattyrob  I see the filesize, but can't find https://core.trac.wordpress.org/ticket/48164, the original URL sideload.
