### ISSUE TITLE
Core Plugin: REST API

### ISSUE THREAD

**Issue by viktorix** [ClassicPress/ClassicPress#1038]
Move REST API to a core plugin ([discussion](https://forums.classicpress.net/t/core-plugins-discussion/3513/7)).

**Comment by bahiirwa** [comment]
@mattyrob has spent some time on this. PR can leverage
- https://github.com/ClassicPress/ClassicPress/commit/e9f82647d50ec4d3948e138d1a4b2e3c6ae4b79c

**Comment by mattyrob** [comment]
Closing this issue, this can be consider again later but this set of features can be left in core and disabled by a plugin if required:

https://wordpress.org/plugins/disable-json-api/
https://wordpress.org/plugins/disable-wp-rest-api/
