### ISSUE TITLE
Core Plugin: Embed API

### ISSUE THREAD

**Issue by viktorix** [ClassicPress/ClassicPress#1039]
Move embed API to a core plugin ([discussion](https://forums.classicpress.net/t/core-plugins-discussion/3513/7)).

**Comment by bahiirwa** [comment]
Some work has been done here
- https://github.com/ClassicPress/ClassicPress/commit/3d2330b02979f4a0b4991e330660e4859150d023
- https://github.com/ClassicPress/ClassicPress/commit/f2e5ade348eb298f1fb42cb09bcde5838cfe0cc4
- https://github.com/ClassicPress/ClassicPress/commit/abee251412af069d81d67166d38282c3058058e3
- https://github.com/ClassicPress/ClassicPress/commit/51d6cf9a5b2bd47ea793cfaa4dbc4909294ccf4f
- https://github.com/ClassicPress/ClassicPress/commit/d1388cc439573e59077c4f1dc3459cd20610fdd6

**Comment by mattyrob** [comment]
Closing this issue, this can be consider again later but this set of features can be left in core and disabled by a plugin if required:

https://wordpress.org/plugins/disable-embeds/
