### ISSUE TITLE
Improve "Remember me" checkbox

### ISSUE THREAD

**Issue by viktorix** [ClassicPress/ClassicPress#1041]
This was brought up as a [petition in the forums](https://forums.classicpress.net/t/login-remember-me/2882):

> Below the login credentials there is this cryptic “remember me” that doesn’t mean anything at all.
>
> Remember me for what, for how long and what for?
> The correct syntax for such checkboxes is:
>
> Remember me for XX days on this computer

I will experiment with improvements to this checkbox as part of the overall improvements to the login page I started last year (#796).

**Comment by KTS915** [comment]
The most accurate text would actually be "Remember me for up to 14 days in this browser." But who wants all that cluttering up their login form? I haven't ever seen anyone else complain about this, so it seems like a storm in a teacup: the abbreviated version works fine.
