### ISSUE TITLE
Add UUIDs/GUIDs as candidate keys for all tables

### ISSUE THREAD

**Issue by viktorix** [ClassicPress/ClassicPress#1045]
> In working with some more complex WordPress sites that need to interact with other systems and synchronize data it’s becoming clear that the lack of a properly maintained UUID/GUID makes that really, really hard. See:
> https://stackoverflow.com/questions/45399/advantages-and-disadvantages-of-guid-uuid-database-keys/45479#45479
> I am talking a candidate key here, not UUIDs/GUIDs as primary keys.

[Original petition](https://forums.classicpress.net/t/add-uuids-guids-as-candidate-keys-for-all-tables/2885)

**Comment by KTS915** [comment]
I'm struggling to see how it would be a good idea to add 32-character strings to every item in the database when almost no user of ClassicPress would ever have any use for them.
