### ISSUE TITLE
Drop support for Older PHP Versions.

### ISSUE THREAD

**Issue by bahiirwa** [ClassicPress/ClassicPress#1056]
As PHP grows and changes, consideration for dropping support of older versions in likely starting with 5.6.
As of now, [PHP 7.1, 7.2 and 7.3 have reached EOL.](https://www.php.net/eol.php)

See https://github.com/ClassicPress/ClassicPress/issues/1049#issuecomment-1179360281 and https://forums.classicpress.net/t/minimum-php-version-should-be-7-x/2887

Some issues raised are:
- [x] https://github.com/ClassicPress/ClassicPress/issues/438 
- [x] https://github.com/ClassicPress/ClassicPress/issues/451 (Might need one to close support for 5.6)
- [ ] Have a board/visualization for the PHP usage. (Needs a task in appropriate repo)

Ref: https://github.com/ClassicPress/ClassicPress/issues/1049#issuecomment-1181398976_

**Comment by viktorix** [comment]
Dropping 5.6 support would be considered a breaking change, so it would have to be v2.

For reference, from the petition, this is what James planned on doing:

> Here's what I am thinking as far as a plan for this change:
> 
> - All ClassicPress 1.x versions will support PHP 5.6 and greater.
> - We'll bump the minimum PHP version with each major version of ClassicPress, and use a PHP version check to make sure the site is compatible with the new version.  If the version check doesn't pass, then we'll block the upgrade (similar to how the migration plugin works today).
> - When we get closer to version 2 release, we'll take a look at the distribution of PHP versions on ClassicPress 1.x sites.
> - In a ClassicPress 1.x release, we'll include a prompt to upgrade older PHP versions.  This should help move the needle further and push more people to upgrade.
> - We'll use the results from the active installation numbers, as well as the PHP support timeline, to decide on a minimum PHP version for ClassicPress v2.x.  It may be as high as PHP 7.2 and 7.3, but we need more information about active installations, timeline, etc first.
> 
> If that works well going from v1 to v2, it should be an approach that we can repeat with each major version of ClassicPress.

**Comment by JoeRathbun** [comment]
Coincidentally, a few days ago, I tried to move 2 sites from 7.0 to 7.4 and the front ends fell apart.

**Comment by KTS915** [comment]
@JoeRathbun: I am running all my sites on PHP 7.4 without any problems at all. What you experienced is likely not an issue with CP itself, but with something specific to your site. If you open an issue on the ClassicPress forums for that, I'm sure someone will be able to help (though you'll need to be a bit more specific than "fell apart").

**Comment by JoeRathbun** [comment]
Sorry, @[KTS915](https://github.com/KTS915) you are right, I have several sites running 7.4 as well. I wasn't trying to get tech support, I was just agreeing that requiring PHP 7.4 should be a part of ClassicPress v2.
