### ISSUE TITLE
Handle multiple Link headers - Simplepie

### ISSUE THREAD

**Issue by erichk4** [ClassicPress/ClassicPress#1058]
## Expected behavior

Feed parsing should not throw errors (e.g. Siteorigin dashboard widget) 

## Current behavior

PHP Error:  preg_match() expects parameter 2 to be string...

## Possible solution

Upgrade SimplePie to latest version or apply the patch https://github.com/simplepie/simplepie/pull/700/commits/0e2eb359c8207bb1a7e3154e8c703cf2455b5225

## Steps to reproduce (for bugs)

1. Upgrade to latest ClassiPress verion 1.4.2
2. Install and activate Siteorigin panel plugin
3. Go to the Dashboard (watch the php error logs, on some installations also causes 502-Bad gateway errors)

## Context

-> https://github.com/simplepie/simplepie/issues/669
and
-> https://github.com/simplepie/simplepie/pull/700

**Comment by mattyrob** [comment]
There are two upstream changesets that'll get us from 1.5.6 to 1.5.7 and then 1.5.8

https://core.trac.wordpress.org/changeset/52393
https://core.trac.wordpress.org/changeset/52413/

And then we need to watch this tick to migrate to 1.6.0

https://core.trac.wordpress.org/ticket/55604

**Comment by viktorix** [comment]
Looks like this should have been closed when #1060 was merged and v1.5.0 released.
