### ISSUE TITLE
Replace Petitions Dashboard widget API

### ISSUE THREAD

**Issue by viktorix** [ClassicPress/ClassicPress#1069]
Since we're moving feature requests to issues, we have frozen the current petitions API so we can change the dashboard widget without issues.

My proposed widget tries to get more attention to our GitHub issues. It will have three tabs:
- Recent requests - shows the latest ten requests.
- Accepted requests - shows requests that were accepted, which means it has a label such as "needs pr", "has pr", etc.
- Help Wanted - this will show issues with "help wanted" label, to try and get people engaged.

Once request has "wontfix" label, it will not show.

Here are 2 mock-ups for 2 tabs in a new widget for recent and accepted requests. Help wanted is basically the same as recent.

![image](https://user-images.githubusercontent.com/1692600/180361871-e2963eb4-898c-4f04-bbed-826a72dece1e.png)

![image](https://user-images.githubusercontent.com/1692600/180361894-85aa3e2c-b32f-4911-b770-1d67b51c1ab5.png)

## APIs
If I'm not mistaken, this is what we can use:

Open issues labeled with "type: feature request":
https://api.github.com/search/issues?q=is%3Aissue+is%3Aopen+label%3A%22type%3A+feature+request%22+repo:classicpress/classicpress

Open issues labeled with "help wanted":
https://api.github.com/search/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22+repo:classicpress/classicpress

## /features/ endpoint
We can't have CP websites requesting data from GitHub API directly. So we would need to set up a script that would parse GitHub API and serve it using `/features/` API we currently have. This way, we have full control over it. Script can be triggered by cron daily or couple of times per day. Daily probably would be fine.

We need to try and get users more engaged without being annoying. This is the first step.

**Comment by bahiirwa** [comment]
> We can't have CP websites requesting data from GitHub API directly. 

Could your throw more light on this?

This is because we shall be making a redirect/"reverse proxy" of sort. Unless we choose to save this information in some place before distributing it.

**Comment by viktorix** [comment]
@bahiirwa there are a few reasons not to use GitHub API directly:

1. Privacy. Main issue. GitHub API will log all requests. Users wouldn't even know they're sharing their IP with GitHub.
2. Maintenance of the widget. Just like now, if we need to freeze API results to make changes to the widget, we wouldn't be able to do it since we wouldn't have control over the API.
3. Gives us more control over what we can do with the data.
4. GitHub API returns a lot of unnecessary data. So we can clean it up and return only the necessary data for the widget to work.

**Comment by viktorix** [comment]
I've made some progress on the feature request widget. I've modified HTML/CSS while still using old API data:

![image](https://user-images.githubusercontent.com/1692600/183232904-ca949616-b0da-4661-811b-6105fd836196.png)

**Comment by viktorix** [comment]
We need to modify [JSON generator script](https://github.com/ClassicPress/ClassicPress-APIs/blob/master/bin/update-petitions-data.php) to get data from GitHub, which is triggered periodically using a cronjob.

The following is a proposed JSON format based on the current API:
```json
{
    "recent": {
        "data": [{
                "title": "items->{}->title",
                "status": "open",
                "link": "items->{}->url"
            },
            {
                "title": "items->{}->title",
                "status": "open",
                "link": "items->{}->url"
            }
        ]
    },
    "in-progress": {
        "data": [{
                "title": "items->{}->title",
                "status": "needs-pr",
                "link": "items->{}->url"
            },
            {
                "title": "items->{}->title",
                "status": "has-pr",
                "link": "items->{}->url"
            }
        ]
    },
    "help-wanted": {
        "data": [{
                "title": "items->{}->title",
                "status": "open",
                "link": "items->{}->url"
            },
            {
                "title": "items->{}->title",
                "status": "open",
                "link": "items->{}->url"
            }
        ]
    },
    "link": "https://github.com/ClassicPress/ClassicPress/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+feature+request%22"
}
```
## Categorization

We have 3 categories: recent, in-progress, and help wanted

## recent
Pull the most recent 10 open issues using the label "type: feature request" and the following statuses:
- status: discussion
- status: on hold
- status: need more info
- status: needs decision

When passing status label to the JSON file, please remove "status: ".

https://api.github.com/search/issues?q=is%3Aissue+is%3Aopen+label%3A%22type%3A+feature+request%22+repo:classicpress/classicpress

## in progress
Pull open issues labeled "type: feature request" and the following statuses:
- status: has pr
- status: needs pr
- status: research plugin
- status: needs test
- status: needs review
- status: community reviewed

When passing status label to the JSON file, please remove "status: ".

https://api.github.com/search/issues?q=is%3Aissue+is%3Aopen+label%3A%22type%3A+feature+request%22+repo:classicpress/classicpress

## help wanted
Pull the latest 10 open issues with label "help wanted".
When passing status label to the JSON file, please remove "status: ".

https://api.github.com/search/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22+repo:classicpress/classicpress

**Comment by bahiirwa** [comment]
Thank you for the well detailed requirement. This comment might need to be an issue on APIs repo. 

However, We need to keep the current issue for the dashboard modification in core.

**Comment by mattyrob** [comment]
Please can we have a progress report on this proposal.

Is there a possibility of a PR soon? 1.5.0 is nearing Release Candidate phase, without a PR soon we may need to consider deferring this until 1.6.0.

**Comment by viktorix** [comment]
@mattyrob bump it to 1.60. This requires API changes that haven't been implemented yet.

**Comment by bahiirwa** [comment]
I see this is closed now. I had began work on it here. https://github.com/ClassicPress/ClassicPress-APIs/pull/107
Please let me know if I should close it as it is not required anymore. @KTS915

**Comment by KTS915** [comment]
I don't see a petitions widget in ClassicPress any more, so I closed this. Do you see one?

**Comment by KTS915** [comment]
In other words, what you're doing is something new, not a replacement.

**Comment by bahiirwa** [comment]
I see, this has been since removed. No need to develop for it since it is out.
