### ISSUE TITLE
Login page loads specific styles twice times

### ISSUE THREAD

**Issue by luxvw** [ClassicPress/ClassicPress#1076]
Prior WP 5.3 minor issue.

https://core.trac.wordpress.org/ticket/43483  
https://core.trac.wordpress.org/changeset/45673

In login.css: `@import url(forms.css); @import url(l10n.css);`

While in script-loader.php  
`$styles->add( 'login',  "/wp-admin/css/login$suffix.css", array( 'dashicons', 'buttons', 'forms', 'l10n' ) );`

Thus 'forms' and 'l10n' are loaded twice times.

**Comment by bahiirwa** [comment]
@luxvw Would you like to work n a [backport](https://github.com/ClassicPress/ClassicPress/blob/develop/.github/CONTRIBUTING.md#backporting-changes-from-wordpress) for this?

**Comment by viktorix** [comment]
With re-fork work getting underway, we should consider closing backporting issues such as this.
