### ISSUE TITLE
Countable warnings in class-wp-xml-server.php

### ISSUE THREAD

**Issue by mattyrob** [ClassicPress/ClassicPress#1079]
## Expected behavior
I noticed error being logged today on one of my sites related to PHP variables not being countable. There is an upstream issue and fix:
https://core.trac.wordpress.org/ticket/48046

## Current behavior
If the `$args` variable is not countable a PHP Warning is logged.

## Possible solution
Backport of upstream changeset should fix this issue:
https://core.trac.wordpress.org/changeset/46148

## Steps to reproduce (for bugs)
See upstream ticket for more detail and evidence of the issue.

## Context
Seen in live site error logs.

**Comment by welmarr** [comment]
I can correct it using your suggestion. But this is my first contribution. I have already forked and [configured the project locally](https://github.com/ClassicPress/ClassicPress/blob/develop/.github/CONTRIBUTING.md#setting-up-a-local-development-environment) on my computer. How can I proceed to submit the fix?

**Comment by bahiirwa** [comment]
So glad to have you on board @welmarr. Check out https://github.com/ClassicPress/ClassicPress/blob/develop/.github/CONTRIBUTING.md 

Look for backporting from WordPress

**Comment by bahiirwa** [comment]
@welmarr Any questions about this?
