### ISSUE TITLE
Missing Instructions:: Run PHPCS locally before commit

### ISSUE THREAD

**Issue by bahiirwa** [ClassicPress/ClassicPress#1092]
In order to reduce the back and forth commits for fixing PHPCS, we need to add Instructions for running PHPCS locally before commit to `contributions.md` file

### Manual PHPCS install.
- You could manually install `phpcs` 
- download the WP coding standards too. 
- And then configure the path for phpcs. 

### Using Composer
The simpler way is to 
- install composer globally
- run composer install in the CP repository folder locally. 
- run `phpcs -n` That show only errors.

**Comment by xxsimoxx** [comment]
Closing as completed by #1460.
