### ISSUE TITLE
Missing Information: Working with JS and CSS files.

### ISSUE THREAD

**Issue by bahiirwa** [ClassicPress/ClassicPress#1093]
We need to add Instructions to the `contributions.md` file to help with JS and CSS file contributions.
Right now we might not be using modern tools like SASS/SCSS but we need to document this for the future:
- how we use NPM and its dependencies.
- Is this locally used?
- When do we use `npm install` locally?

**Comment by viktorix** [comment]
For Windows users, it should be mentioned it's not possible to run `grunt` right now - including if installing it inside WSL. I haven't been able to get grunt to work. The problem is described in issue #854

**Comment by xxsimoxx** [comment]
Closing as completed by #1460.
