### ISSUE TITLE
Add .editorconfig file for consistency

### ISSUE THREAD

**Issue by bahiirwa** [ClassicPress/ClassicPress#1099]
Now that the coding standards are going to be enforced, it is good to use an editor that reads the `.editorconfig` file that is in the root of the repo. 

Ref: http://editorconfig.org/ can help with explanation.

_Originally posted by @joyously in https://github.com/ClassicPress/ClassicPress/issues/1086#issuecomment-1220907206_

**Comment by mattyrob** [comment]
We [already have](https://github.com/ClassicPress/ClassicPress/blob/develop/.editorconfig) `.editorconfig`

It would be helpful to know what additions we need to make to that file.
