### ISSUE TITLE
Fork-related tags and branches

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#11]
## Tags

As the last commit that came directly from the `wordpress-develop` repository, commit d7b6719f88f54e15608434be2b1b1599d59d42b3 should have a tag.

What should it be called?  `LAST_WP_COMMIT`?

Are there any other fork-related tags that would be useful to mark points of divergence from WP core?

## Branches

It would be easier to use `master` as the default branch for this repository instead of `4.9`.  Right now there are a couple of extra steps when submitting changes as PRs, and a good bit of standard `git` advice found online won't work without modification.

I think it makes sense to change this over now, but let's make sure we have a reasonable way to handle release branches.

**Comment by Mte90** [comment]
I agree to mark the WP commits, so it is wasy to track them.

I think that we can do as wordpress do. Trunk for the next major release where we can backport stuff and when there is a release like `4.9` in this case we have a branch.

I think that pr deserve to the trunk so we can evaluate it better and not depend to a major already released.

**Comment by scottybo** [comment]
Happy to take your lead on this @nylen - I set it to the 4.9 branch as I figure we would be working on that from here on out, but I'll be honest: I'm out of my depth with this part of the repo

**Comment by scottybo** [comment]
@nylen how would you like to proceed?

**Comment by nylen** [comment]
Let's use `master` for normal development, and rename the branches that come from WP to `wp-4.9` (for example).

Now is a good time to make this change since there are no open PRs.

Later on, when we are ready to do a release, we'll probably open a [release branch](https://stackoverflow.com/questions/20755434/what-is-the-master-branch-and-release-branch-for).  Each version will get a git tag from the commit that generated the release.

**Comment by nylen** [comment]
This is done.  This repo now has the following branches:

- `master` - we will do development here
- `wp-4.9` - tracks the `4.9` branch from https://github.com/WordPress/wordpress-develop
- `wp-trunk` - tracks the `master` branch from https://github.com/WordPress/wordpress-develop

I'll use these last two branches for the bot mentioned in #19 that will help us stay in sync with WP.

I've also applied the `LAST_WP_COMMIT` tag to the last commit that WP and ClassicPress share.

**Comment by nylen** [comment]
Oh - I forgot - this repo currently says:

> This branch is 397 commits ahead, 836 commits behind WordPress:master

This is because our `master` branch now means something different than what's in the parent repo, but this isn't what we want.

Per https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork I've contacted GitHub support to break the fork link on GitHub.
