### ISSUE TITLE
Insufficient error Message: Run phpcs -q -n --report=checkstyle | cs2pr

### ISSUE THREAD

**Issue by bahiirwa** [ClassicPress/ClassicPress#1121]
In the automations `Run phpcs -q -n --report=checkstyle | cs2pr` in the `.github/workflows/coding-standards.yml` does not give a full error for the devs to provide a proper solution for failing test.

See: https://github.com/ClassicPress/ClassicPress/actions/runs/3157139302/jobs/5137644526

## Screenshots

![Screenshot 2022-09-30 at 12 25 14](https://user-images.githubusercontent.com/7713923/193239796-2f67e300-cd3b-4fa6-bd41-bad9833eb5da.png)

**Comment by mattyrob** [comment]
The output is displayed on the PR in the list of file changes, in this case see here:
https://github.com/ClassicPress/ClassicPress/pull/1090/files

Line 75 and 76 of `tests/phpunit/tests/dbdelta.php` are incorrectly indented.
