### ISSUE TITLE
💡 drag-n-drop page ordering

### ISSUE THREAD

**Issue by atomGit** [ClassicPress/ClassicPress#1157]
### Context

the ability to arrange items by simple drag and drop is already available in the core i believe - it is in play on the Appearance > Menu page and works very well for arranging menu items (menu_order)

i'd like to propose utilizing this capability on the 'pages' back-end (/wp-admin/edit.php?post_type=page) to replace the current method of arranging pages 

the terribly annoying and time wasting problem of arranging pages using their page order surfaces when one has many pages and wants to insert a new page somewhere in the middle to have it show up that way on the front-end, either in a menu or on a page that lists all children, or just to keep things neat

doing so requires having to change the page order, one page at a time, for every page after the insertion point - imagine doing this with 20, 50 or hundreds of pages

### Possible implemantion

drag and drop ordering is already built-in to the core and is used to arrange menu items 

drag and drop for pages should modify 'menu_order'

### Will you be able to help with the implementation?

i don't possess the skill to help with this

**Comment by KTS915** [comment]
I recommend the Simple Page Ordering plugin: https://wordpress.org/plugins/simple-page-ordering/

**Comment by atomGit** [comment]
it's funny you mention that :)

i created a petition long ago to incorporate the functionality of SPO in the core and the idea was rejected (extra bulk, etc.), however i've since learned that the functionality is already in the core, thus no need for a plugin

btw i'm using [CMS Tree Page View](https://wordpress.org/plugins/cms-tree-page-view/) in the mean time - if i'm not mistaken the SPO dev has some things on his/her plate that will break compatibility with CP, plus i didn't really like the way it worked but that could be browser specific

**Comment by KTS915** [comment]
I don't know what you mean when you say the functionality is already in core.

Great that you've found what works for you. SPO works with v3.8+ of WP and so works fine with CP.

**Comment by atomGit** [comment]
the functionality for arranging items by drag-n-drop can be realized in the appearance > menu page where you can drag and drop menu items, including their children ... thus the basic functionality seems to already be built-in ... thus something like SPO doesn't need to be incorporated in the core

**Comment by KTS915** [comment]
So you're talking about a tool that's in core, specifically jQuery, I think. But making use of that tool can be done by a plugin or core; there's no inherent advantage to having it done by core. And you've already highlighted an issue with adding it to core: what if some users prefer it implemented differently? Then we've added bloat.

**Comment by atomGit** [comment]
> there's no inherent advantage to having it done by core.

i disagree - the fewer plugins the better and without a plug the alternative is to keep ordering pages in a most counter-intuitive, time wasting and confusing way, and with enough pages the problem becomes unmanageable

users that don't need the functionality can simply ignore it since there would be no change to the way the page list is displayed, but those that do can benefit _immensely_ (see the 2 scenarios i laid out earlier)

> what if some users prefer it implemented differently?

how so? i think the functionality is either there, or it isn't - i think the only question would be whether or not to change the menu_order when a page is moved and i think that would be the logical and expected thing to do

in the end, if the overhead in adding it (re-purposing code that's already present) costs little or nothing, why not add it?

certainly there are considerations i'm not able to account for and so maybe it's not as great of an idea as i think it is, but from an end-user perspective i can hardly describe how wildly ridiculous it is to set the page order, one page at a time, to re-order them

eventually one might give their pages order numbers like 100, 200, etc., to make room for additional pages, but that quickly wears out too and so then it's a plugin to do what a) WP/CP can already do without a plugin and b) what ought to have been built-in to begin with in my opinion

**Comment by KTS915** [comment]
You talk as if specifying numerical order is the only other option for ordering pages. It isn't. And I certainly don't want to be ordering lots of pages by using drag and drop. I find it much easier to use a (core) filter to have the pages automatically listed in alphabetical order. That way, every admin knows immediately where to find what they are looking for, and there's no manual effort involved at all.

**Comment by atomGit** [comment]
> And I certainly ...

have you thought about what others might want?

and again, **those that don't want the functionality can simply ignore it** - you talk as though implementing it is somehow going to destroy the work flow of every admin when in fact it changes nothing

whatever, you obviously have your mind made up Tim so do what you want

**Comment by KTS915** [comment]
I don't get to decide by myself. If I did, I would have closed the topic myself.

I was pointing out that what you are asking for isn't for everyone, and so I wanted you to explain why it should be added to core, where everyone will get it whether they want it or not. You might, for example, have explained why dragging and dropping every page manually is better than having a default filter. (I can certainly understand micromanaging a front-end menu, but I can't see the reason for doing the same with a back-end list.) But you haven't. Which suggests that, indeed, a plugin is the best way to achieve this as it's really not about core functionality but personal preference.
