### ISSUE TITLE
💡Replace api.wordpress.org/core/importers/1.1 endpoint

### ISSUE THREAD

**Issue by viktorix** [ClassicPress/ClassicPress#1168]
### Context

ClassicPress makes calls to `api.wordpress.org/core/importers/1.1` in `/wp-admin/includes/import.php` to get a list of importer plugins. WordPress API endpoint should be replaced with a ClassicPress API endpoint.

This could be considered a privacy issue.

### Possible implemantion

PR has been submitted to create a new API endpoint:
https://github.com/ClassicPress/ClassicPress-APIs/pull/59

### Possible Solution

Once the new API endpoint has been merged and taken live, replace URL in the core:
`/wp-admin/includes/import.php`.

### Will you be able to help with the implementation?

Yes, API endpoint PR has been submitted.

**Comment by bahiirwa** [comment]
The API looks ready for merge. What would is left is to make a PR closing this with new API URL.
I think this can neatly fold in 1.5.0-rc1 @mattyrob

**Comment by mattyrob** [comment]
API change s merged, we need a PR for this proposed change next.

**Comment by viktorix** [comment]
[PR](https://github.com/ClassicPress/ClassicPress-APIs/pull/61) for index.php has been submitted.

**Comment by viktorix** [comment]
I've started testing this on one of my production sites, no issues so far. Plugins compatible with CP are installing, no errors.

**Comment by mattyrob** [comment]
PR for `index.php` on the API repo is merged and the API site manually updated now.
Next we need a PR to update the URL used in core code in `/wp-admin/includes/import.php`.
