### ISSUE TITLE
Update PHPMailer to 6.7.0 📋 

### ISSUE THREAD

**Issue by bahiirwa** [ClassicPress/ClassicPress#1189]
### WordPress trac tickets

https://core.trac.wordpress.org/ticket/57281

### WordPress changesets

https://core.trac.wordpress.org/changeset/54937

### Can you help?

Yes, I will submit a PR

**Comment by viktorix** [comment]
With re-fork work getting underway, we should consider closing backporting issues such as this.

**Comment by viktorix** [comment]
With the upcoming v2.0, this issue will be closed.
