### ISSUE TITLE
Replace (W) icon in multisite sites list

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#121]
And probably some other places where it's rendered the same way...

![screen shot 2018-10-09 at 3 37 26 pm](https://user-images.githubusercontent.com/227022/46709109-cf539980-cc07-11e8-9dd3-fe1e19d42196.png)

Thanks @striebwj for the report!

**Comment by frozzare** [comment]
Looks like that WP-icon is part of Dashicons. I replaced all WP-icon images I could find in `wp-admin` and `wp-includes` in #5

**Comment by nylen** [comment]
Milestoning for the first beta (probably not going to get to this for the alpha releases).

**Comment by senlin** [comment]
fixed with #149
