### ISSUE TITLE
💡 new default for attachment order by date instead of ID

### ISSUE THREAD

**Issue by joyously** [ClassicPress/ClassicPress#1223]
### Context

When viewing an attachment page, it is common for the theme to use `previous_image_link()` and `next_image_link()` for navigation among attachments. The sequence, however, is hard-coded in a call to `get_children()` like this:
```
	$attachments = array_values(
		get_children(
			array(
				'post_parent'    => $post->post_parent,
				'post_status'    => 'inherit',
				'post_type'      => 'attachment',
				'post_mime_type' => 'image',
				'order'          => 'ASC',
				'orderby'        => 'menu_order ID',
			) ) );
```
I attempted to change this with a filter on `'posts_orderby'` (since `get_children` calls `get_posts()` which uses its own `new WP_Query`), but my filter was not invoked.

It seems like a lot of hassle to modify this one thing, but there are several scenarios in which people would want to: importing images, bulk upload, the plugin Add From Server (which is my scenario). All of these can make the ID not in the same sequence as the preferred date, especially since the date is editable and the ID is not.

I'm thinking that a filter on the arguments or a simple change to a better default of using the date instead of the ID would be a good solution.

Be aware that WP has changed these functions a bit in WP 5.8 and those changes might be incorporated along with my suggestion.

### Possible implemantion

I changed this one line locally and it does what I prefer:
```
	'orderby'        => 'menu_order date',
```
or a new filter on the args to `get_children`.

### Will you be able to help with the implementation?

change already given

**Comment by mattyrob** [comment]
This can be tested in the TwentySixteen theme with images uploaded.

Mitigating considerations either way:
 - this is a simple change
 - this is an intuitive change
 
- conversely these functions don't seem to be I'm more recent Themes.
- editing image update date is only viable by plugins or direct database editing
