### ISSUE TITLE
🐞 Cookie “wp-settings-4” does not have a proper “SameSite” attribute value

### ISSUE THREAD

**Issue by atomGit** [ClassicPress/ClassicPress#1227]
### Expected behavior

browser console (firefox):

> Cookie “wp-settings-4” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

### Current behavior

as above

### Possible solution

as above

### Steps to reproduce bug

1. load a CP site - firefox may or may not be required -  i noticed this when loading the dashboard, but it may be found elsewhere
3. check console

### ClassicPress version

1.5.2

### PHP version

8.0

### Can you help?

No, I can't help

**Comment by mattyrob** [comment]
Upstream ticket for information and potential tracking of a good solution:
https://core.trac.wordpress.org/ticket/37000

Seems like a reasonable plugin fix exists already:
https://github.com/MikhailRoot/samesite-cookie-manager

**Comment by viktorix** [comment]
When we release v2.0 and WP still doesn't fix this, we should consider using the included patch to fix this in CP.

**Comment by xxsimoxx** [comment]
Wondering if this can be a valid solution for PHP < 7.3 can be [this one](https://www.php.net/manual/en/function.setcookie.php#125028):

> To add the "samesite" attribute, you can concatenate it to the path option...

```php
<?php
    setcookie('cookie_name', 'cookie_value', 0, '/; SameSite=strict');
?>
```

**Comment by viktorix** [comment]
PR for this issue that hasn't been merged into WP yet, but we should consider merging with CP:
https://github.com/WordPress/wordpress-develop/pull/687/files

**Comment by KTS915** [comment]
Just wanted to point out that it seems there's already a function called `wp_setcookie`: https://core.trac.wordpress.org/ticket/37000#comment:35
