### ISSUE TITLE
Add Chinese support 💡 

### ISSUE THREAD

**Issue by ramlinshione** [ClassicPress/ClassicPress#1228]
### Context

I like the ClassicPress very much
It is easy , simple and fast
I hope that it will be added Chinese support

### Will you be able to help with the implementation?

Yes,i'd like to.

**Comment by alexlii1971** [comment]
我是华人， 你需要哪方面的支持？

**Comment by viktorix** [comment]
We are working on v2.0 and will be working on translations. Most likely, we will use our existing Crowdin account to manage it. I will post here when we're ready for translations. Any help is welcome and appreciated!

**Comment by heybran** [comment]
I can help translate as well.

**Comment by mattyrob** [comment]
If anyone is still interested in contributing a translation we are now all set up at CrowdIn, this is the link to our Project Page:
https://classicpress.crowdin.com

If you need a new language locale adding please let us know.

**Comment by mattyrob** [comment]
Closing this issue now; translations are processed in the ClassicPress CrowdIn project.
