### ISSUE TITLE
📝 Final v1.6.0 of 1.x branch 

### ISSUE THREAD

**Issue by viktorix** [ClassicPress/ClassicPress#1236]
Before releasing v2.0, we need to release v1.6.0 with some minor changes. This issue will document the necessary changes:

- [x] #1240
- [x] #1244
- [x] #1206 

Leave a comment if there is anything else we should include in v1.6.0.

**Comment by viktorix** [comment]
Should #1170 be included?

**Comment by viktorix** [comment]
We also need to decide if any outstanding work for issue #1098 should be completed or issue closed.

**Comment by smileBeda** [comment]
For "Hide security Page" there's this PR here which could be used: https://github.com/ClassicPress/ClassicPress/pull/1206
Hope it helps!

**Comment by viktorix** [comment]
@smileBeda thanks for heads up.

**Comment by xxsimoxx** [comment]
Should we add a deprecation for PHP < 7.4 support?

**Comment by mattyrob** [comment]
We certainly need to warn users that when they update to CP v2 they need PHP >= 7.4

**Comment by viktorix** [comment]
The last PR is being worked on and, hopefully, we can get RC1 out next week.

**Comment by viktorix** [comment]
All PRs have been merged, and work has been completed on 1.6.0.
