### ISSUE TITLE
Increment security by removing filters from escaping/sanitization functions?

### ISSUE THREAD

**Issue by smileBeda** [ClassicPress/ClassicPress#1243]
### Context

WPCS is discussing https://github.com/WordPress/WordPress-Coding-Standards/issues/2241#issuecomment-1603481798

I was thinking, maybe this is something CP can explore (in v2?)
I am not a fan of removing filters, on the other hand, is it really smart to allow filtering of functions that are supposed to make things secure?

BTW, I find it intriguing that WP is capable of ruining everyone's day by forcing 💩 like blocks down everyone's throat or breaking shortcodes in minor releasees, but seemingly maybe could consider an actual _security_ feature a "backwards breaking change" :D
_But anyway, this the nature of things is._

### Possible implemantion

For example, remove `return apply_filters( 'attribute_escape', $safe_text, $text );` from `esc_attr`, or `return apply_filters( 'esc_html', $safe_text, $text );` from `esc_html`

It would be a breaking change, yes, but the v2 would be an opportunity for that?

### Will you be able to help with the implementation?

I would be able to contribute to the removal of such filters, if the community decides it is an OK thing to do

Maybe, instead of removing the filters, we could leave them in, but, throw a PHP notice when they are used? Or, only apply the filters if a certain (new) setting is chosen in the Admin area by Admins? Something like "Allow unsafe filtering of security functions".

**Comment by xxsimoxx** [comment]
Speaking from a SemVer point of view, we can and  should deprecate those filters in 1.6 and remove in 2.0.

From my point of view, said that any plugin is admin and in a standard enviroment can just bring that filters back, as well as erase the whole db or change your admin password, I don't see any noticeable security improvement in removing such filters.
