### ISSUE TITLE
Request: Freenode IRC channel please

### ISSUE THREAD

**Issue by stefanos82** [ClassicPress/ClassicPress#125]
I have just logged in on WordPress channel and has 369 logged in users.

If we had an IRC channel ourselves, it would be a lot easier to attract new users and why not candidate volunteers?

I have deleted my slack account because before I knew it, I had surpassed the amount of free storage.

Also, are there any plans for assembling a mailing list?

**Comment by nylen** [comment]
cc @dsnid3r @striebwj

**Comment by nylen** [comment]
cc @senlin also

This is up to the community team, but my thoughts are that adding an IRC channel now would further fragment our community.

> are there any plans for assembling a mailing list?

Yes!  @scottybo will know more about the status of these efforts.

**Comment by senlin** [comment]
@stefanos82 - thanks for your interest and suggestion.

As @nylen already wrote, IRC is not likely as we do not want to fragment our community too much. In the beginning Slack was selected and we will stick with that for the time being. I'm not saying it is written in stone that there never will be an IRC channel, just for now we have so many _plates in the air_ so to speak, that we stick with what we have.

Regarding the mailing list, there already is one and you can subscribe to it via the website: https://www.classicpress.net (scroll down a bit).

Hope this helps!

**Comment by Tmeister** [comment]
@senlin I think that @stefanos82 is talking about a community mailing list where you can send and reply email like `http://lists.automattic.com/mailman/listinfo/wp-hackers/`, not a notification list.

**Comment by stefanos82** [comment]
@Tmeister indeed I meant something SQLite's mailing lists:

![image](https://user-images.githubusercontent.com/1777466/46824013-66e7f200-cd98-11e8-8b5c-190d5e9a43f8.png)

**Comment by senlin** [comment]
Sorry for the misunderstanding. I have no idea about any of these. 

As I explained above, I think our priorities are elsewhere at the moment, but it is certainly something to keep in mind for the future (after release of v1).

**Comment by stefanos82** [comment]
@senlin the reason I have suggested the creation of an IRC channel is because it is and would be a lot easier to attract WordPress users that look for alternatives.

Besides, WordPress already has a channel under Freenode server for a number of years now.

Also, it's free without Slack's limitations.

For simple users, it can come quite handy.

With the existence of an IRC channel it would be a lot quicker for them to join in and ask whatever they like, whereas ClassicPress's current communicative model restricts any interested candidate to join slack for the sake of asking pretty much anything.

Personally I didn't like the use of Slack due to the pressure of paying to access all of my logs at a future time.

As far as I know, WordPress keeps slack for core development, whereas IRC channel is used for community interaction and helping newbies most of the time with generic issues.

Even though you say we shouldn't fragment our community, my humble opinion is we must act as fast as possible and that means now I'm afraid.

In case you haven't noticed it, @scottybo [commented on an accessibility article](https://wptavern.com/wordpress-accessibility-team-lead-resigns-cites-political-complications-related-to-gutenberg#comment-263879) and was silenced in a direct way with the excuse of promoting his fork.

ClassicPress needs to act fast and that means covering all media possible.

People have had enough and they need to speak up, to have their voices heard.

IRC is one of their medium.

**Comment by dsnid3r** [comment]
Hey @stefanos82 so I’d like to expand on what some others have said, currently we’re using Slack for our team development and communication but i’d like to explain some more reasoning behind it being the right move to only use one platform. While the idea of an IRC chat to get the people who would want to convert over in theory sounds like a great and simple solution a few factors are to take into account. If you look at the WordPress IRC it’s transitioned heavily in recent years where a community is unreachable other than a couple peek hours during the day. Majority of the “active” users aren’t really active but rather just always logged in and the access to platform contributors or “experts” aren’t as available as they would be on Slack. As a smaller community currently we wouldn’t be able to offer the same level of support and expertise. In the coming weeks we’ll begin rolling out our new site which will start to incorporate more community features. I do thank you for the suggestion and is absolutely something that we should consider in the future as we grow. 
Thanks,
Dustin Snider
Community Team Lead

**Comment by stefanos82** [comment]
Fair enough.

**Comment by rosswintle** [comment]
I know this is closed, but I was browsing closed issues to see what you guys have achieved so far. Slack’s limitations are unhelpful. I wondered if you had considered Spectrum? It just got acquired by GitHub and had all its features opened up for free (as far as I can tell) and so probably has a good future. Might be worth considering.

**Comment by striebwj** [comment]
@rosswintle I like the look of Spectrum. Let me see what others think as it does seem to have everything we are looking for.

**Comment by ginsterbusch** [comment]
This one? https://github.com/SpectrumIM/spectrum2
If its easier to use / offers more features over matterbridge, I'm all in.

cu, w0lf.

**Comment by striebwj** [comment]
No, this one: https://github.com/withspectrum/spectrum

They were just acquired by Github.

**Comment by ginsterbusch** [comment]
Ah, yet another node.js abomination...

cu, w0lf.

**Comment by rosswintle** [comment]
> Ah, yet another node.js abomination...

I would love ClassicPress to be a welcoming, friendly open-minded community of developers. But it seems like one where people make unjustified snap judgements about other people's tools and frameworks. Please don't be like this. You are better than this.

**Comment by ginsterbusch** [comment]
Well, React is another one of these. Guess what Gutenborg is commited in :)

Also, I'm not a big friend of JS backend orgies (starting with stuff like Gulp, Grunt and the likes: having never understood why I should replace all those perfectly working tools that are already in place on Unix derivates for some more complex, non-system native utilities). Yep, I'm not a fancy new-tech fanboy :)

Aside of that, the main issue I've got with this JS abomination is: No android app? No other desktop applications than for Mac? Accessibility? Usability? And how in the name of bog is this going to be a better choice than Slack, RocketChat or the originally suggested IRC?

cu, w0lf.

ps: Yes, I do totally understand the notion of wanting to get everything done in the same, or at least similar, programming language. Yes, I do commit PHP-cli obscenities all the time, although I know bash + the GNU utility collection would do the job much, much better .. still - thats just for MY OWN entertainment. Its not something I'd bother others into.
pps: JS seems to make people horribly lazy .. which is another reason why I'm not so happy about JS backend orgies: https://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos/

**Comment by rosswintle** [comment]
It was just a suggestion to look into.  I don't see how what it is built with affects the choice to use it or not. I don't see that ClassicPress is developing the tool that the ClassicPress team will use to communicate.

Apps are coming. And now it's owned by GitHub/Microsoft it will probably get invested in some more.

I have no idea how accessibility and usability compare to that of Slack or other tools.

As for comparing to other tools:

vs Slack:
 - Spectrum is unlimited and free. Slack will lose its message history unless someone pays for it.
 - Slack conversations are private - you have to sign up to see them.

vs RocketChat:
 - I've no idea because I've not used it. It's not been suggested as an alternative in this discussion. Perhaps, if you're suggesting it, you could provide some input here?

vs IRC:
 - Spectrum is more usable and easier to get going with. I get that IRC is free, open and very established in certain communities but IRC is arcane and quite user-unfriendly and has a huge barrier to entry for people who aren't familiar with it.

**Comment by rosswintle** [comment]
This was helpful. Thanks. I'll leave it for you folks to consider.

**Comment by striebwj** [comment]
We have a lot to consider when deciding what chat platform to migrate to. So, trust me, we do appreciate your input. I hadn't heard about Spectrum before. As Community Team Lead it is my responsibility to look into what platform would be suit our needs and then make the suggestion to the committee where we would vote on it. 

We tried RocketChat, and it isn't ready for production (+300 users). Instead, we have it set up as an archive so we can bypass the Slack message limites. 

IRC, while it is great for accessibility I have concerns with user-experience for everyone else. This was why we are now looking into a bridge set up where users can pick the platform they want to use and still be connected with everyone else. 

Again, thank you for your input.
