### ISSUE TITLE
Bug on ClassicPress installation

### ISSUE THREAD

**Issue by senlin** [ClassicPress/ClassicPress#128]
Encountered a bug when installing ClassicPress.

Generated the `wp-config.php` file with database name, username, password and other details and then when going to the URL to set up the site, there is an error that says:

> Sorry, I need a wp-config-sample.php file to work from. Please re-upload this file to your ClassicPress installation.

Duplicating the `wp-config.php` into `wp-config-sample.php` leads to another error, saying:

> The file wp-config.php already exists. If you need to reset any of the configuration items in this file, please delete it first. You may try installing now.

The install link goes to `wp-admin/install.php` which then continues with the regular install. 
 
## Expected behavior
Usually when pre-filling the wp-config.php file and removing the sample one, the install simply starts.

## Current behavior
It doesn't as per the error described above.

## Possible solution
I think the system should be able to check that an install can also be done from a wp-config.php file, without the sample being present?

## Steps to reproduce (for bugs)

1. upload installation package from Github
2. rename sample config to `wp-config.php` and fill in all necessary details
3. go to the site
4. error 
<img width="455" alt="installation-error" src="https://user-images.githubusercontent.com/650066/46905146-8a6d8280-cee7-11e8-9ef1-70be6fdf1091.png">

## Context
The famous 1 minute install now becomes 1.5 minutes ;)

**Comment by nylen** [comment]
I haven't seen this issue, and I am pretty sure we didn't do anything that would cause this to happen differently than WordPress... A few questions to troubleshoot:

- Did you see this once or is it reliably reproducible?
- Did you start with the contents of this repository, or a built zipfile, or something else?
- Where was the `wp-config.php` file located relative to the rest of the files?
- Were you changing the default values of `ABSPATH` or any other paths with this install?

**Comment by senlin** [comment]
Hi @nylen to answer your questions:
* saw it twice once on local once on a staging test install
* I started with the tar.gz file of [the release](https://github.com/ClassicPress/ClassicPress/releases/tag/1.0.0-alpha0)
* the `wp-config.php` file was in the root, I took the sample one filled in the data and removed`-sample` from the filename
* didn't change anything else 

Just now I tried to reproduce it and I cannot anymore, so will close this issue and if someone else experiences it or it happens again to me, we can reopen it and investigate further.

**Comment by nylen** [comment]
Ok, thanks for the report anyway, this will let us be on the lookout for anyone else with the same issue.
