### ISSUE TITLE
Deprecate Farbtastic 

### ISSUE THREAD

**Issue by KTS915** [ClassicPress/ClassicPress#1291]
### Context

Farbtastic was replaced by Iris as WP's color picker 11 years ago! See https://core.trac.wordpress.org/ticket/21206

It was kept in the WP (and not the CP) bundle only to maintain backward compatibility, but anyone using the WP color picker has been using Iris ever since. It seems like removal of Farbtastic is long overdue, but we need to deprecate it first before removing it in CP v3.

### Possible implementation

I'm not sure how deprecations are done.

Removal in v3 would mean deleting one file from each of `wp-admin/js` and `wp-admin/css` and then removing all references to Farbtastic in `wp-includes/script-loader.php`

### Possible Solution

See above

### Will you be able to help with the implementation?

I can do the removal in v3 but I don't know the procedure for deprecations.

**Comment by xxsimoxx** [comment]
Closed by #1427.
