### ISSUE TITLE
🐞 Twig not rendered after migrating WP 6.4 multisite to CP 1.7.1

### ISSUE THREAD

**Issue by elisabettac77** [ClassicPress/ClassicPress#1308]
### Expected behavior

When migrating the site to ClassicPress the admin should render twig correctly.

### Current behavior

after migrating WP 6.4 multisite to CP 1.7.1 multisite the following error appears at the top of the admin screen ' Could not render Twig with following Exception: Variable "notice_id" does not exist. ' and twig is not rendered.
![Schermata del 2024-01-19 14-50-59](https://github.com/ClassicPress/ClassicPress/assets/146635386/2006b15d-a9a2-466d-bf1f-7a975b56b315)

### Steps to reproduce bug

1. prepare a multisite WP 6.4 install
2. install the migration plugin
3. switch to ClassicPress
4. the error occurs

### ClassicPress version

1.7.1

### PHP version

8.1

### Can you help?

I can help test a solution

**Comment by mattyrob** [comment]
@elisabettac77 - Were there any plugins installed and activated? As fat as I can tell Twig is a plugin framework.

**Comment by elisabettac77** [comment]
As per chat I had with Tim and Stefanos in Zulip (#core) this issue was caused by a series of issues.
first of al the fact that an -s (underscores) theme is not fully compatible with WP/CP due to twig.
secondarily because the OpCache retained the error even after upgrading.
and third because some plugins that were previously intalled (when the multisite was WP) and were removed before switching it to CP left behind some folders and database tables (namely also Mailpoet uses twig).
Migrating WP to CP 2 RC directly on a multisite is not possible. I tried the migration from the CP 1.7.1 to v2 RC1 and it worked seamlesly and the error is no more there (this means that during the process OpCache was flushed).
This is not a direct bug of CP, but is worth mentioning somewhere in users' facing docs that some errors may occur when using themes/plugins taken from WP repos and that sometimes there is the need to deep clean the installation after deleting because the plugins do not uninstall fully.

**Comment by mattyrob** [comment]
> Migrating WP to CP 2 RC directly on a multisite is not possible. I tried the migration from the CP 1.7.1 to v2 RC1 and it worked seamlesly

Please can you clarify what you mean here? The "nighty" build is still tagged as RC1, and there are always 2 builds, one is the nightly and one is a migration build. It isn't clear and obvious but if using the migration plugin you would need to use the link to the zip file in the list of assets for the migration build.

**Comment by elisabettac77** [comment]
I tried v2 RC1 nightly zip URL. I will try to reproduce the error in switching from WP 6.4 to CP v2 RC1 nightly whith all loggin enabled to see what was going on. it stopped after unpacking files with a message along the lines of "permission denied to write to server folders" but migrating to CP 1.7.1 from the same WP minutes after that went well. and then going from that to RC went well using the URL provided in the release notes.

**Comment by elisabettac77** [comment]
For reference I used this URL https://github.com/ClassyBot/ClassicPress-v2-nightly/archive/refs/tags/2.0.0-rc1+nightly.20240119.zip

**Comment by mattyrob** [comment]
Thant may explain the failed migration, the URL should be more like:
https://github.com/ClassyBot/ClassicPress-v2-nightly/releases/download/2.0.0-rc1%2Bmigration.20240119/ClassicPress-nightly-2.0.0-rc1-migration.20240119.zip

**Comment by mattyrob** [comment]
Seems this was theme related, can reopen if needed.
