### ISSUE TITLE
WordPress/ClassicPress (WXR) Import Tool 

### ISSUE THREAD

**Issue by KTS915** [ClassicPress/ClassicPress#1339]
### Expected behavior

The Import Tool (WordPress Importer plugin) should be installable automatically and not only manually

### Current behavior

At the moment, when a user wishes to import an exported WXR file, they are told that the default Import tool (WordPress Importer plugin)  is incompatible with ClassicPress and are directed to https://docs.classicpress.net/user-guides/using-classicpress/tools-import-screen/ This tells them to download version 0.7 of the Import tool manually, and then upload it manually.

### Possible solution

The latest version of the Import tool (WordPress Importer plugin) is 0.8.2, and it is compatible with ClassicPress. We should therefore re-enable the ability to install it automatically from the CP Import dashboard. (We can then also delete the page referred to above as it will then be obsolete.)

### Steps to reproduce bug

1. Try to Import a WXR file on a site where the Import tool (WordPress Importer plugin) is not already installed.

### Context

Note that the option to specify a PHP version on this form needs updating to include PHP 8.2 and 8.3. (I'm actually using 8.2).

### ClassicPress version

2.0.0

### PHP version

8.1

### Can you help?

I can help test a solution

**Comment by mattyrob** [comment]
@xxsimoxx - I think you are on the right lines, there are code changes we need to revert and the API would need a new endpoint and we should link to that from the code.

I think t would be here:
https://github.com/ClassicPress/ClassicPress/blob/fc2c79db16fffd365ca1aa50481659900af76b84/src/wp-admin/includes/import.php#L152

**Comment by xxsimoxx** [comment]
[Pull request](https://github.com/ClassicPress/ClassicPress-APIs/pull/101) opened for the API part.
Once merged can be pulled to the server (it's a new standalone endpoint) so I can open a PR for the core part.
