### ISSUE TITLE
WP version still shows in At a Glance dashboard widget

### ISSUE THREAD

**Issue by senlin** [ClassicPress/ClassicPress#138]
Although replaced almost everywhere else, the WP version is still showing in the admin footer and in the At a Glance dashboard widget.

Will replace `get_bloginfo( 'version', 'display' )` with `classicpress_version()`

**Comment by nylen** [comment]
I think this is part of #44, which is probably still too big to be directly actionable.  Thanks for breaking out this specific task into its own issue.
