### ISSUE TITLE
🐞 Plugins: Modal window doesnt open (TypeError: f.showModal is not a function)

### ISSUE THREAD

**Issue by ginsterbusch** [ClassicPress/ClassicPress#1386]
### Expected behavior

Clicking on "View version (...) details" in the Plugins overview screen should display a modal window with details to the current (updatable) version of the plugin.

### Current behavior

The modal window, that would normally appear when clicking on "View version (...) details" in the Plugins overview screen, does not open, because of an error in plugin-install.min.js: 

`TypeError: f.showModal is not a function`

### Possible solution

Probably make sure that the minified version of plugin-install.js includes the latest changes, too?
I'm aware that there is currently a move going on to replace the ancient jQuery ThickBox script with something more modern .. 

Workaround: Open "details" links in new tab. Which works thanks to unobtrusive JS.

### Steps to reproduce bug

1. Install latest nightly build ( 2.0.0+nightly.20240407)
2. Add a slightly outdated plugin of your choice
3. Go to the admin plugin section and do as described above.

### ClassicPress version

2.0.0+nightly.20240407

### PHP version

8.2

### Can you help?

I can help test a solution

**Comment by mattyrob** [comment]
@ginsterbusch - I have not yet been able to reproduce this issue, I wonder if it could be due to JavaScript file caching in the browser or on the site - if you are using a plugin to cache files can you clear the cache and then try a forced browser reload (usually `shift` on the keyboard held down and then reload in the browser)

**Comment by xxsimoxx** [comment]
I'm not able to reproduce the issue too.

**Comment by KTS915** [comment]
I can't reproduce it either.

**Comment by ginsterbusch** [comment]
Its still broken. And DebugTools are set to "do not cache", but that was the most obvious thing I tested.
Also tested with Cache disabled.

**Comment by KTS915** [comment]
Since no-one else seems to be able to reproduce this, you need to give us more information about your setup. Are you using the latest nightly now? Are you sure it's not caused by a plugin conflict somewhere?

**Comment by ginsterbusch** [comment]
What I did: Getting the latest nightly build, uncompressed the archive, did a full file search for "showModal".

That call exists exactly in ONE file (plugin-install.js), and NOWHERE else. And its just a call (dialog.showModal();), there is NO function!
So its indeed trying to call a non-existing function, which is why it doesnt work.

After further digging, I found this: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

And now I get it, you introduced breaking changes: Its part of newer JS, that should in theory work, but apparently doesnt. Thickbox worked because its BACKWARD compatible.

Suggested fix: Add a fallback option, eg. using jQueryUI (ex. https://jqueryui.com/dialog/) or Tingle.js (https://tingle.robinparisi.com/). I am calling it "fallback", but I dont remember the correct English word right now.

Other options: Fallback / Backward Compatiblity plugin (as long as it allows injecting a shim that gets the job done, all is well).

**Comment by KTS915** [comment]
There is no function in CP called `showModal()` because it's actually built-in to the JavaScript API for the `dialog` element: https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/showModal

This is widely supported: https://caniuse.com/?search=showModal

So something else is afoot on your site. Maybe you are using a browser that CP doesn't claim to support?

**Comment by ginsterbusch** [comment]
> There is no function in CP called `showModal()` because it's actually built-in to the JavaScript API for the `dialog` element: https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/showModal
> 
> This is widely supported: https://caniuse.com/?search=showModal
> 
> So something else is afoot on your site. Maybe you are using a browser that CP doesn't claim to support?

The browser I'm using is Pale Moon, which still uses the XUL-based engine, which is being used because I. AM. _DISABLED_, and Firefox has managed to finally break all the little helpers available to both a SIGHT-disabled AND autistic person (lets not talk about Chrome, thats even WORSE). Interestingly, before the current update of the Nightly, it didnt work in any browser, so some change must have happened.

**Comment by KTS915** [comment]
There weren't any changes relating to this in the latest nightly. There haven't been any changes to this for some time. You can check the list of changes made here: https://github.com/ClassicPress/ClassicPress/pulls?q=is%3Apr+is%3Aclosed 

As comments from three of us earlier in the thread showed, it was working in other browsers before.

One of the very reasons for this particular change is that the `dialog` element has recently become accessible for those using screen readers. Maybe it's time for Pale Moon to adopt it.
