### ISSUE TITLE
💡 Change Hello Dolly

### ISSUE THREAD

**Issue by xxsimoxx** [ClassicPress/ClassicPress#1430]
### Context

- The plugin is not passing WPCS
- The plugin is not passing CPCS
- The plugin is not a good source for new plugin developers

### Possible implemantion

- Remove Hello Dolly
- Fix WPCS, CPCS and headers
- Rewrite the plugin using namespaced, object oriented code

### Will you be able to help with the implementation?

I can open a PR.

**Comment by mattyrob** [comment]
I'd suggest we remove / replace Hello Dolly, I've never particularly been a fan.

**Comment by KTS915** [comment]
> I'd suggest we remove / replace Hello Dolly, I've never particularly been a fan.

I'd go for complete removal. It's just a waste of space.
