### ISSUE TITLE
💡 Disable attachment pages for new ClassicPress installations.

### ISSUE THREAD

**Issue by KTS915** [ClassicPress/ClassicPress#1434]
### Context

I always disable attachment pages (using Greg Schoppe's code at https://gschoppe.com/wordpress/disable-attachment-pages/).

WordPress has now caught on. See https://core.trac.wordpress.org/ticket/57913 But they messed up the implementation, so there are several changesets to get it done properly:

https://core.trac.wordpress.org/changeset/56657
https://core.trac.wordpress.org/changeset/56658
https://core.trac.wordpress.org/changeset/56711
https://core.trac.wordpress.org/changeset/57357
https://core.trac.wordpress.org/changeset/57358

### Possible implementation

Presumably this can be done by using the above changesets.

### Will you be able to help with the implementation?

 I don't know how to implement multiple changesets. But I can help test the solution.

Unlike WP, I'd also like to see us add a toggle or checkbox somewhere, so that a site administrator can easily disable attachment pages on old sites and enable such pages on new sites. But I think that belongs in a separate PR.

**Comment by StonehengeCreations** [comment]
There is already a "hidden" option to disable attachment pages completely, although it is not listed in the Admin.

Run this code **once** from your functions.php:
`update_option( 'wp_attachment_pages_enabled', false );`

Or go to `https://www.yourdomain/wp-admin/options.php`, find the `wp_attachment_pages_enabled` entry using the keyboard <kbd>Ctrl + F</kbd> and replace `1` with `0`. 
Then press <kbd>Enter</kbd> to save (or scroll all the way down for the submit button).

Once disabled all attachments will be shown in the browser using `/wp-content/uploads/image.jpg` automatically.
I double checked and this also works if an image has been inserted into a post/page using the Media Library `Link to` dropdown options `Media File` as well as `Attachment Page`.

To implement this for everyone, adding a simple checkbox in `Settings > Media` (file: `/wp-admin/options-media.php`) would most likely suffice, much like the `uploads_use_yearmonth_folders` option.

**Comment by KTS915** [comment]
Yes, I'm aware of all that. The point of opening this ticket is as a reminder to make things user-friendly.

PR #1436 does the bulk of the work.

> To implement this for everyone, adding a simple checkbox in Settings > Media (file: /wp-admin/options-media.php) would most likely suffice, much like the uploads_use_yearmonth_folders option.

PR #1437 achieves that.

**Comment by xxsimoxx** [comment]
@iljester #1437 is all about adding this feature to the media options page.

**Comment by iljester** [comment]
In any case, I would like to point out that `wp_attachment_pages_enabled` is only available from version 6.4 of WP.  I didn't find it in my installation.

https://make.wordpress.org/core/2023/10/16/changes-to-attachment-pages/

**Comment by xxsimoxx** [comment]
Thank you, that is backported in #1436 that's not already merged.
