### ISSUE TITLE
Update throws error for 2.1 🐞 

### ISSUE THREAD

**Issue by tradesouthwest** [ClassicPress/ClassicPress#1468]
### Expected behavior

Upgrading as per admin notice banner from Updates screen.

### Current behavior

Updating throws errors:
`PHP Fatal 	Uncaught Error: Call to undefined function maybe_upgrade_translations()Stack trace: #0 /wp-admin/includes/class-core-upgrader.php(211): update_core('/home/leadspil/...', '/home/leadspil/...') #1 /wp-admin/update-core.php(740): Core_Upgrader->upgrade(Object(stdClass), Array) #2 /wp-admin/update-core.php(965): do_core_upgrade(false) #3 {main} thrown in /wp-admin/includes/update-core.php on line 786WordPress core
File: [/wp-admin/includes/update-core.php](https://github.com/WordPress/wordpress-develop/blob/6.2.5/src/wp-admin/includes/update-core.php)
Line: 786`

### Possible solution

Not sure, but this could already be an issue flagged but did not see it in Issues. source: File: [/wp-admin/includes/update-core.php](https://github.com/WordPress/wordpress-develop/blob/6.2.5/src/wp-admin/includes/update-core.php)

### Steps to reproduce bug

ClasicPress Update on shared hosting via the admin pages.

### Context

![Screenshot_2024-06-13_08-15-22](https://github.com/ClassicPress/ClassicPress/assets/2350010/747ac523-6ff9-4afd-b993-6e97c6bf6654)

### ClassicPress version

2.1

### PHP version

8.0

### Can you help?

I can help test a solution

**Comment by mattyrob** [comment]
Please can you provide more details about how this site was originally set up, if / how it was migrated to ClassicPress and how the update was applied? I'm curious as the fatal error message links back to WordPress.

**Comment by tradesouthwest** [comment]
Checking `function update_core( $from, $to ) {}` inside wp-admin/update-core.php file has several filters that could be related like `update_feedback`  but the error looks like it is thrown after maintenance mode diabled and then after opcache_invalidate on line 785/6 `translation-install require()` So what it is saying is that there is an illegal call to `Call to undefined function maybe_upgrade_translations()` which might mean the function is not defined correctly in wp-admin/includes/translation-install file. Will check.

**Comment by tradesouthwest** [comment]
Line 321 in translation-install file has a conditional that might need to be checking for an object in an array rather than checking for an empty state. Maybe it should be checking for `size_of()` function instead. 

Or more likely is that the conditional should be written as `if ( ! $failed ) {}` and not `if ( !empty( $failed ) ) {}`

**Comment by tradesouthwest** [comment]
@mattyrob To answer your question: ClasicPress Update on shared hosting via the admin pages. Was originally installed via cPanel and I have several CP sites on same host account. Will check the others today.

**Comment by KTS915** [comment]
@tradesouthwest I presume that the other sites updated without a problem. Is that right?

**Comment by mattyrob** [comment]
Looking at the site URL it seems to now be running on 2.1.0.

Did the update apply cleanly or was it applied and the error seen? Is there any caching running on the site?

There is a new function `maybe_upgrade_translations()` in `wp-admin/includes/translation-install.php` of ClassicPress, but it looks like on this shared hosting the install is still pointing at the WordPress GitHub repository.

**Comment by mattyrob** [comment]
@tradesouthwest - is there any update or recurrence of this issue or can we consider closing this now?

**Comment by tradesouthwest** [comment]
Have not been able to reproduce to issue so lets close this ticket.
