### ISSUE TITLE
ClassicPress logo disappeared when installed on sub folder.🐞 

### ISSUE THREAD

**Issue by ve3** [ClassicPress/ClassicPress#1479]
### Expected behavior

The logo in admin pages on top left (text left to right mode) always show. This logo should be on top above dashboard icon.

### Current behavior

The logo disappeared in all admin pages.

### Steps to reproduce bug

1. Install ClassicPress in sub folder for example **/classicpress** and use URL as `https://localhost/classicpress`. No change any settings, no change permalink.
2. Login to admin pages and access any URL in **/classicpress/wp-admin**.
3. The logo should be appears on top left (for normal text left to right mode).

### Context

When inspect via network inspector, it loaded logo image from **/wp-admin/images/classicpress-logo-white.svg?ver=202303** (error 404) while ClassicPress was installed in sub folder **/classicpress**. So, it should be loaded logo image from **/classicpress/wp-admin/images/classicpress-logo-white.svg?ver=202303**

### ClassicPress version

2.1.1

### PHP version

7.4

### Can you help?

No, I can't help

**Comment by mattyrob** [comment]
@ve3 - thank you for submitting this issue.

There are two documented ways to install ClassicPress / WordPress in a sub-directory as detailed [here](https://developer.wordpress.org/advanced-administration/server/wordpress-in-directory/).

Can you advise which of these 2 methods you followed, or have you found it to be an issue with both?

**Comment by ve3** [comment]
I install ClassicPress in /classicpress folder and use this as URL to start installation. So, the closest method from the link above is 2 but from what I inspected more...
Your CSS from **admin-bar.css** on line 508 use this.
```
background-image: url(../../wp-admin/images/classicpress-logo-white.svg?ver=202303);
```
And this CSS file is located at **/classicpress/wp-includes/css/admin-bar.css**.

From admin pages, the **load-style.php** loaded this CSS file and output as one CSS inside PHP itself but **load-style.php** is located at **/classicpress/wp-admin/load-style.php**. 
So, this means the logo svg will be refer from this PHP file not **admin-bar.css** file and this PHP is 1 level depth less than CSS file. That's why the result becomes 404 on svg logo.

**Comment by ve3** [comment]
**/classicpress/wp-admin/load-style.php**
**/classicpress/wp-includes/css/admin-bar.css**

The folder depth is different. I think you should not use PHP to load and display CSS that contain related path or not use related path in the CSS the can be loaded in PHP file. Or... maybe rewrite the related path in PHP before response to browser.

**Comment by mattyrob** [comment]
I can reproduce. Needs PR now. Can discuss as core meeting.

**Comment by ginsterbusch** [comment]
Could be fixed by using a "reduced to the max" embedded SVG image in CSS (ie. using url(data: ..), eg. https://css-tricks.com/data-uris/).

cu, w0lf.

**Comment by KTS915** [comment]
Just don't base64 encode it: https://css-tricks.com/probably-dont-base64-svg/

**Comment by ginsterbusch** [comment]
> Just don't base64 encode it: https://css-tricks.com/probably-dont-base64-svg/

To quote from stackoverflow:

> To reply to the "You probably shouldn't base64 SVGs" comment(s). If you are wild beast base64 encoding an entire svg library, reconsider your decisions so far and don't base64 the world. However, if you are making a module or plugin and want to embed very small SVG instead of including an entirely new file, please do that. Including one base64 encoded SVG instead of another directory dependency is worlds easier for you and someone who uses your small module / plugin.

Source: 
https://stackoverflow.com/questions/10768451/inline-svg-in-css/21626701#comment118303581_21626701

**Comment by KTS915** [comment]
Avoiding base64 encoding doesn't mean what that commenter thought it means. Once you're using SVGs, you're using XML already, so there's no need for base64, which would make the file larger.
