### ISSUE TITLE
💡 Address Safari's reluctance to visually indicate focus on certain elements

### ISSUE THREAD

**Issue by KTS915** [ClassicPress/ClassicPress#1545]
### Context

See https://github.com/ClassicPress/ClassicPress/pull/1542#issuecomment-2357782580 and https://itnext.io/fixing-focus-for-safari-b5916fef1064

### Possible Solution

It's worth investigating whether simply adding the CSS selector `:focus-visible` to appropriate elements might be enough. Otherwise we might need to use a polyfill.

### Will you be able to help with the implementation?

Yes

**Comment by mattyrob** [comment]
Tested in Safari v18 and looks better in this PR:

Current `develop`:
![Screenshot 2024-10-06 at 15 41 04](https://github.com/user-attachments/assets/9dcc9e05-5e2c-4a1a-a7ab-7a40d1492f54)

This PR:
![Screenshot 2024-10-06 at 15 41 45](https://github.com/user-attachments/assets/50cc8c0b-9082-454f-9d89-b99418d84c37)
