### ISSUE TITLE
Packaging ClassicPress as a Docker image on ghcr.io

### ISSUE THREAD

**Issue by bohdan-shulha** [ClassicPress/ClassicPress#1559]
### Context

Hi there,

I'm a founder of a platform that allows you to self-host virtually any service packaged as a Dockerfile.

In the scope of WP drama, I would love to add ClassicPress as a 1-click app template to the service.

Would you consider creating a GitHub workflow to build and publish an image to GitHub's Docker registry?

### Possible implemantion

Similar to Bitnami's image for Wordpress

https://github.com/bitnami/containers/tree/main/bitnami/wordpress

### Will you be able to help with the implementation?

Unfortunately, I don't have the capacity to work on this feature.

However, I'll create a 1-click app for my platform.

**Comment by KTS915** [comment]
Thanks very much for the offer. We don't have something immediately available, but we're going to look into it

**Comment by techkodeninja** [comment]
Hello @bohdan-shulha 

We do have an official ClassicPress image but it may be on PHP 7.4. do you need an alternative PHP version for your project. I'll be helping you out with this.

**Comment by bohdan-shulha** [comment]
Hey,

Thanks for the answer.

I'm so sorry, I didn't find the docker image on the first try.

https://hub.docker.com/r/classicpress/classicpress

This is more than enough.

Thank you!

**Comment by fwilhe2** [comment]
> https://hub.docker.com/r/classicpress/classicpress

Is this an official image? It looks like it only has a latest tag and that was pushed a year ago. Given that the last release of CP is a few weeks ago, I guess this contains an outdated version that probably should not be used.

**Comment by techkodeninja** [comment]
Is the official image. According to what I remember, when you deploy, it downloads and extracts the latest version of CP. please let me know so I'll take a look at it

**Comment by bohdan-shulha** [comment]
Is there any documentation? I'm looking for the data directory name and essential env variables.

Something like this: https://github.com/bitnami/containers/tree/main/bitnami/wordpress

**Comment by techkodeninja** [comment]
I haven't done any documentations for the official image, but  those variables i believe is CLASSICPRESS_XXXX_XXX which is the same format as WORDPRESS, so just replace WORDPRESS with CLASSICPRESS.

I am in the process of adding new images and create docs for it soon.

**Comment by techkodeninja** [comment]
hello everyone, I have successfully added new images for ClassicPress, you may now use 7.4, 8.0, 8.1, 8.2, and 8.3 from our official docker hub https://hub.docker.com/r/classicpress/classicpress/tags

**Comment by howardshand** [comment]
@techkodeninja, can you set the _latest_ tag to use the default/recommended version?

**Comment by techkodeninja** [comment]
@howardshand: definitely can. please give me a few day or so to get it tagged. the latest tag might be 8.3. is that okay! since 8.4 is currently not available due to imagick issue.

**Comment by howardshand** [comment]
8.3 is fine, just important that it reflects what's actually the latest published image.

**Comment by techkodeninja** [comment]
I'll try to get it done by the end of the day.

**Comment by techkodeninja** [comment]
@howardshand apology, the latest has been updated to 8.3 at the moment, we have 8.4 as one of the tags now. I'll find time to move the latest to 8.4 this week.
