### ISSUE TITLE
🐞 ClassicPress Pepper for Passwords plugin not updating on CP update

### ISSUE THREAD

**Issue by xxsimoxx** [ClassicPress/ClassicPress#1581]
### Expected behavior

ClassicPress Pepper for Passwords plugin should update when a new version is shipped by a new core version.

### Current behavior

ClassicPress Pepper for Passwords is not updated when updating to new nightly build.

### ClassicPress version

Nightly

### PHP version

8.3

### Can you help?

I can help test a solution

**Comment by mattyrob** [comment]
I think I have tracked this back to a line in `wp-admin/includes/update-core.php` that checks if the `$_new_bundled_files` entry already exists and skips writing it if it's already there.

One potential solution is to add the plugin to the directory and push updates on there.

**Comment by xxsimoxx** [comment]
That can be a solution, but the Directory Integration plugin is used on less than 10% of the CP installation. Another way can be to exclude the plugin from that check.

**Comment by mattyrob** [comment]
Maybe there is also another way to accomplish this in the core code. I'm fairly sure the Hello Dolly plugin had updated pushed out with core updates in WordPress.

**Comment by ginsterbusch** [comment]
@mattyrob Or the Akismet plugin. But yeah, this was my thought, too.

cu, w0lf.

**Comment by xxsimoxx** [comment]
Seems that Akismet get updated using WP repo.
If we choose to use our directory for core plugin, my idea is to have a GitHub repo to just handle releases.
[This repo](https://github.com/xxsimoxx/cp-pepper) as example. If we'll go this way I'll transfer the repo to ClassicPress org.

**Comment by mattyrob** [comment]
I do think we need this plugin in the directory, but I may have a way to push an update in the next release in core.

**Comment by xxsimoxx** [comment]
Good. I'll put it in the directory. We need a README.md in the plugin folder before.

**Comment by xxsimoxx** [comment]
See #1583 for the `README.md`.

**Comment by xxsimoxx** [comment]
Confirm that #1584 fixed this. Tested updating to 2.2.0+nightly.20241010.
