### ISSUE TITLE
GPLv2 or GPLv3 licensing?

### ISSUE THREAD

**Issue by marctenax** [ClassicPress/ClassicPress#16]
WordPress is licensed as GPLv2 or later and all derivative projects are GPLv2 or later, including plugins or themes, unless otherwise specified.

I think that also ClassicPress maintain this licensing methodology.

Join this discussion, and let me know how you think about it.

Vote: GPLv2 or GPLv3.

Thanks!

**Comment by Mte90** [comment]
v2 to don't have any problems on compatibility and other projects wordpress based.

**Comment by scottybo** [comment]
Makes sense - v2 it is!

**Comment by marctenax** [comment]
v2 also for me!
