### ISSUE TITLE
🐞 Backport Changeset 56939 to resolve slashing issue

### ISSUE THREAD

**Issue by KTS915** [ClassicPress/ClassicPress#1603]
### Expected behavior

A slash too many with the `get_pagenum_link()` function.

### Current behavior

See https://core.trac.wordpress.org/ticket/2877

### Possible solution

Changeset at https://core.trac.wordpress.org/changeset/56939

### Steps to reproduce bug

See https://core.trac.wordpress.org/ticket/2877

### ClassicPress version

2.2.0

### PHP version

8.3

### Can you help?

I can help test a solution

**Comment by kun18911** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
