### ISSUE TITLE
🐞 Two files lack an auto-minified version

### ISSUE THREAD

**Issue by KTS915** [ClassicPress/ClassicPress#1618]
### Expected behavior

For the new Media Library grid view we have added the filepond.js library together with one ClassicPress JS file and one ClassicPress CSS file to integrate them into ClassicPress. These two files need to be added to the list of files that have a minified version automatically generated for them.

### Current behavior

There is a regular JS file and a regular CSS file, which work when script debugging is on. But there is no minified version of either for when debugging is set to off.

### Possible solution

Minify the following files:
`~/wp-includes/js/filepond/cp-filepond.css`
`~/wp-includes/js/filepond/cp-filepond.js`

### Steps to reproduce bug

Just check the `~~/wp-includes/js/filepond/` folder

### ClassicPress version

2.2.0

### PHP version

8.3

### Can you help?

I can help test a solution

**Comment by mattyrob** [comment]
There are several *.js and *.css files at the `~/wp-includes/js/filepond/` location. Do they all require minification?

![Screenshot 2024-10-30 at 09 48 10](https://github.com/user-attachments/assets/8c5fb31f-0807-4fc7-98c3-9e8b2cdf1c01)

**Comment by KTS915** [comment]
The other files there are in the format that Filepond provides. They don't come in minified form. I don't know whether it would affect their functionality if those files were minified too. Should we try and see what happens?

**Comment by mattyrob** [comment]
Thanks, that gave me a pointer.

The CSS files will both look for a minified version based on the current `script-loader.php` file and probably complain when the file is not found.

The JS will always use the unminified, so we can minify and update script-loader to use the minified file if present,

I'll get a PR done.
