### ISSUE TITLE
WP link in set up

### ISSUE THREAD

**Issue by striebwj** [ClassicPress/ClassicPress#162]
The "We got it." link in set up links to "https://codex.wordpress.org/Editing_wp-config.php"

![screen shot 2018-10-22 at 6 28 07 pm](https://user-images.githubusercontent.com/14165147/47323536-33c02100-d62a-11e8-8e37-0fcd280b99a0.png)

**Comment by nylen** [comment]
There are a lot of WP codex links still, and links to other places in WP.org like the forums.  We'll probably want to replace these when we have our own place to direct them to, which right now we don't.

**Comment by johnalarcon** [comment]
PR #265 resolves the reported issue, though does not address the additional links mentioned by @nylen.

**Comment by bahiirwa** [comment]
We now have https://docs.classicpress.net/user-guides/editing-wp-config-php/ a PR is needed to close this.

**Comment by viktorix** [comment]
I'll work on this.

**Comment by mattyrob** [comment]
Looking at the [changes](https://github.com/ClassicPress/ClassicPress/pull/265/files) made with #265 the link to the upstream Codex page has been removed and replaced with a more streamlined process.
Closing.
