### ISSUE TITLE
🐞 Comment Function Removed from Walker_Comment

### ISSUE THREAD

**Issue by dshanske** [ClassicPress/ClassicPress#1645]
### Expected behavior

My code expects the comment function inside Walker_Comment and it no longer exists.

### Current behavior

Since comment is removed, assume because HTML5 is default, only html5_comment exists. 

### Possible solution

Would suggest, for backcompat, that the comment function be restored, but simply call the html5_comment function. 

### Steps to reproduce bug

Try to call Walker_Comment::comment

### ClassicPress version

2.2.0

### PHP version

I don't know

### Can you help?

I can help test a solution

**Comment by dshanske** [comment]
I agree with switching to HTML5 by default, I just would have maintained backward compatibility for functions using it, as it wouldn't be an issue to have the function. I'm modifying my code regardless to cover both WP and CP by having it check.

**Comment by mattyrob** [comment]
@dshanske - please see PR I opened here:
https://github.com/ClassicPress/ClassicPress/pull/1646
Are you able to test this?
