### ISSUE TITLE
🐞 Clicking on "Show Details" for a Plugin Not Working

### ISSUE THREAD

**Issue by Pross** [ClassicPress/ClassicPress#1654]
### Expected behavior

When you click "Show Details" when updating a plugin it should reveal a div with the details

### Current behavior

Nothing happens

### Steps to reproduce bug

1. Update a plugin
2. Click Show Details

### ClassicPress version

Nightly

### PHP version

8.1

### Can you help?

Yes, I will submit a PR

**Comment by KTS915** [comment]
I'm not seeing this. Are you talking about a plugin from the WP repo or a plugin listed on the CP directory?

**Comment by Pross** [comment]
Well I just updated akismet as a test, clicking the link does nada for me?

**Comment by Pross** [comment]
I could reveal it with JS `jQuery('#progress-1').toggle()` so the div is there, just the click action does nothing

**Comment by KTS915** [comment]
Just to check I'm looking at the same thing as you, I am clicking on the "View Details" links on the `plugins.php` page. When I do that, I get a modal pop up and, after about half a second, it populates with all the data.

**Comment by Pross** [comment]
> Just to check I'm looking at the same thing as you, I am clicking on the "View Details" links on the `plugins.php` page. When I do that, I get a modal pop up and, after about half a second, it populates with all the data.

Negative, im on the update-core.php page, updating a plugin from there, NOT the plugins page

**Comment by Pross** [comment]
<img width="672" alt="Screenshot 2024-11-19 at 19 10 58" src="https://github.com/user-attachments/assets/9ecf45eb-4c5b-4b90-b63e-ad28ad3837d2">

**Comment by KTS915** [comment]
Aha! Gotcha.

**Comment by KTS915** [comment]
Could you try changing line 841 in `~wp-admin/js/common.js` to read as follows?
```
topMenuItems = document.body.className.includes( 'wp-admin' ) && $adminmenu[0] ? $adminmenu[0].querySelectorAll( 'li.wp-has-submenu' ) : [];
```

**Comment by KTS915** [comment]
I have now made a PR to fix this at https://github.com/ClassicPress/ClassicPress/pull/1655.

**Comment by Pross** [comment]
> @Pross Could you try changing line 841 in `~wp-admin/js/common.js` to read as follows?
> 
> ```
> topMenuItems = document.body.className.includes( 'wp-admin' ) && $adminmenu[0] ? $adminmenu[0].querySelectorAll( 'li.wp-has-submenu' ) : [];
> ```

Yep, that fixes it!
