### ISSUE TITLE
🐞 menuItem.querySelector is not a function

### ISSUE THREAD

**Issue by citrika** [ClassicPress/ClassicPress#1669]
### Expected behavior

A conditional in [**wp-admin/js/common.js**](https://github.com/ClassicPress/ClassicPress/blob/e9ce5419ad712c0b8a5a920a20c6a0a9a5d97757/src/wp-admin/js/common.js#L920) should prevent "menuItem.querySelector is not a function" error.

### Current behavior

![bug](https://github.com/user-attachments/assets/12db3137-6dfd-4675-9e87-8ca9964ac46f)

### Possible solution

![fix](https://github.com/user-attachments/assets/96085af0-7200-44ea-9d2f-a0edc7d781d4)

### Steps to reproduce bug

1. Enable "Preserve log" in Chromium-based browser console
2. Select menu item in dashboard

### ClassicPress version

2.2.0

### PHP version

8.1

### Can you help?

I can help test a solution

**Comment by KTS915** [comment]
Thanks for the report. This has already been fixed in the nightly version and will be in v 2.3.0, which is scheduled to be released on Thursday.
