### ISSUE TITLE
🐞 Uncaught SyntaxError: Unexpected end of input (at common.min.js?ver=cp_b65fdc6f:1:21316)

### ISSUE THREAD

**Issue by zcraber** [ClassicPress/ClassicPress#1683]
### Expected behavior

`wp-admin-bar-menu-toggle` and `collapse-button` should work properly.

### Current behavior

After the latest 2.3.0 update, `wp-admin-bar-menu-toggle` and `collapse-button` are not working, and the console shows the error `Uncaught SyntaxError: Unexpected end of input (at common.min.js?ver=cp_b65fdc6f:1:21316)`

### Steps to reproduce bug

1. Update CP.
2. Try the Collapse Menu and Menu Toggle.

### Context

![cp](https://github.com/user-attachments/assets/ce279522-c574-4654-a9fa-53b77b5b7aac)

### ClassicPress version

2.3.0

### PHP version

8.1

### Can you help?

I can help test a solution

**Comment by mattyrob** [comment]
I have not been able to reproduce this issue in my testing, the the following PR may be associated:
https://github.com/ClassicPress/ClassicPress/pull/1680

**Comment by zcraber** [comment]
I tested on both Edge and Brave. The issue only appears in Brave, but not in Brave's private window.

**Comment by mattyrob** [comment]
That would tend to indicate it's a browser caching issue. Have you tried a force reload, I think in Brave it's `Ctrl + F5`, or `Shift + F5` or `Ctrl + Shift + R` to force reload all resources bypassing the cache.

**Comment by zcraber** [comment]
Just tried that, and it worked! 
My bad, should have tested that before opening the issue. Will close this now.
