### ISSUE TITLE
🐞 Metabox "details" node doesn't work correctly

### ISSUE THREAD

**Issue by citrika** [ClassicPress/ClassicPress#1694]
### Expected behavior

The metabox "details" node should get the CSS classes set through the postbox_classes function and the "open" attribute should be applied accordingly.

### Current behavior

The CSS classes are not applied and the "open" attribute is lost.

### Possible solution

In: [/wp-admin/includes/template.php](https://github.com/ClassicPress/ClassicPress/blob/3a1f7d006d5e108b5b3f8d78e79806bd4688adb4/src/wp-admin/includes/template.php#L1276)

Replace:
```php
$open_attribute = postbox_classes( $box['id'], $page ) ? '' : ' open';
echo '<details id="' . $box['id'] . '" class="postbox' . $hidden_class . '"' . $open_attribute . '>' . "\n";
```

With:
```php
$classes = postbox_classes( $box['id'], $page );
$open_attribute = str_contains( $classes, 'closed' ) ? '' : ' open';
echo '<details id="' . $box['id'] . '" class="postbox ' . $classes . $hidden_class . '"' . $open_attribute . '>' . "\n";
```

### Steps to reproduce bug

1. Add a custom CSS class to an existing metabox in a "post" post type edit screen:
```php
add_filter( 'postbox_classes_post_submitdiv', 'custom_metabox_classes' );
function custom_metabox_classes( $classes ) {
  array_push( $classes, 'test' );
  return $classes;
}
```
2. The "submitdiv" metabox node doesn't get the custom class and the "open" attribute is lost.

### Context

Some custom fields plugins, like Meta Box, don't work correctly. ACF works correctly because it adds the classes through Javascript.

### ClassicPress version

2.3.1

### PHP version

8.1

### Can you help?

I can help test a solution

**Comment by mattyrob** [comment]
Thank @citrika for an excellent bug report and your proposed fix. I have confirmed this issue and created a pull request.

**Comment by KTS915** [comment]
While I can confirm the issue, the proposed fix causes a problem with the Custom Fields metabox. It also reverses the default behavior of metaboxes.
