### ISSUE TITLE
🐞 Dashed lines in post edit screen when Meta Box plugin is installed

### ISSUE THREAD

**Issue by citrika** [ClassicPress/ClassicPress#1695]
### Expected behavior

The post edit screen shouldn't contain the dashed lines.

### Current behavior

Dashed lines related to the sortable functionality appear when Meta Box plugin is installed.

### Steps to reproduce bug

1. Install Meta Box.
2. Add custom fields, for example:
```php
add_filter( 'rwmb_meta_boxes', 'custom_metabox_fields' );
function custom_metabox_fields( $meta_boxes ) {
  $meta_boxes[] = [
    'title'      => 'MB Field Group',
    'id'         => 'mb-field-group',
    'post_types' => ['post'],
    'context'    => 'normal',
    'closed'     => false,
    'fields'     => [
      [
        'type' => 'checkbox',
        'name' => 'Featured',
        'id'   => 'featured',
        'std'  => true,
      ],
    ],
  ];
  return $meta_boxes;
}
```

### Context

[Styling issues in ClassicPress](https://github.com/wpmetabox/meta-box/issues/1621)

### ClassicPress version

2.3.1

### PHP version

8.1

### Can you help?

I can help test a solution

**Comment by mattyrob** [comment]
May well be linked to this:
https://github.com/ClassicPress/ClassicPress/pull/1678

**Comment by KTS915** [comment]
@mattyrob Yes, in my testing, that PR fixes this issue.
