### ISSUE TITLE
Minimum PHP version allowed on this project.

### ISSUE THREAD

**Issue by marctenax** [ClassicPress/ClassicPress#17]
Allowed support and maintaining minimum PHP 5.2+ or greater

Allowed support and maintaining minimum PHP 5.6+ or greater

Allowed support and maintaining minimum PHP 7.0+ or greater

**Comment by senlin** [comment]
Since support for 5.6 already has stopped one year and seven months ago and security support will end in 3 months, my vote is for **PHP 7.0+ or greater**

**Comment by danieltj27** [comment]
I'd really like to see ClassicPress learn from some of the mistakes WordPress has made in terms of versioning and require a minimum of PHP 5.6 and a recommended version of 7.2 if possible. Anything below that should have no guarantees that it'll work and will most definitely break.

Starting 'anew' with this fork will let the project set some 'easy wins' and make development much, much easier. It's faster and more secure anyway.

**Comment by Mte90** [comment]
WordPress core-php team is pushing to move on maybe for 5.1 for minimum requirement of php 5.3.

We need to think that if we want to be a LTS fork we need to be compatible with php 5.2.
For that reason I suggested 2 version one LTS without gutenberg, one more advanced with other changes/features/blablabla.

**Comment by senlin** [comment]
> We need to think that if we want to be a LTS fork we need to be compatible with php 5.2.

To be honest, I don't understand why we need to think that at all. Why would it not be possible to be an LTS fork without being compatible all the way down to PHP 5.2?

**Comment by Mte90** [comment]
Because a LTS version means that we keep compatibility. Or we chose to do a version only gutenberg free with changes or we do a LTS release.

LTS means that we support people and guarantee compatibility with WordPress, and to be compatible with WordPress at 100% (like a LTS) we need to support PHP 5.2.

**Comment by senlin** [comment]
Why would it not be possible to take the meaning of LTS (so include future security updates), and at the same time cut ancient compatibility?
Doesn't matter what kind of label is put on it, I don't see why a little progress cannot be made at the same time too.

**Comment by Mte90** [comment]
LTS means compatibility so the choice of change the minimum requirements doesn't fit with that statement.
For that reason there was the idea of to do a LTS version and another version with the changes to vote etc included this one.

In that way we can have a LTS and one with this change and others.

**Comment by senlin** [comment]
Pity that things have to be(come) so complicated.

**Comment by Mte90** [comment]
I know but when a project have a large userbase it is normal that things became complicated or that need of a fork/project like this will never happen.

**Comment by scottybo** [comment]
Just to pitch in here - when we get to ClassicPress Plus this is when we'll change the minimum versions of PHP. As @Mte90 mentioned, this first fork is a LTS release "as is", the goal is to maintain security updates and bug fixes. Plus will be the new kid on the block :)

**Comment by scottybo** [comment]
Closing this issue - not because it isn't a valid topic, but because it isn't going to happen for the LTS fork.
