### ISSUE TITLE
Use new ClassicPress logo images

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#172]
The ClassicPress logos in this repository are outdated.  Here are the new ones:  https://docs.classicpress.net/press-and-branding/

There is one that's not there yet and needs to be created - an updated version of ` src/wp-includes/images/classicpress-logo-dashicon-style.svg` added in #32.  It should have a fill color of `rgba(240,245,250,0.6)` as in the following CSS rule:

https://github.com/ClassicPress/ClassicPress/blob/c5f2894c468815fe1eda0a11505dcd00f18ab419/src/wp-includes/css/admin-bar.css#L243-L248

Previous PRs that modified logo images, cache busters, etc: #18, #30, #32, #149, #161

The CSS cache buster strings for the logos should also be updated.  All references to the logo in CSS _should_ be using the `?ver=20180905` cache buster, but we may have missed a couple of places.

**Comment by senlin** [comment]
I can fix these, but still need help with the creation of the `classicpress-logo-dashicon-style.svg` replacement.

**Comment by nylen** [comment]
@senlin: I've updated this file and added it to https://docs.classicpress.net/press-and-branding/.

Since it's not an "official" logo, I guess we can remove it from there after we update it in the core code, but that'll do for now.

**Comment by senlin** [comment]
@nylen: great thanks!

**Comment by senlin** [comment]
the temporary logo you created for the dashicon can now be removed from the docs page I think?

**Comment by nylen** [comment]
Yep, done in https://github.com/ClassicPress/ClassicPress-Network/commit/2916a598696ff147686e0cb910702e57331b8bbd
