### ISSUE TITLE
Remove emojis

### ISSUE THREAD

**Issue by wolffe** [ClassicPress/ClassicPress#175]
Remove emojis. Parsing the content for emojis (or smilies) can be expensive. This feature should be moved to a plugin.

**Comment by nylen** [comment]
From the issue template that you read before creating this issue:

> To suggest new features or major changes, please visit our Petitions website at:
https://petitions.classicpress.net/

This suggestion is already available there:

https://petitions.classicpress.net/posts/7/remove-emojis-gdpr-friendly
