### ISSUE TITLE
Let's Have New Welcome Text on Install Page

### ISSUE THREAD

**Issue by pftaylor61** [ClassicPress/ClassicPress#181]
This is not a big deal. However, on wp-admin/install.php, line 318, let's have some new welcome text, that is specific to ClassicPress.

<p><?php _e( 'Welcome to the famous five-minute ClassicPress installation process! Just fill in the information below and you&#8217;ll be on your way to using the most extendable and powerful personal publishing platform in the world.' ); ?></p>

This is word-for-word what WordPress has at that point. Let's have something new and sp[ecific to ClassicPress. My suggestion:

<p><?php _e( 'The ClassicPress installation process takes just five minutes! Just fill in the information below and you&#8217;ll soon be on your way to publishing, using the most exciting, classic, powerful, and versatile platform.' ); ?></p>

However, I am sure other people could produce better text. Let's just be different!

**Comment by senlin** [comment]
Thank you for reporting this @pftaylor61, now we can keep track of this.

Your suggestion did not make it in the text box though?

**Comment by yatsenko-julia** [comment]
Unfortunately, I cannot see your suggestion @pftaylor61. I wrote the text by myself and I'm ready to make any changes to it that you consider appropriate.

**Comment by senlin** [comment]
@yatsenko-julia 
Thanks for your PR #187!
I think there is a small typo in it as you wrote "ClassicPress brings all of the latest features the best modern CMS while keeping...".
Shouldn't there be something more after "the best moderns CMS"?
I also asked this question on the PR itself.

**Comment by yatsenko-julia** [comment]
@senlin 
Indeed, seems I have missed “of” which I’ve added. Not sure what you mean by ‘something more after “the best moderns CMS”’ — could you explain, please?

**Comment by senlin** [comment]
Adding "of" solves that part.
Without it, the sentence could also have become something like below, it was not entirely clear from the context which way the sentence was supposed to go :)
"ClassicPress brings all of the latest features the best modern CMS _has to offer,_ while keeping..."
