### ISSUE TITLE
Use CP Endpoint for locales

### ISSUE THREAD

**Issue by Mte90** [ClassicPress/ClassicPress#183]
## Expected behavior
Install or use ClassicPress and get the latests updates for Core the CMS instead from WordPress 

## Current behavior
Use WordPress endpoints

## Possible solution
* Do a check for `$type` that in case is `core` use the CP endpoint https://github.com/ClassicPress/ClassicPress/blob/develop/src/wp-admin/includes/translation-install.php
* Do CP endpoint for all the locales like http://api.wordpress.org/translations/core/1.0/, with support for version https://github.com/ClassicPress/ClassicPress/blob/develop/src/wp-admin/includes/translation-install.php#L46
* Scripts that every 8 hours generate the new zip with new po/mo

**Comment by Mte90** [comment]
I already created the most used locale on CP translate instance https://translate.classicpress.net/projects/core/

**Comment by Mte90** [comment]
Moved the discussion of the endpoints to https://github.com/ClassicPress/ClassicPress-APIs/issues/8.
We need to discuss about how to generate the packages for all the locales.

**Comment by nylen** [comment]
This is not going to be ready in time for beta1.  Moving to 1.0.0-beta2 milestone.

**Comment by Mte90** [comment]
The actual status is:

- Endpoint seems working, few little things to check in production
- Implement the usage of our endpoint only for core
