### ISSUE TITLE
We should not localize CP urls

### ISSUE THREAD

**Issue by Mte90** [ClassicPress/ClassicPress#184]
## Expected behavior
URls of classicpress should be not localizable to simplify the work to copy and paste because the value is the same.

## Current behavior
They are localizable

## Possible solution
Remove the usage of gettext like for https://translate.classicpress.net/projects/core/it/it/?filters%5Boriginal_id%5D=140
You can find few examples on https://translate.classicpress.net/projects/core/it/it/?filters%5Bstatus%5D=untranslated&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

**Comment by nylen** [comment]
@Mte90 can you provide examples please?

**Comment by nylen** [comment]
Ah, I see.

Are we planning to localize our websites in the future?

If so, we should probably leave the URLs as translatable until then, no?

**Comment by Mte90** [comment]
This is a good question but I am not sure when we can do that because require a lot of effort and a big community.
So maybe for the actual status is better to remove it and when we can do it we can re-enable them.

**Comment by nylen** [comment]
> So maybe for the actual status is better to remove it

The problem is this is also a good bit of effort, and then it's more effort to add the localizations back in later.

What if we exclude strings that contain only a website URL from our GlotPress instance?

**Comment by Mte90** [comment]
Well they will be parsed from the gettext system of WordPress so I am not sure if that will be the best way.

**Comment by nylen** [comment]
I would think it shouldn't be too hard to mark strings that match a specific pattern as "already translated".  But I don't know the best way, so we can accept a PR for this.

What about strings that contain `some text and a URL like <a href="https://www.classicpress.net">this</a>`?  I guess those should be translated

**Comment by Mte90** [comment]
The string with an url can be translated but strings with only the url for me are mainly the problem, because in few cases we don't have replacement like for the support right now.
Anyway is always better to avoid to localize url if the website doesn't support it, using `sprintf` to pass the url to `__(` as example is the best solution to avoid confusions to localizers.

Thinking of cleanup I think that,
We can remove the localization for this 4 strings:

- https://translate.classicpress.net/projects/core/it/it/?filters%5Boriginal_id%5D=3890
- https://translate.classicpress.net/projects/core/it/it/?filters%5Boriginal_id%5D=140
- https://translate.classicpress.net/projects/core/it/it/?filters%5Boriginal_id%5D=138
_- https://translate.classicpress.net/projects/core/it/it/?filters%5Boriginal_id%5D=81

Change the text on:

- https://translate.classicpress.net/projects/core/it/it/?filters%5Boriginal_id%5D=3528

Wondering if this strings refer to our urls:

- https://translate.classicpress.net/projects/core/it/it/?filters%5Boriginal_id%5D=5877

So after all are only few changes that doesn't break anything and in the future we can think what to do because maybe we will have our docs as example.

**Comment by nylen** [comment]
Ok, so to summarize what needs to be done:

- Do not translate strings that only contain a URL  like `https://www.classicpress.net`
- In strings that contain both text/HTML and URLs like `https://www.classicpress.net`, move the URL out into a `%s` or `%1$s` placeholder with a `/* translators: */` comment

Are you planning to work on this, or is it available for anyone to start on?

**Comment by Mte90** [comment]
If someone can work on that is better :-)
I am busy with other stuff :-)

**Comment by Mte90** [comment]
It is missing only to change the text of https://translate.classicpress.net/projects/core/it/it/?filters%5Boriginal_id%5D=3528

**Comment by nylen** [comment]
Re-opening because there is still something left to do here:

> It is missing only to change the text of https://translate.classicpress.net/projects/core/it/it/?filters%5Boriginal_id%5D=3528

> `<strong>Important:</strong> before updating, please <a href="https://codex.wordpress.org/WordPress_Backups">back up your database and files</a>. For help with updates, visit the <a href="https://codex.wordpress.org/Updating_WordPress">Updating ClassicPress</a> Codex page.`
