### ISSUE TITLE
Automatically pull changes from WP → ClassicPress

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#19]
We'll want a bot that will automatically pull changes over from the WP `4.9` and `trunk` branches into PRs against this repo (if possible), or log each commit that doesn't apply cleanly to somewhere else.

I'll start working on this next week.  I'll put the code on a separate repo under the ClassicPress org.

**Comment by danieltj27** [comment]
I don't think we should be pulling changes from WordPress once forked. I feel like the project is trying to stay as much like WordPress as possible but just hiding Gutenberg which seems easily avoidable by either not updating to 5.0 or using the Classic Editor plugin.

I feel like we should start a new repo that isn't a fork of existing repos and push the code on 4.9.8 (minus the callout) and just start working on a separate project, otherwise they'll be too much overlap with WordPress and we'll end up with an exact mirror without the supporting backbone of WordPress.org and compatibility.

I don't think a clone minus Gutenberg is the best approach. Just my opinion but I think it'll give us a better chance of survival in the CMS filled ecosystem.

**Comment by Mte90** [comment]
Well we need that changes to branch 4.9.x are updated to our fork.
For master we can see when and if there will be another project with changes.

**Comment by nylen** [comment]
> I feel like we should start a new repo that isn't a fork of existing repos and push the code on 4.9.8 (minus the callout)

This is essentially what we have here, but there is no reason to lose the commit history from WP.

> and just start working on a separate project, otherwise they'll be too much overlap with WordPress

We are not ready to do this yet - we are a long way away from an initial release.  The priority for now is ensuring that people can switch from WordPress to ClassicPress without problems, which means keeping in sync with WP.

**Comment by marctenax** [comment]
Why would a typical user switch to ClassicPress if it is exactly the same as WordPress?

What do we offer differently, to intrigue, and make the switch?

**Comment by danieltj27** [comment]
> Why would a typical user switch to ClassicPress if it is exactly the same as WordPress? What do we offer differently, to intrigue, and make the switch?

Exactly this.

Currently you can get the 'ClassicPress' experience by just using a plugin to remove the callout. I don't think a fork is quite the right term if all is happening is removing anything Gutenberg.

**Comment by nylen** [comment]
I agree, to an extent.  But you are confusing the **short term** and **long term** needs of the project.  How we differentiate ourselves from WordPress is a conversation to have **after** we've proven that we can build and release a working product.

**Comment by marctenax** [comment]
WordPress already provides updates and support for the last 10 versions.

**Comment by nylen** [comment]
For now, [ClassicPress Slack](https://join.slack.com/t/classicpress/shared_invite/enQtNDIwNjY2OTg1MjAxLWJiM2U2NmY3ZjFlZjQ4Zjk2OGI4ZTg3NzY1ZTU3NzI3OTRjMTU0YzAzOWUyZmZlODgyOWE1YTViYjcwY2Y5YzI) is a better place for larger discussions about the purpose of ClassicPress and its long-term plans.  This is a specific technical issue for a task that needs to be done before an initial release can be prepared.

**Comment by marctenax** [comment]
I'd rather keep this off Slack as it's an issue that should have discussed on GitHub

**Comment by nylen** [comment]
Yes - I've started building a web app that will track the status of each commit from WP and help us create PRs to merge them as needed.  The code so far is at https://github.com/ClassicPress/ClassicPress-Bots, not a whole lot to see yet though.

**Comment by Mte90** [comment]
There is no readme so is not clear what that bot project do :-)
