### ISSUE TITLE
Old CP logo used in install and admin bar

### ISSUE THREAD

**Issue by johnalarcon** [ClassicPress/ClassicPress#191]
The old (off-center feather) logo is used on the installation page and admin bar. The new (centered feather) logo should be added.

**Comment by senlin** [comment]
Hi @johnalarcon - thanks for noticing
Please have a look at what is lined up for merging: https://github.com/ClassicPress/ClassicPress/pull/189

**Comment by nylen** [comment]
FWIW, this probably should have been left open until the PR was merged.  I'm merging it now though.

**Comment by nylen** [comment]
Actually just kidding, this was a duplicate of #172 so it should have been closed as such.
