### ISSUE TITLE
Better wording on Media Settings admin page

### ISSUE THREAD

**Issue by johnalarcon** [ClassicPress/ClassicPress#193]
In Dashboard > Settings > Media, there is text that reads, "Organize my uploads into month- and year-based folders" I can live without a period at the end, but the trailing hyphen on the word 'month' makes it appear something is missing. Recommend updating to:

`Organize my uploads into month-based and year-based folders`

...or, preferably, something more succinct, like...

`Organize my uploads into date-based folders`

**Comment by senlin** [comment]
@johnalarcon 
Is there a reason you are completely ignoring the template for a new issue?
The template also describes the process for changes and we use this template to avoid getting all kinds of random issues being opened here on Github.

To suggest new features or major changes, please visit our Petitions website at:
https://petitions.classicpress.net/

For more details about our governance and change planning process, see:
https://www.classicpress.net/democracy/

Thanks for your understanding.

Closing this now.

**Comment by johnalarcon** [comment]
Yeah, sorry I was writing notepad and got overzealous...  Anway, to me, this is a bug, not a feature update. That's why I posted it here.

**Comment by senlin** [comment]
I think a bug is something that was introduced by ClassicPress, whereas the point you raise has to do with something that is already the case on a default WP install too. Therefore it needs a petition to alter its behaviour.

**Comment by nylen** [comment]
> Organize my uploads into month- and year-based folders

This is pretty standard English, and I prefer the current version to the other suggestions here.  It is precise, but not overly verbose.

- Compound words pre- and post-conjunction don't need to both be fully spelled out if their suffix is the same.
- https://english.stackexchange.com/questions/27707/post-hyphenation-of-split-compound-words
- https://en.wikipedia.org/wiki/Hyphen#Suspended_hyphens

---

@senlin this is always going to be somewhat debatable I think, but to me, wording changes from WordPress fall under "minor modifications to existing functionality or process" ([source](https://www.classicpress.net/democracy/#democracy-exceptions)) and therefore don't require a petition.

We should definitely remain open to minor suggestions for improvement, and we can discuss them individually, or redirect them to a petition if they turn out to be "too big".
