### ISSUE TITLE
Broken gravatar and reference to wapuu in example comment

### ISSUE THREAD

**Issue by johnalarcon** [ClassicPress/ClassicPress#194]
When doing a fresh install, a single test comment is added to the system by *A ClassicPress Commenter*. In WP, this example user's email address resolves to a valid Gravatar, but in CP it does not. If Gravatars will remain in CP, then the example should have an email that is attached to an actual working Gravatar account. Also, the term "wapuu" should be nixed – that's a WordPress thing.

## Expected behavior
Working avatar. No reference to wapuu.

## Current behavior
Broken avatar. Reference to wapuu.

## Possible solution
Fix avatar. Remove reference to wapuu.

## Steps to reproduce (for bugs)
Install CP.

**Comment by senlin** [comment]
@johnalarcon 
Thanks for reporting this, would it be possible to actually use the template we designed to report New Issues, instead of nixing everything in the template?

There is a reason we like everyone to follow the structure of the template as it becomes much easier to keep track of things.

Thanks for your understanding.

**Comment by johnalarcon** [comment]
Yes, I updated it to use the template before you commented.

**Comment by johnalarcon** [comment]
Can I get someone with email access to set up a Gravatar under a CP email address? Afterward, please post the address here and I'll write a PR. That's the only thing blocking this item.

**Comment by senlin** [comment]
@johnalarcon you can use the address social@classicpress.net which has the ClassicPress feather assigned to it in Gravatar.com
Thanks for doing the PR on this one!

**Comment by johnalarcon** [comment]
Thanks. Should be able to knock out 2 or 3 PRs on this end today.

**Comment by johnalarcon** [comment]
PR #200

**Comment by johnalarcon** [comment]
PR #200 merged; closing this.
