### ISSUE TITLE
Load wp-settings in wp-load vs at end of wp-config

### ISSUE THREAD

**Issue by mikeschinkel** [ClassicPress/ClassicPress#197]
This issue was split off from ClassicPress/ClassicPress-v1#192 and I am copying over and attributing the relevant comments thus far.

The idea is to make `/wp-config.php` just a file to contain configuration and not part of the a persistent part of the callstack for the entirety of a page load.

Doing this will make it easier and more reliable for tools like WP CLI to load a site's configuration without having to `eval()` a hacked version of `/wp-config.php`.  However, that is only one reason for this.

Given the currently architecture, it is hard to establish a configuration file or set of configuration files that can be committed to version control  that can be deployed reliably to different managed web hosts and without a build step. 

All of the major managed hosts have chosen to implement their own configuration which makes this even more difficult. Since WordPress as a project provided no guidance for what parts of the configuration needed to be defined by the user and which parts were available to be defined by the host.

Upon reflection I do not believe the simple change of moving the loading of `/wp-settings.php` from the end of `wp-config.php` to the end of `/wp-load.php` will break any sites or any tools. We can even wrap the loading of `/wp-settings.php` at the end of `/wp-load.php` with an `if (defined('WPINC'))` so that any ClassicPress site using a WordPress-style `/wp-config.php` that ends with a call to `/wp-settings.php` will still work correctly.

OTOH making this change will allow for innovation that has thus far been stifled by the current structure.

*NOTE:* This is more detailed than the original mention in ClassicPress/ClassicPress-v1#192 so neither  @Mte90 or @nylen whose responses I copied did not have the benefit of reading the full justification above.

**Comment by mikeschinkel** [comment]
**Comment by @Mte90 copied from [#185](/ClassicPress/ClassicPress/issues/185#issuecomment-433332522)**

Will be better to only have settings in `/wp-config.php` and not code _(and I am not sure if that change will break WP CLI.)_ 

Anyway right now we didn't planned anything because we are working on 1.0 that is a LTS version. I think that plus of ClassicPress is the compatibility with WordPress so remove that can create a problem but we will see after that release.

**Comment by mikeschinkel** [comment]
My comment in reply to @Mte90, copied from [#185](/ClassicPress/ClassicPress/issues/185#issuecomment-433496063) and edited:

> _"Will be better to have in wp-config only settings and not code"_

Not sure I agree with that, at least not in its entirety. There are a lot of scenarios where the configuration changes based on different logic in `/wp-config.php`, so even if `.env` files were used there would still be a need for a PHP file that could modify those configurations before they are baked into stone with `define()`s.

Also, what I am proposing is a trivial change that would require _(almost?)_ side effects and could provide _(at least my use-cases)_ immediately benefit. Later we could then architect a more _"perfect"_ solution. 

So I plead for us to not let the perfect be the enemy of the good.

> _"(and I am not sure if that change will break WP CLI)."_

Ironically, one of my reasons for wanting this is to empower tools like WP CLI to more easily load configurations and not have to just through so many hoops.  

And what I propose above where `/wp-load.php` only calls `/wp-settings.php` if it has not already been called would doing it the WordPress way and thus not break WP CLI. But even if the new way breaks WP CLI's current implementation we could easily test for `defined('WP_CLI')` and make it work as a special case.

**Comment by mikeschinkel** [comment]
**Comment by @nylen copied from [#185](/ClassicPress/ClassicPress/issues/185#issuecomment-433679659):**

> _"remove the call to require `/wp-settings.php` from `/wp-config.php` and instead call it at the end of `/wp-load.php`, thus allowing other PHP tools to load `/wp-config.php`"_

- What kinds of sites will this break?
- Is it possible to detect this breakage automatically?

For this specific change, I'm not sure, but I think this is an exercise we'll need to do for each potentially breaking change. What that looks like will of course depend on the breaking change and whether it's possible to check for breakage on a given site.

I also think we should look for other ways to achieve the same goal that are not breaking changes. For example:

> _"add an environment variable like `CLASSICPRESS_PARSE_CONFIG_ONLY` that causes `/wp-settings.php` to exit immediately, instead of continuing with the load process."_

I think this would achieve the same goal of _"allowing other PHP tools to load `/wp-config.php`"_, do you agree?

Another benefit of looking harder for non-breaking ways to achieve goals like this is that we can make changes like that prior to our `v1` final release.

Hope that helps, happy to discuss more if you have any questions.

**Comment by mikeschinkel** [comment]
**My reply, not from #185 but new to this issue:**

> _"What kinds of sites will this break?"_

As I have thought through this, I don't actually see it breaking any sites, not if we add the test that only loads `/wp-settings.php` from `/wp-load.php` if it has not already been loaded.

> _"Is it possible to detect this breakage automatically?"_

Given the above, I think this is moot. But if not, we could easily scan wp-config.php to see if it contains `'/wp-settings.php'`, but I don't think we would need to.

> _"add an environment variable like `CLASSICPRESS_PARSE_CONFIG_ONLY` that causes `/wp-settings.php` to exit immediately, instead of continuing with the load process."_

By testing for `WPINC`, I don't think we'd need to add any new variable and be able to achieve the same goal I think you had in mind.

> _"Another benefit of looking harder for non-breaking ways to achieve goals like this is that we can make changes like that prior to our `v1` final release."_

The nice this is this is such a trivial change to make and then such as trivial revert if it is needed that we could easily do it and see if it causes any problem anywhere as people test the final release of `1.0`.

**Comment by nylen** [comment]
Okay. This sounds pretty reasonable to me, the benefit is clear and I agree this shouldn't break anything with the extra check you suggested. If you are willing to write a PR I say we go for it.

**Comment by nylen** [comment]
Also, if we're going to do this, let's get it in before beta1 please so that we can get it in front of more people.

Tentative date for beta1 is in 3 weeks.

**Comment by nylen** [comment]
Hi @mikeschinkel, do you think you could help get a PR going for this change this week?  Otherwise getting this change into beta1 is going to be tight.

**Comment by mikeschinkel** [comment]
@nylen How about end of weekend? I am putting out client fires this week....

**Comment by nylen** [comment]
That may work, but my time is going to be pretty limited this weekend & next week.

We'll figure something out, I'd be happy to have the PR anyway and if this doesn't get into beta1 then it can go into beta2 or RC.

**Comment by dixonge** [comment]
where is wp-config.php at this time? Is it created on the fly?

**Comment by nylen** [comment]
Yes, there is a wp-config-sample.php which is used as a template.

**Comment by dixonge** [comment]
The one in master branch?

**Comment by nylen** [comment]
The latest source branch is `develop`, but yes.

**Comment by mikeschinkel** [comment]
@nylen See https://github.com/ClassicPress/ClassicPress/pull/238

**Comment by nylen** [comment]
We are out of time for beta1, milestoning this for beta2.
