### ISSUE TITLE
Setup API endpoints

### ISSUE THREAD

**Issue by scottybo** [ClassicPress/ClassicPress#2]
For ClassicPress core updates to work we will need to have valid API endpoints to query. I propose following the WordPress approach, ensuring we have the following endpoints in place on the (to be created) sub domain https://api.classicpress.net

https://api.wordpress.org/events/1.0/
https://api.wordpress.org/secret-key/1.1/salt/
https://api.wordpress.org/core/version-check/1.7/
https://api.wordpress.org/core/stable-check/1.0/

**Comment by Mte90** [comment]
I think that we have to define what api endpoint we want to replicate.
I think that from them we need only stable-check, the rest can use the official wordpress.

**Comment by scottybo** [comment]
@Mte90 I've emailed Matt Mullenweg to see if we're allowed to use the API endpoints, no reply yet... Any thoughts on this?

**Comment by scottybo** [comment]
Repo created, just going to some REALLY basic stuff just so we have our own endpoints to use

https://github.com/ClassicPress/ClassicPress-APIs

**Comment by scottybo** [comment]
API endpoints are:

https://api.classicpress.net/core/stable-check/1.0/
https://api.classicpress.net/core/version-check/1.0/
https://api.classicpress.net/events/1.0/
https://api.classicpress.net/secret-key/1.0/salt/

**Comment by scottybo** [comment]
Closing this issue as we now have a separate repository for this project.
