### ISSUE TITLE
Issue with official website

### ISSUE THREAD

**Issue by stefanos82** [ClassicPress/ClassicPress#20]
I have tried to view `https://www.classicpress.net/robots.txt` and got redirected to `https://www.thirty.site/site/www.classicpress.net/robots.txt/?website=true` which throws 

![image](https://user-images.githubusercontent.com/1777466/44945620-f5f70700-adf5-11e8-8279-033905479635.png)

**Comment by scottybo** [comment]
Something for me to fix!

**Comment by dsnid3r** [comment]
This issue is resolved with the new site.

**Comment by nylen** [comment]
We have a repo for the `*.classicpress.net` websites, which is a better place for this issue.

See:  https://github.com/ClassicPress/ClassicPress-Network/issues/6

Since this is tracked elsewhere, and the original issue is resolved, I'm closing this one.
