### ISSUE TITLE
ClassicPress theme by mojo Themes

### ISSUE THREAD

**Issue by stefanos82** [ClassicPress/ClassicPress#21]
What problems could this theme cause to ClassicPress, regarding its name?

http://www.mojo-themes.com/item/classicpress-responsive-magazine-wordpress-theme/

**Comment by stefanos82** [comment]
Since it's a project by the community for the community, it would be both cool and hilarious to name it ComPress.

**Comment by nylen** [comment]
@scottybo can confirm, but I think the name is set at this point.

**Comment by scottybo** [comment]
It is indeed! I've registered ClassicPress Limited as a company.

I'm not particularly concerned about the theme - as @nylen said, it's very old, has only had one version 
 released and doesn't seem to be widely used.

**Comment by nylen** [comment]
Closing, nothing to do here apart from having this documented.
