### ISSUE TITLE
Don't refer to the project as 'the WordPress fork'

### ISSUE THREAD

**Issue by danieltj27** [ClassicPress/ClassicPress#224]
I don't think ClassicPress should be branding itself as ***The WordPress Fork*** because it comes across as an official branch of WordPress or side project. Not only that, it comes across as being stood against WordPress with the old ClassicPress vs Gutenberg mantra.

Just my thoughts, but I don't think you really need to have it on the site and GitHub repo(s).

**Comment by ginsterbusch** [comment]
I wasn't aware that CP is anywhere explicitely called"The Wordpress Fork". I only know of: "ClassicPress is a hard fork of WordPress (...)" and "ClassicPress is a modified and enhanced version of WordPress that serves the business website market."

cu, w0lf.

**Comment by danieltj27** [comment]
![screenshot 2018-11-11 at 16 43 40](https://user-images.githubusercontent.com/8491069/48315660-fae3ee00-e5d0-11e8-9723-53fd12cd99c6.png)

**Comment by ginsterbusch** [comment]
Oh, in the "tag line". My bad, guess I always skimmed past it :)

cu, w0lf.

**Comment by nylen** [comment]
Thanks for the suggestion and the discussion. I've updated the repo tagline.

If there is anywhere else where we still say "the WordPress fork", please let us know here.  I don't see any more instances so I am closing this.

**Comment by scottybo** [comment]
Can't say I agree with this - we are the only serious fork of WordPress, and we are often referred to as "the fork" in articles, podcasts, tweets and so on.

**Comment by Mte90** [comment]
I think that also as LibreOffice started as OpenOffice fork I think that we can do that.
Also consider that until we not release the first version and maybe also in the future the project grow and also the discoverability of the project itself, will be not a problem to change.

**Comment by nylen** [comment]
Another reason I removed this is because we were only saying "the WordPress fork" in one single place.

If we are going to use this language, that's fine, but we need input, revision, and **help making the actual changes** so that we are using it consistently in multiple places (website, core software, GitHub, etc).

**Comment by danieltj27** [comment]
I don't speak on behalf of the WordPress project by any means. What I'm raising here though is that the wording and approach ClassicPress seems to be taking when using this wording is that it's *_the fork_*, as if it's some kind of WordPress backed project.

That's just my take on it and is merely a suggestion. 

@Mte90 

> I think that also as LibreOffice started as OpenOffice fork I think that we can do that.

I don't see what that has to do with this though. Absolutely, ClassicPress is a fork, and that's okay. But the wording I'm highlighting here makes it come across as if it's *_the one and only_* fork and some kind of official project.

But again to reiterate, this is just a suggestion for an opinion of mine, nothing more.

**Comment by nylen** [comment]
@danieltj27 I don't think a fork is ever going to be confused with an official project.

To me a better reason not to use this wording is that there are other WordPress forks out there, like calmPress.

I see now that "the WordPress fork" wording is also used at https://twitter.com/GetClassicPress.

**Comment by nylen** [comment]
Suggestion from Tim in Slack:

> I think it might simply be clearer to write "Forked from WordPress." The _from_ then helps to emphasize distance and also avoids use of "the". That should keep everyone happy.

+1 from me.

**Comment by scottybo** [comment]
I'm happy to go with this

**Comment by nylen** [comment]
I've updated the repo tagline here as well.

**Comment by Nodws** [comment]
Might want to change the name too as saying "I :heart:  WP" doest trigger any FBI alerts but  maybe ClassicPress 's initials will :P
