### ISSUE TITLE
Change links and wording from Slack to new support forums

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#232]
![2018-11-14t23 10 21-05 00](https://user-images.githubusercontent.com/227022/48529751-8de78700-e862-11e8-9d6c-4d916a9fdd27.png)

We need to update this dashboard widget to point people to https://forums.classicpress.net/c/support instead of Slack for support.

We'll keep Slack too, it's great for real-time discussions or questions, and we'll copy relevant conversations over to the forums or here on GitHub.

Follow-up to #163.

**Comment by dixonge** [comment]
It looks like we are referencing Slack in four different files:

- the repo README.md (needs changing, but not part of this milestone exactly)
- https://github.com/ClassicPress/ClassicPress/blob/f547f17513f15ebe4eb7f2f60bb298d17f7148a3/src/wp-admin/maint/repair.php
- https://github.com/ClassicPress/ClassicPress/blob/2f28f17991f1dbe3fc292d0ef50bf62336bdf52f/src/wp-admin/includes/dashboard.php
- https://github.com/ClassicPress/ClassicPress/blob/3febb8a51cd31cc8a60d96fc2d4012d7dbbeea84/src/wp-includes/update.php

I presume we want to change all those to point to the forums?

**Comment by ruiguerreiro79** [comment]
@dixonge you are right, we also need to change the context text of the link.
At the moment we have:

src/wp-admin/includes/dashboard.php
"For support, suggestions for improvement, or general discussion about ClassicPress, join our Slack group and send us a message in the #support or #testing channels."

src/wp-admin/maint/repair.php
"Some database problems could not be repaired. Please copy-and-paste the following list of errors into the #support channel in our Slack workspace for additional assistance."

src/wp-includes/update.php
"An unexpected error occurred. Something may be wrong with ClassicPress.net or this server&#8217;s configuration. If you continue to have problems, please join our Slack group and report this issue."

Any suggestions for the final text?

**Comment by nylen** [comment]
@ruiguerreiro79 here is the wording we used for the migration plugin:  https://github.com/ClassicPress/ClassicPress-Migration-Plugin/pull/38

**Comment by dixonge** [comment]
Suggestions:

src/wp-admin/includes/dashboard.php
"For support, suggestions for improvement, or general discussion about ClassicPress, join our Slack group and send us a message in the #support or #testing channels."

> Join our growing community:
> [Support](https://forums.classicpress.net/c/support)
> Feedback on [existing features](https://forums.classicpress.net/c/features)
> To suggest [new features](https://petitions.classicpress.net/)
> [General discussion](https://forums.classicpress.net/c/General)

src/wp-admin/maint/repair.php
"Some database problems could not be repaired. Please copy-and-paste the following list of errors into the #support channel in our Slack workspace for additional assistance."

> "Some database problems could not be repaired. Please copy-and-paste the following list of errors into the [support forum](https://forums.classicpress.net/c/support) for additional assistance.

src/wp-includes/update.php
"An unexpected error occurred. Something may be wrong with ClassicPress.net or this server’s configuration. If you continue to have problems, please join our Slack group and report this issue."

>"An unexpected error occurred. Something may be wrong with ClassicPress.net or this server’s configuration. If you continue to have problems, please join our Slack group and report this issue."

**Comment by nylen** [comment]
> Join our growing community: [...]

Sounds good to me, except I would also leave a link to the Slack group here.  Even though we're planning to offer support in the forums only, Slack is still the right place if you want to chat with someone in real-time.

**Comment by ruiguerreiro79** [comment]
@nylen @dixonge 
Here is what I have done, I included the Main community forum link instead the forum features one.
![image](https://user-images.githubusercontent.com/29898220/48629691-3d7f3f00-e9b2-11e8-92df-1dfd24a6c029.png)

Let me know if I need to change anything  before commiting.

**Comment by ruiguerreiro79** [comment]
I just created the PR #234
