### ISSUE TITLE
Fix unreliable HTTP tests

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#25]
Sometimes on Travis CI builds, we see something like this:

> ![2018-09-04t18 56 51-05 00](https://user-images.githubusercontent.com/227022/45063697-e802e980-b074-11e8-8620-c673b780ffba.png)

These failures occur occasionally when the PHPUnit tests access external resources via HTTP.  There are any number of things that can go wrong here, most of them not related to the code under test.

So, for any tests that need to do HTTP calls, it would be better to have them spin up a local HTTP server and run against that.  This will make the tests more reliable, a bit faster, and also eliminate the need for a few [API endpoints](https://github.com/ClassicPress/ClassicPress-APIs).

**Comment by nylen** [comment]
Some of the test code in question:

https://github.com/ClassicPress/ClassicPress/blob/94703a6809d583762d8e5b5e9c8a96126cc39594/tests/phpunit/tests/http/base.php#L13-L16

https://github.com/ClassicPress/ClassicPress/blob/94703a6809d583762d8e5b5e9c8a96126cc39594/tests/phpunit/tests/http/base.php#L73-L78

Here is the PHP code that runs behind that API endpoint:  https://github.com/ClassicPress/ClassicPress/blob/master/tests/phpunit/data/WPHTTP-testcase-redirection-script.php

It would be better to run this PHP code on the Travis CI virtual machine directly.  Then, the test URLs would look something like `http://localhost:8080/redirection.php`, and any potential issues with network connectivity are taken out of the equation.

**Comment by Mte90** [comment]
Or we can cache that files and avoid a webserver?

**Comment by nylen** [comment]
It needs to be a web server, because these tests are testing HTTP features like redirection.

**Comment by nylen** [comment]
This is still annoying, and consistently causes failed builds, milestoning for our first beta release.

**Comment by nylen** [comment]
Haven't gotten to this yet, and we haven't been seeing as many of these failures lately.

**Comment by Mte90** [comment]
I saw few patches in 5.0 about this kind of problems in tests.

**Comment by nylen** [comment]
A couple more tests to fix here:

https://github.com/ClassicPress/ClassicPress/blob/f765dbfa00cf74fd51cae45ffb13cd2536417e4b/tests/phpunit/tests/image/functions.php#L306-L325

https://github.com/ClassicPress/ClassicPress/blob/f765dbfa00cf74fd51cae45ffb13cd2536417e4b/tests/phpunit/tests/image/functions.php#L333-L341

In Slack, @joyously reported that the first of these two tests is failing:

```
There was 1 failure:
1) Tests_Image_Functions::test_wp_crop_image_url
Failed asserting that WP_Error Object (...) is not an instance of class "WP_Error".
ClassicPress/tests/phpunit/tests/image/functions.php:317
```

Further debugging revealed an error message about "the file is not an image" which suggests to me the image is not being downloaded from the remote URL successfully.

**Comment by mattyrob** [comment]
Is this still applicable? It relates to Travis CI and we are now using GutHub Actions.

**Comment by bahiirwa** [comment]
I think it is a good candidate for closing @nylen. Please close it if you agree.

**Comment by bahiirwa** [comment]
I think it is a good candidate for closing @nylen. Please close it if you agree.

**Comment by striebwj** [comment]
Let's close it until we get anymore reports of it

**Comment by nylen** [comment]
This is still a valid issue: tests shouldn't rely on external servers.
