### ISSUE TITLE
PHP 7.3 support

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#263]
We need to make some changes to get rid of some warnings/notices when running under PHP 7.3.

See:

- https://make.wordpress.org/core/2018/10/15/wordpress-and-php-7-3/
- https://core.trac.wordpress.org/query?keywords=~php73&col=id&col=summary&col=status&col=owner&col=type&col=priority&col=milestone&order=priority

**Comment by mattyrob** [comment]
I'm still getting to grips with GitHub but attached is a diff back ported some of the fixes from WordPress.

[263.txt](https://github.com/ClassicPress/ClassicPress/files/2660771/263.txt)

**Comment by HongPong** [comment]
Hi all,
I just wanted to chip in a bit of help here :)
@mattyrob  here is what I did to prepare this pull request:

1. Fork the ClassicPress repo to my own github account
2. Clone repo to local machine
3. Make a new branch. called php-73-fixes and switch to it . `git checkout -b php-73-fixes`
3. `git apply -v ` and drag n dropped your text file. Wverything applies cleanly. money!
4. `git add -A :/` to stage all changes
5. `git commit -m "the fixes #263 etc etc"
6. `git push origin php-73-fixes` . git comes back with a prompt from gitlab saying :
> remote: Create a pull request for 'php-73-fixes' on GitHub by visiting:
> remote:      https://github.com/HongPong/ClassicPress/pull/new/php-73-fixes
7. I go to that URL and fill in the info based on the issue template. by including #263 i get the right links to appear to/from this issue.

That's it!
All of that said I didn't test this, but the pull request will report back results from automated testings.

Hope this helps and I wish all classicpress people the best of luck!

**Comment by mattyrob** [comment]
@HongPong 

Cheers - I was all set to spend some time this evening forking and branching and you've saved me the effort! :)

**Comment by nylen** [comment]
Let's make sure that we port over whole *changesets* from WordPress, rather than whole tickets or partial commits at once.  This will make it easier to track our work and make sure that we have everything.

(I've been [working on a web application](https://forums.classicpress.net/t/backport-wp5-trac-tickets/110) to help with this task, but it will be a while before it's ready for use.  In the meantime we certainly welcome help porting changes over, as long as they are bugfixes or developer experience improvements with no backwards compatibility implications.)

Since https://github.com/WordPress/wordpress-develop exists, the easiest way to do this is using `git`.

Rough steps, using changeset 43832 ([trac](https://core.trac.wordpress.org/changeset/43832), [GitHub](https://github.com/WordPress/wordpress-develop/commit/894e8472389547757c2c0698cc6f2f6d4ac2015a)) as an example:

```
# add and fetch WordPress git history
git remote add wp https://github.com/WordPress/wordpress-develop
git fetch wp
# reset to latest ClassicPress code
git fetch origin
git checkout origin/develop -B develop
# start a new PR branch
git checkout -b merge/wp-r43832
git cherry-pick 894e8472
```

This magic number `894e8472` comes from looking through the lists at https://github.com/WordPress/wordpress-develop/commits/5.0 and https://github.com/WordPress/wordpress-develop/commits/master for a commit that happened at the same time as the commit on WP Trac, with the same message and the same internal ID (`git-svn-id: ...@43832`):

> git-svn-id: https://develop.svn.wordpress.org/branches/5.0@43832 602fd350-edb4-49c9-b593-d223f7449a82

There may be merge conflicts during the `cherry-pick` command, but in this case the changes I wanted were applied without me ever having to edit any code files.  This is great because this way I know I got exactly the changes I wanted.

So I followed the steps from @HongPong above, and the resulting PR is https://github.com/ClassicPress/ClassicPress/pull/274.  Note I left a record of what I did in the PR message.

**Comment by nylen** [comment]
For anyone working on porting WP changes back to ClassicPress, please record the following pieces of information for each commit:

- WP SVN changeset link
- `wordpress-develop` git commit hash

An example from #274:

> Merges https://core.trac.wordpress.org/changeset/43832 / WordPress/wordpress-develop@894e847 to ClassicPress.

**Comment by nylen** [comment]
This isn't going to make it into beta2.
