### ISSUE TITLE
WP version numbers in internal functions

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#27]
Several internal functions include WP version numbers in their arguments:

- [`_deprecated_function`, `_deprecated_argument`, etc](https://gist.github.com/nylen/78e3094129dee5556a620ff58d19e9ba)
- [`_doing_it_wrong`](https://gist.github.com/nylen/f1f0f4355b3c57e49ec6c79608a2fc7e)

(These searches **do not** include all such instances, because some of the calls span multiple lines of code.)

We need to decide what to do with these.  We probably want to change all of these version numbers from e.g. `2.0.0` to `WP-2.0.0`.  This is consistent with the approach taken in #26, but it is a bit more work (are there more functions to check? how can we make sure we catch all  such function calls?)

**Comment by marctenax** [comment]
Incorrect sintax @since WP-2.0.0

@since [version] [<description>]

http://docs.phpdoc.org/references/phpdoc/tags/since.html

**Comment by Mte90** [comment]
It is written to use semantic versioning system but is not mandatory http://docs.phpdoc.org/references/phpdoc/tags/version.html

**Comment by senlin** [comment]
And apart from that we will need a way to differentiate from code that was original WP and code that is original ClassicPress. Taking into account that on release it will be ClassicPress 1.0.0, then 2.0.0 will be around the corner. So if we don't find a good solution now, it will be a big mess later on.

On top of that @nylen clearly says:

> We need to decide what to do with these.

so no need to point out what may or may not be correct syntax, IMHO

**Comment by Mte90** [comment]
I think that if we add new methods/functions we can prefix them with `cp_`.
If we make changes compared to original stuff we can add in the comments of the methods/functions that (this will be part of the guidelines).

Any way I think that we can add the `WP-` prefix in comments to differentiate the code.

**Comment by senlin** [comment]
`deprecated_file` seems to be another string to search on

**Comment by Mte90** [comment]
Probably at next meeting will discuss about what to do for this ticket, so we can move forward

**Comment by senlin** [comment]
Why wait so long? What to do is already clear: add the `WP-`prefix, 
We now "only " need to describe it properly and think of a way to make sure we catch all such function calls.

**Comment by Mte90** [comment]
There is also the point about the prefix for methods/functions.
I think that also require a check of the code with phpcs and wordpress codestyle if breaks something.
Because if break something we need to fork and maintain also them

**Comment by Mte90** [comment]
You are right, I confused my own replies.
I think that we need a test for code sniffers and it's done.

**Comment by marctenax** [comment]
Done for me.

**Comment by senlin** [comment]
@marctenax curious what you mean by that?

**Comment by nylen** [comment]
I can take this one.  If someone wants to write a code sniffer, that's fine, but for now, the task is to prefix all instances of WP version numbers in `deprecated_*` and `_doing_it_wrong` functions with `WP-`.
