### ISSUE TITLE
Improve logic for theme stylesheet cache buster

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#285]
Whenever I write a plugin or theme that enqueues JavaScript or CSS, I always add a custom version to it so that I can bump the version and clear browser caches when the assets change.  For example:

https://github.com/ClassicPress/ClassicPress-Themes/blob/05ef142f6a677974e4ca4413df6aa0d88edaa93c/classicpress-susty-child/functions.php#L3-L26

The default `style.css` file for a theme is a different story.  Since the core software enqueues this file for me, I have to jump through some hoops to use my custom asset version there:

https://github.com/ClassicPress/ClassicPress-Themes/blob/05ef142f6a677974e4ca4413df6aa0d88edaa93c/classicpress-susty-child/functions.php#L52-L68

Filed under: Things that Really Grind My Gears ™️

At the very least there should be a filter to override this version.  Ideally: 

1. The theme's core stylesheet should use the version number from the theme's `style.css`
2. This should also be the default behavior for any other assets enqueued by a theme or plugin

I'm not sure if this would break anything, and (2) might prove difficult.

**Comment by Mte90** [comment]
The appending of the version is not already happening in wordpress for the theme files?

**Comment by nylen** [comment]
It is, but it's the _ClassicPress_ version that gets appended, which doesn't make sense to me.

**Comment by ginsterbusch** [comment]
maybe the scans are THAT lazy and just check for "*press" + version.

cu, w0lf.

**Comment by Mte90** [comment]
The idea of the version is useful because enable the browser to cache that resources but yes use the classicpress version for themes is not good.
I don't think that is a behaviour of wordpress maybe it is a bug that we created?

**Comment by senlin** [comment]
For the child themes I put together, I used the `filemtime( get_stylesheet_directory() . '/style.css' )`, would it not be possible to use that too?

**Comment by nylen** [comment]
Checking `filemtime` on every request isn't something we should ship out to everyone because it hurts performance for servers with slow filesystems. I didn't notice that was in the child themes but we should probably change it.

**Comment by nylen** [comment]
You are understanding the purpose of cache busting correctly, but we can think through the specific implementation more carefully, with the goal of avoiding unnecessary server-side operations on every request.

For JS and CSS enqueued by ClassicPress itself, we're using cache buster strings like `?ver=cp_abcdef`, and the `abcdef` portion changes with each ClassicPress release (using the [`classicpress_asset_version` function](https://github.com/ClassicPress/ClassicPress/blob/8797d5eaf7a06de6814fd91d2d6c25fd8ff27bdb/src/wp-includes/script-loader.php#L37-L70)).

WordPress uses `?ver=5.0.3` instead, but this achieves the same purpose:  ensure that JS/CSS files are fetched again with each new version of the core software.

Using the version of the core software (or the `cp_abcdef` string based on it) is probably also fine for our bundled themes, until we need to update them **without** doing a new ClassicPress release.  (We don't have to worry about this right now anyway, because releasing our own updates to a theme is only going to be possible once we have our plugin/theme directory up and running).

WordPress does release updates to their bundled themes outside of the updates to the core software, so the theme assets mostly use hard-coded version strings like `?ver=1.0` (seen in Twenty Seventeen) or `?ver=20160816` (seen in Twenty Sixteen).

These strings have a drawback too: you have to remember to update them when the source file changes.

Yet another option would be to use the version of the theme itself from the `style.css`, as proposed in the first comment in this issue.  I'm not sure what the code would look like to do this, or whether that could also hurt performance.

Still yet another option would be to ensure that whenever a CSS/JS file changes, it gets a new filename during the ClassicPress build process.  I think generally this is the ideal way to do cache busting.  Once that works, it's pretty much impossible to get a stale version of a file, but in ClassicPress it would be a major change and pretty difficult to make it all work correctly.

---

So, this comment got a bit long, but to summarize:  there are multiple ways to do this.  `filemtime` is easy, and it's probably fine in the majority of cases.  I'd use this on individual  sites as long as the hosting is good and seems to have a fast filesystem, but I think it's worth avoiding for software like ClassicPress that's intended to support a wide variety of hosts, since it has the potential to be slow.

Using a string based on the ClassicPress version is probably fine for now, like we do for CSS/JS files enqueued by the core software.  There are also a few other alternatives for the future like (1) using a hard-coded cache buster that we update whenever the source file changes, (2) using the theme version from the theme stylesheet, or (3) assigning files a unique name during the build process.

**Comment by senlin** [comment]
Fantastic, thanks for the extensive explanation! So we shall change it too in the child themes. Is it possible to also use the `classicpress_asset_version` function for those?

**Comment by nylen** [comment]
Yes, it should be fine to use the same function.

**Comment by pattonwebz** [comment]
This works fine for me and is how I have done it for a long time.
```
add_action(
	'wp_enqueue_scripts',
	function() {
		if ( ! is_admin() ) {
			$version_string = 'anyversionstringyouwant';
			/**
			 * This is the main theme stylesheet that is being enqueued where
			 * the themes name is actually `mythemename`.
			 */
			wp_enqueue_style( 'mythemename-style', get_stylesheet_uri(), array(), $version_string );
		}
	}
);
```

**Comment by bahiirwa** [comment]
> $version_string = 'anyversionstringyouwant';

`classicpress_asset_version()` function that provides a common code path for specifying and modifying script and stylesheet version numbers / cache busters 

There is a default CP buster. Check https://github.com/ClassicPress/ClassicPress/pull/297

**Comment by pattonwebz** [comment]
I seen that @bahiirawa, if that's what people want to use they can :)

**Comment by joyously** [comment]
I do this in my theme, (it loads both the parent and child style)
```
$theme = wp_get_theme();
$version = $theme->parent() ? $theme->parent()->get( 'Version' ) : $theme->get( 'Version' );
wp_enqueue_style( 'twenty8teen-style', get_template_directory_uri() .
	'/style.css', array(), $version );
if ( is_child_theme() ) {
	wp_enqueue_style( get_stylesheet() . '-style', get_stylesheet_uri(),
		array( 'twenty8teen-style' ), $theme->get( 'Version' ) );
}
```

**Comment by joyously** [comment]
> The default `style.css` file for a theme is a different story. Since the core software enqueues this file for me, I have to jump through some hoops to use my custom asset version there

Even if you are talking about the bundled theme/child theme, core shouldn't be enqueuing the file. Is this different for CP than WP?
_Is this a dead issue?_
