### ISSUE TITLE
Don't show "database upgrade" screen after migrating from WP 5.0

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#287]
When migrating from WP 5.0 to ClassicPress using the [migration plugin](https://github.com/ClassicPress/ClassicPress-Migration-Plugin), a database upgrade screen is shown.  This is because in WordPress 5.0.0, the `$wp_db_version` variable was changed from `38590` to `43764`.

However, surprisingly enough, there were no database changes with the introduction of Gutenberg in WP 5.0.0.  This change is instead used to deactivate the Gutenberg plugin when upgrading from WP 4.x to 5.x.

So, in the ClassicPress upgrade routine, we can ignore this particular pair of `$wp_db_version` values and avoid showing this screen.

See also:

- https://github.com/ClassicPress/ClassicPress-Migration-Plugin/issues/44
- https://github.com/WordPress/wordpress-develop/commit/583e4220ee2fb2f65419f48b5134c8fbd1aa3381

**Comment by mattyrob** [comment]
It looks like the ClassicPress migrate plugin calls the wp_version_check() function to start the migration process.

Looking at the documentation of that function there is a filter `'core_version_check_query_args'` that includes in the barrage a value for `initial_db_version`. Could we use that filter to pass the updated database version number?

**Comment by nylen** [comment]
@mattyrob You should be looking at the _end_ of the migration process instead, this is when this screen appears.

The database version is stored in up to 3 different places:  in the code in `wp-includes/version.php`, as the `db_version` option, and (for multisite installations only) in the `blog_versions` table.

Looking at this again, I'm not sure whether we should try to update the database silently for this specific pair of versions, or just ignore it every time we check for a database upgrade.  Here is one place where this check is done:

https://github.com/ClassicPress/ClassicPress/blob/8797d5eaf7a06de6814fd91d2d6c25fd8ff27bdb/src/wp-admin/upgrade.php#L73

https://github.com/ClassicPress/ClassicPress/blob/8797d5eaf7a06de6814fd91d2d6c25fd8ff27bdb/src/wp-admin/upgrade.php#L87-L103

Whatever we end up doing here, it needs to be tested and understood on both single-site and multisite installs.  The easiest way to do this is probably to use the [testing setup for the ClassicPress migration plugin](https://github.com/ClassicPress/ClassicPress-Migration-Plugin/tree/master/test#instructions).

Implementing an incomplete fix here would be worse than just leaving it as-is:  right now, it's just an unnecessary step rather than something that's broken, but a fix that is less than fully understood would run the risk of breaking something.

**Comment by mattyrob** [comment]
@nylen 

I've created a testing environment within my existing setup (using Home-brew on a Mac) and cannot get the database update screen to show (I presume that means this [screen](https://mainwp.com/wp-content/uploads/2015/09/dbupdaterequired.png))

Hopefully the gif below shows the process.

![classicpress-migration](https://user-images.githubusercontent.com/1280733/52175673-080f1400-279f-11e9-86a6-9669ede372b2.gif)

**Comment by nylen** [comment]
Interesting... here is what I see every time I migrate from WP 5.0 or higher:

![cp-migration-database-upgrade](https://user-images.githubusercontent.com/227022/52230808-53e8b880-2886-11e9-89e2-cbb2ec15e39b.gif)

I'm not sure why we see "Upgrading database..." and then the migration completes and shows a database upgrade screen.  This seems like a pretty :spaghetti: part of the WP code.

I'm going to remove this from the 1.0.0 milestone, as this is a "nice-to-have" and probably a lot more difficult than some of the things we really need to have in that release.

I'd still be happy to accept a PR for this, but it would need to include a pretty thorough explanation of what happens in the code with each of these values, and the approach taken to correctly update each one:

> The database version is stored in up to 3 different places: in the code in `wp-includes/version.php`, as the `db_version` option, and (for multisite installations only) in the `blog_versions` table.

**Comment by mattyrob** [comment]
@nylen 

I'll keep digging when I get time - my current set up fails in checking for plugin updates - see the error on reported in the original gif I posted. Not sure why that happens either.
