### ISSUE TITLE
Change logo on database update required screen

### ISSUE THREAD

**Issue by senlin** [ClassicPress/ClassicPress#29]
As per the title, the WordPress logo still needs to be replaced in the screen that informs a database update is required:

<img width="897" alt="database-update-required" src="https://user-images.githubusercontent.com/650066/45081451-2806b280-b0ef-11e8-9788-4151184ea303.png">

location: `src/wp-admin/css/install.css` L89

~~Question: can we just change it without a version number?~~

**Comment by nylen** [comment]
Summarizing Slack discussion about this issue...

The DB installation/upgrade page looks right to me.  As far as I can tell, this was due to the old logo being cached in your browser.  These logos were replaced in #18.

We updated the version string in #30, and that should take care of it.
