### ISSUE TITLE
Theme footers show "Proudly Powered by WordPress"

### ISSUE THREAD

**Issue by senlin** [ClassicPress/ClassicPress#291]
Since the migration to ClassicPress does not contain any file in the wp-content folder, the footer credits of the (default) themes remain pointing to WordPress.

As per [this forum discussion](https://forums.classicpress.net/t/proudly-powered-by/375/4) and @nylen 's comment:

> It’d be great to find an automatic and general solution for this issue, even if it’s just a solution that covers some or all of the Twenty * themes.

**Comment by nylen** [comment]
For the default themes that we bundle (currently Twenty Fifteen through Twenty Seventeen), this is also an issue.  They _start out_ saying "Powered by ClassicPress", but once a new version is released and the theme is updated, it will change back to "Powered by WordPress".

**Comment by senlin** [comment]
> For the default themes that we bundle (currently Twenty Fifteen through Twenty Seventeen)

Aren't those only bundled in the releases that people can install manually (for new sites mostly)? Those themes are not part of the package when a migration is done. 

Regarding updates of those default themes, it might be an idea to also include child themes that have a constant change to the footer (among other things if necessary).

**Comment by mattyrob** [comment]
The following is very hacky and untested for non-English sites, but so far it seems to work - needs more testing though before considering an PR.

```
function wp_to_cp( $translated_text, $text, $domain ) {
    if ( false !== strstr( $text, 'WordPress' ) ) {
    	$translated_text = str_replace( 'WordPress', 'ClassicPress', $translated_text );
    }
    if ( false !== strstr( $text, 'https://wordpress.org/' ) ) {
    	$translated_text = str_replace( 'https://wordpress.org/', 'https://classicpress.net/', $translated_text );
    }
    if ( false !== strstr( $text, 'Proudly powered by %s' ) ) {
    	$translated_text = str_replace( '%s', 'ClassicPress', $translated_text );
    }

    return $translated_text;
}

add_filter( 'gettext', 'wp_to_cp', 1, 3 );
```

**Comment by senlin** [comment]
On the [PR for child themes](https://github.com/ClassicPress/ClassicPress/pull/292#issuecomment-447605293) @nylen suggested:

> I think hiding the WP default themes from the dashboard (and keeping them up to date in our copy of their code) is probably an ok way to go. However, I'd like to discuss it first, because I'm sure there could be a better way to handle this.

I think we can indeed hide the default themes and then name the child themes of the PR ClassicPress TwentyFifteen, ClassicPress TwentySixteen and ClassicPress TwentySeventeen.

I am just not sure whether hiding the parent themes from the screen and keeping them updated is something that is going to be a workable solution in the long run. Of course long run is relative as most likely we will come with our own ClassicPress default theme at some point?

**Comment by nylen** [comment]
@mattyrob something like this looks like it will probably work well enough for most cases (as long as the theme uses translation functions to print the footer text).  It would be good to get some automated tests in place here.

The other thing we should do is only add this `gettext` hook after a footer-related action is fired, e.g. at the end of `wp_footer`.

The only other way I can think of to achieve the same thing is by output buffering.  Filtering `gettext` isn't exactly what I would call clean, ideal code, but I think it's less invasive than output buffering.

Thinking about where this code could live... I think the migration plugin could be a good candidate, because @senlin's PR will work for new installs.  Regardless of where it lives, though, we should probably make this an option that's disabled by default.

---

> I think we can indeed hide the default themes and then name the child themes of the PR ClassicPress TwentyFifteen, ClassicPress TwentySixteen and ClassicPress TwentySeventeen.

@senlin this sounds good to me.  Let's be sure not to hide the parent Twenty * theme if it happens to be active for whatever reason.

> Of course long run is relative as most likely we will come with our own ClassicPress default theme at some point?

Yes, but I think making child themes is an OK solution for now.

**Comment by GTMAN** [comment]
I tested this on 2019 2017 2016 2015 added the code to wp-includes/functions.php. Is this the appropriate file?

`add_filter('gettext', 'change_powered_by', 10, 3);

function change_powered_by( $translated_text, $untranslated_text, $domain ) {

    

    if ($untranslated_text === 'Proudly powered by %s.' || $untranslated_text === 'Proudly powered by %s') {
        return 'Powered by ClassicPress!';
    }

    return $translated_text;
}`

**Comment by GTMAN** [comment]
@mattyrob I tested the code and on 2017 & 2019 themes. Works on 2017 but on 2019 the text changes but not the url when running _ca version. I renamed wp-content/languages and then the URL changed as well. Ran the code from wp-includes/functions.php.

**Comment by mattyrob** [comment]
@GTMAN 

What is the _ca version? Is that a translated version? What link do you get instead?

**Comment by GTMAN** [comment]
Yes its Canadian  is the link https://en-ca.wordpress.org

I cannot access it though gettext  $text ... I think because it's translated already??
Tried with no joy
`if (preg_match("/^(?:.+)?wordpress\.org$/",$text ) ) {
     echo "match";
    $translated_text = preg_replace( '/^(?:.+)?wordpress\.org$/', 'https://classicpress.net/', $translated_text);`
Also tried your code with the different url
`if ( false !== strstr( $text, 'https://en-ca.wordpress.org/' ) ) {
    	$translated_text = str_replace( 'https://en-ca.wordpress.org/', 'https://classicpress.net/', $translated_text );
    }`

**Comment by mattyrob** [comment]
@GTMAN

I guess we need to know if there are going to be language sub-domains on classicpress.net. If not we can drop the ‘if’ check. It there are then a preg_replace() would be useful.

**Comment by nylen** [comment]
At the moment, we do not plan to have separate subdomains by language.

**Comment by GTMAN** [comment]
Looking at the .po files and see that only twentynineteen-en_CA.po (so far) has wordpress.org translated to en-ca-wordpress.org.  I edited the file and translated it to classicpress.net and of course it worked. Need a way to hook into the process after it is translated.  

I wonder how many Business clients would be running a default theme anyway ...  other than to check for conflicts ;)

**Comment by mattyrob** [comment]
@GTMAN 

If the plan is that there won't be ClassicPress language sub-domains, the following should cover the issue with WordPress translating to sub-domains:

```
function wp_to_cp( $translated_text, $text, $domain ) {
    if ( false !== strstr( $text, 'WordPress' ) ) {
    	$translated_text = str_replace( 'WordPress', 'ClassicPress', $translated_text );
    }
    if ( false !== strstr( $text, 'https://wordpress.org/' ) ) {
    	return 'http://sclassicpress.net';
    }
    if ( false !== strstr( $text, 'Proudly powered by %s' ) ) {
    	$translated_text = str_replace( '%s', 'ClassicPress', $translated_text );
    }

    return $translated_text;
}

add_filter( 'gettext', 'wp_to_cp', 1, 3 );
```

**Comment by GTMAN** [comment]
@mattyrob  That works perfectly whether I'm using English US or en_CA.

**Comment by mattyrob** [comment]
@nylen 

Do you want a PR submitting for my hacky fix for this issue or is it being addressed with child themes?

**Comment by GTMAN** [comment]
This kind of approach will cover a lot of other themes where Child themes won't. I've testing it on U-Design and X Theme with mixed results. Going to take the opportunity to contact the Authors and ask that they support ClassicPress by formatting their footers based on either following the default themes or checking if it's a ClassicPress install.

**Comment by GTMAN** [comment]
U-Design support is on the way using the if ( function_exists( 'classicpress_version' ) )
[https://themeforest.net/item/udesign-responsive-wordpress-theme/253220](url)

"I see. That should not be a problem, I'll look into it tomorrow, have to setup a localhost ClassicPress site for testing first.

Cheers!"

**Comment by mattyrob** [comment]
@nylen 

Agree, it's not easy is it but I suspect a plugin might be the best starting place for this. Let's give it some time to have a think and it might become clearer where this should sit (if anywhere).

**Comment by StonehengeCreations** [comment]
Hi everyone. 
New to ClassicPress, so bare with me :-)

Couldn't we simply use the capital_P_dangit() function in wp-includes/formatting.php, lines 5204 - 5233? That function makes sure that every "Wordpress" on a site is changed into "WordPress". You will still maintain the "Powered by" in every available locale.

**Comment by GTMAN** [comment]
Looks to me that function only acts on the_title or wp_title and not globally.

**Comment by senlin** [comment]
@StonehengeCreations 

> Isn't it an idea to include the WordPress naming in this?

Hmmm, I don't think that will work. Suppose someone is writing an article about WordPress. That would then automatically be swapped out for ClassicPress?

Also, this has very little to do with the original issue, which is: 
Theme footers show "Proudly Powered by WordPress"

**Comment by nylen** [comment]
> But I noticed that this change is now only from "Classicpress" to ClassicPress". Why?

This function runs via a filter on post titles and `post_content`, not on the entire page.  The intent of the filter is to make sure the name of the software is written with the correct capitalization in user-generated content.

**Comment by ginsterbusch** [comment]
Ie. our "capital p dangit!" :D

https://codex.wordpress.org/Function_Reference/capital_P_dangit

cu, w0lf.

**Comment by bahiirwa** [comment]
Since this is resolved in https://github.com/ClassicPress/ClassicPress/pull/370. Can we close this?
