### ISSUE TITLE
Rename WordPress to ClassicPress

### ISSUE THREAD

**Issue by scottybo** [ClassicPress/ClassicPress#3]
We need to rename WordPress to ClassicPress in all "public" areas (this includes the admin area).

However, we will not (at this stage anyway):

Change any variable names UNLESS they contain the word WordPress
Change any class or function names UNLESS they contain the word WordPress

**Comment by scottybo** [comment]
I'd keep the `wp_` prefix in place so we remain compatible with plugins. This is mostly a comment update.

**Comment by warrior79** [comment]
Let's do this in 2 parts by diving the folders.

Part 1 -  tests, tools, src/wp-includes
Part 2 - src/wp-admin  , src/wp-content

**Comment by senlin** [comment]
I have taken Part 2 - src/ (root files), src/wp-admin , src/wp-content (which doesn't contain anything)

**Comment by senlin** [comment]
@warrior79 I have changed one file in `tests/phpunit/tests/general/document-title.php` on L90, 95, 121. The reason for that is that the TravisCI test was failing when I tried to do the PR, so before you start with your set of files, please make sure you have the latest ClassicPress:master.

**Comment by nylen** [comment]
I think we can call this done, thanks @senlin and @warrior79 for your help with this huge task. There may be a few things to clean up still, but let's track that in #35.
