### ISSUE TITLE
Integrate patch from 5.0.2

### ISSUE THREAD

**Issue by Mte90** [ClassicPress/ClassicPress#301]
Right now the 5.0.2 is on TC phase but there are few bugfix that are interesting for us to include and that doesn't involve gutenberg:

- https://core.trac.wordpress.org/ticket/45483
- https://core.trac.wordpress.org/ticket/45711

**Comment by senlin** [comment]
Maybe split them up into separate issues?

**Comment by Mte90** [comment]
Yes we can use this ticket as meta to track all of them and discuss the tickets that require that.

**Comment by nylen** [comment]
Here is how to port changes from WP over in a way that is easy to manage and easy for us to track later:  https://forums.classicpress.net/t/backport-wp5-trac-tickets/110/6

**Comment by Mte90** [comment]
First pr https://github.com/ClassicPress/ClassicPress/pull/332

**Comment by Mte90** [comment]
second one https://github.com/ClassicPress/ClassicPress/pull/333

**Comment by Mte90** [comment]
merged yesterday
