### ISSUE TITLE
The term ClassicPress is highlighted as an error in the editor

### ISSUE THREAD

**Issue by johnalarcon** [ClassicPress/ClassicPress#317]
The term **ClassicPress** should be added to the spellcheck dictionary used by the core editor.

![image](https://user-images.githubusercontent.com/12477319/50446654-f9ddf600-08ca-11e9-84e2-8cb681661e1e.png)

## Possible solution
It's not clear how to whitelist a single word, but that seems to be the solution.

## Steps to reproduce (for bugs)
1. Create new post.
2. Type ClassicPress into the editor.
3. Note the squiggly red underline.

**Comment by GTMAN** [comment]
That is coming from my Chrome Browser. If you switch to text view and right click on ClassicPress it gives the option to add to dictionary. I assume other browser work the same.
![image](https://user-images.githubusercontent.com/7461274/50452551-9ffc2100-0908-11e9-91ea-955a3120115e.png)

**Comment by johnalarcon** [comment]
Thanks for the tip. This worked in Chrome, but not Firefox. I found a tutorial online for adding a word to the Firefox dictionary, but it didn't work. I can deal. Since this is a browser feature and not a ClassicPress issue, I'm closing this.
