### ISSUE TITLE
Integrate patch from 5.0.3

### ISSUE THREAD

**Issue by Mte90** [ClassicPress/ClassicPress#328]
Like for #301 it is time to schedule form 5.0.3 what we need https://wordpress.org/news/2019/01/wordpress-5-0-3-maintenance-release/

Looking at the code we need:

- https://core.trac.wordpress.org/ticket/44770
- https://core.trac.wordpress.org/ticket/44809
- https://core.trac.wordpress.org/ticket/45615

**Comment by GTMAN** [comment]
Is this automated or do you need manual edits done?

**Comment by nylen** [comment]
We are getting close to the v1.0.0 release, so for now we need to keep things simple and take only the changesets that are part of the WP 4.9 branch.  For example:  https://core.trac.wordpress.org/changeset/44443

Please port these changes using one PR for one WP commit, unless multiple commits are clearly related to accomplishing the same task.  Please also be sure to include the original changeset number (not the Trac ticket number), the original commit hash from https://github.com/WordPress/wordpress-develop, and an explanation of the changes like for any other PR.

Usually no manual edits are needed (`git` will do the work for you unless there are conflicts), but we do need to make sure we can track what we've ported later.

Here's a guide to follow to make sure that everything is in place for that:  https://forums.classicpress.net/t/backport-wp5-trac-tickets/110/6

Later on, we'll need to have an effort to look through all recent changes from WP and port the ones we want.  This will probably happen in a release like ClassicPress 1.1.0 or 1.2.0, as long as there are no backwards-incompatible changes.

**Comment by Mte90** [comment]
My idea was to do a tool this week that based on the changeset, follow your guide and do the branch with the commit.
As I saw now there are always to fix manually conflicts with 5.* .
Anyway looking at the patch also for #301 there are tickets with a very low amount of line changed.

**Comment by Mte90** [comment]
How to contribute with this ticket:

- Check our backport script that will do everything for you https://github.com/ClassicPress/ClassicPress/blob/develop/bin/backport-wp-commit.sh
- Take the changeset number of the 3 tickets above
- The script for every changeset will generate a branch in your fork and you have to do a pull request of everyone

**Comment by PaoloFalomo** [comment]
@Mte90 here is the status:

| Ticket                                                | Changeset                                                | Pull Request                                          |
|-------------------------------------------------------|----------------------------------------------------------|-------------------------------------------------------|
| [44770](https://core.trac.wordpress.org/ticket/44770) | [43561](https://core.trac.wordpress.org/changeset/)      | https://github.com/ClassicPress/ClassicPress/pull/352 |
| [44809](https://core.trac.wordpress.org/ticket/44809) | [43578](https://core.trac.wordpress.org/changeset/43578) |                     incoming...                                  |
| [45615](https://core.trac.wordpress.org/ticket/45615) | [44443](https://core.trac.wordpress.org/changeset/44443) |             incoming...                                          |

**Comment by PaoloFalomo** [comment]
@Mte90 all changesets from submitted tickets merged in respective PRs

**Comment by PaoloFalomo** [comment]
@Mte90 edited ticket 44809 integration since it's wrong. I'll make a new PR asap. 
Thank you for your help.

**Comment by Mte90** [comment]
ping @PaoloFalomo

**Comment by nylen** [comment]
Let's close this ticket, I think there is nothing left to do here? It would be good to confirm that using http://bots.classicpress.local:8003/branches/wp-5.0, it should show all 3 of the tickets here and whether or not we have already merged them.
