### ISSUE TITLE
Integrate WordPress changes from 5.1

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#358]
From @spacedmonkey on Twitter: https://gist.github.com/spacedmonkey/89dc01a3e043a9e39aff9a27ded6bac1

It's helpful to have this list of tickets, but what we really need in order to do a good job of keeping up with WP is people to test & explain changes.  Ideally we need to have at least 1 or 2 people contributing to ClassicPress who understand the changes well enough to answer questions about them.

Also, changes that have automated tests are often easier to review.

More info about our technical process for porting WP changes: https://forums.classicpress.net/t/backport-wp5-trac-tickets/110/8

**Comment by wpplugindevcom** [comment]
I was thinking about this myself..I should join classicpress

**Comment by Mte90** [comment]
we have still #350 and #328 to move on before or we will have issues with code missing.

**Comment by nylen** [comment]
@Mte90 rather than making huge lists of changesets/tickets, it would be better to focus on one single theme or feature at a time, and make sure it's something we know that we want to do.

For example, it would be helpful to collect all the changes related to the "minimum PHP version" notice that will be shipping in WordPress soon, because we know we want to do something similar.  @invisnet will probably have some thoughts on the implementation, but it would be good to create a separate issue for this and start looking for related WP commits.

Don't forget we still need testing instructions and explanations for any changes we make.  Generally, "because WP did it" isn't a good enough reason to backport something.

**Comment by nylen** [comment]
Let's close this issue and start to address these changes individually.

We also need to focus first on the things we know we want, like #438 for example.  Otherwise we waste a lot of time on this.

See also #428 where we are working on some better guidelines for backporting..

**Comment by spacedmonkey** [comment]
Sorry, was the end result of this that you close the ticket with no action.
Really? That is a not a nice way to treat a new contributor. :(

**Comment by nylen** [comment]
@spacedmonkey there are multiple, earlier comments on this ticket explaining why it was not actionable as written and thus has been closed.

I'm also not sure what would have happened with the email response I sent you individually, explaining that we are happy to have contributors with WP expertise, but we need people who can help us plan and land specific changes instead of sending a list of WP tickets with no context.

As far as I know, no one at ClassicPress has received a response from you other than the following today:

> Really? That is a not a nice way to treat a new contributor. :(

In any case, we've now made a lot more information public in our contribution guidelines as well:

- https://github.com/ClassicPress/ClassicPress/blob/develop/.github/CONTRIBUTING.md#review-criteria
- https://github.com/ClassicPress/ClassicPress/blob/develop/.github/CONTRIBUTING.md#backporting-changes-from-wordpress

Please take a look and let us know if there is any more information we can include there that would be beneficial to you and other new contributors.
