### ISSUE TITLE
Replace API endpoint for core checksum

### ISSUE THREAD

**Issue by Mte90** [ClassicPress/ClassicPress#376]
## Expected behavior
Use CP endpoint to verify the checksum

## Current behavior
On https://github.com/ClassicPress/ClassicPress/blob/develop/src/wp-admin/includes/update.php#L101 it is using for the core the WP endpoint

This can create issues in the future.

**Comment by nylen** [comment]
This isn't going to cause us any problems any time soon - according to the code, checksums weren't added until WP version 3.7.

This code is used in the core update procedure, and currently it does what we want in each case (confirms that a given file needs to be copied):

https://github.com/ClassicPress/ClassicPress/blob/7090ac28407582d60b11d5bdd1cb12150a443484/src/wp-admin/includes/class-core-upgrader.php#L626-L629

https://github.com/ClassicPress/ClassicPress/blob/7090ac28407582d60b11d5bdd1cb12150a443484/src/wp-admin/includes/class-core-upgrader.php#L147-L148

https://github.com/ClassicPress/ClassicPress/blob/7090ac28407582d60b11d5bdd1cb12150a443484/src/wp-admin/includes/update-core.php#L278-L283

@invisnet started on some code for our version of this API, we'll need to put that in place and then we can update the `get_core_checksums` function.

This is a valid issue, but it's more "something we haven't done yet" than a bug so I'm removing the "bug" label.

**Comment by xxsimoxx** [comment]
Closing this issue as discussed at core meeting.
