### ISSUE TITLE
Implement ClassicPress core update functionality and API endpoints

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#38]
This is a high-level issue outlining what needs to be done to make ClassicPress core updates work.

Under https://github.com/ClassicPress/ClassicPress-APIs there are basic endpoints https://api.classicpress.net/core/stable-check/1.0/ and https://api.classicpress.net/core/version-check/1.0/.

These need to be made dynamic and pull information from GitHub about Releases zip files (with caching on the server), which we will use for update hosting initially.

We need someone to record and analyze the responses that come back from the WP core update endpoints for various WP configurations:

- English and non-English
- Latest version on a branch (4.8.x, 4.9.x)
- Older version on a branch with an update available (4.8.x, 4.9.x)

We need to create a procedure for building release zip files, based on the way WordPress already does this.  `grunt build` is a starting point, but how a zip file actually gets built needs more research.

We need to update the ClassicPress code and the update routines to use these endpoints.

Finally we need to test the update routines as exhaustively as possible, probably by releasing a couple of alpha versions on GitHub.

**Comment by ginsterbusch** [comment]
Well, I am working on it (via the ClassicPress Migration Plugin) ;)

**Comment by nylen** [comment]
This issue is too large and vague to be actionable, so I'm closing it.  I think I've covered all of the todo items in new issues, but please let me know if I've missed something.

I've split what's still left to be done here on the API side into https://github.com/ClassicPress/ClassicPress-APIs/issues/5.

> We need to create a procedure for building release zip files, based on the way WordPress already does this. `grunt build` is a starting point, but how a zip file actually gets built needs more research.

We're going to use `grunt build`, commit the results to a separate branch on GitHub, and let GitHub handle serving our release zip files.

> Finally we need to test the update routines as exhaustively as possible, probably by releasing a couple of alpha versions on GitHub.

We've already started on this, with a super-preliminary `alpha0` release.  We have a milestone for the rest of the tasks for the `alpha1` release: https://github.com/ClassicPress/ClassicPress/milestone/2

This milestone includes https://github.com/ClassicPress/ClassicPress/issues/136 which is necessary to get ClassicPress to unpack and install its own release builds successfully.
