### ISSUE TITLE
Change temporary string in About pages

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#41]
After the changes in #32, the About pages in the admin section say this:

> Thank you for trying ClassicPress! We are under heavy development while we prepare for an initial release

This string is fine for now, but we should change it to something more permanent, ideally **before** we set up translation infrastructure.

**Comment by senlin** [comment]
Before we can implement this, we need to decide about the exact text.

**Comment by nylen** [comment]
Removed the "critical" label because this can wait (other things like consistent version number handling and working updates are more important).

**Comment by nylen** [comment]
I think the time to do this is after our alpha releases and before our first beta releases.  Suggestions welcome for wording, but it could look something like this:

> Thank you for trying ClassicPress!  Please let us know ([link to website/github/slack]) if you find any issues with our [first/second/etc] beta release.

**Comment by freesouldesign** [comment]
I think people who want to report bugs do it in any case and who install ClassicPress at the moment know it can have bugs. I would avoid to focus on bugs, to don't associate ClassicPress with bugs. There are other places where you can speak about bugs. I would focus on the main goals and values of ClassicPress and write something like:

> Thank you for using ClassicPress, the business focused CMS system. 
> Powerful. Versatile. Predictable.

**Comment by nylen** [comment]
Done:

> Thank you for using ClassicPress, the business focused CMS.
> Powerful. Versatile. Predictable.

The "we are under heavy development" text was fine for an alpha release, but we're moving quickly towards production-ready code and language.
