### ISSUE TITLE
Build is failing (emoji-related)

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#413]
`src/wp-includes/formatting.php` is being modified during the build process, which (unlike in WordPress) causes the build to fail.

See:

- https://github.com/ClassicPress/ClassicPress/blob/ecfea534/Gruntfile.js#L718-L789
- https://core.trac.wordpress.org/changeset/45134

**Comment by nylen** [comment]
In order to fix this, I would like for us to make a PR where we backport all emoji-related changes from WP to CP.  (We'll be moving emoji support out into a core plugin in v2, but for now, we might as well keep it up to date.)

When we get to the end of this PR, we'll need to host the Twemoji v12 files also at twemoji.classicpress.net.  Then, we might also want to fix this `svn ls https://github.com/...` command in the Gruntfile to do something more exact.

You can find the emoji-related WP changesets here (Ctrl+F for `emoji`):

- https://bots.classicpress.net/branches/wp-5.0
- https://bots.classicpress.net/branches/wp-5.1
- https://bots.classicpress.net/branches/wp-trunk

cc @Mte90 in case you are interested in helping or coordinating this change.

**Comment by Mte90** [comment]
Found the changeset https://core.trac.wordpress.org/changeset/45134

**Comment by nylen** [comment]
@Mte90 I linked to this changeset in the original post, but I'd like to see a PR that prepares **all** of the changesets related to emoji, so that we are up to date with WP in this component.

**Comment by Mte90** [comment]
Sorry I missed it but in the previous message there was written to search on different pages, so I looked there and I found only that changeset.

**Comment by nylen** [comment]
>I would like for us to make a PR where we backport all emoji-related changes from WP to CP
