### ISSUE TITLE
Add full changelog display to admin dashboard

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#422]
The ClassicPress admin dashboard should show the same changelogs as our official release posts in the forums: https://forums.classicpress.net/c/announcements/release-notes

Right now these changelogs appear in 2 different places (on the forums and on GitHub).  To avoid having 3 places, it might be nice to come up with a way to automatically pull the content from a single source (most likely GitHub).

Or, we could take the simplest route and just add a link from the admin dashboard to the releases subforum.

**Comment by bahiirwa** [comment]
> it might be nice to come up with a way to automatically pull the content from a single source (most likely GitHub).
> 
> Or, we could take the simplest route and just add a link from the admin dashboard to the releases subforum.

Yes and Yes, This should be workeable. I have used a sample repo on my github space and tapped into the Github release api -  https://api.github.com/repos/bahiirwa/years-since-repo/releases/latest

Inset are the results. It is possible to actually pull this in and only go for the body to get the release notes. 

Question is what if? I am so lazy to click the link button?

![Screen Shot 2019-06-18 at 08 44 55](https://user-images.githubusercontent.com/7713923/59656189-76c89900-91a5-11e9-8210-a65f7ad89f1c.png)
![Screen Shot 2019-06-18 at 08 45 05](https://user-images.githubusercontent.com/7713923/59656191-76c89900-91a5-11e9-8d6d-ac21509ab212.png)

**Comment by nylen** [comment]
I didn't think of pulling this data from the GitHub API.  Let's do it, I think that will work really nicely.  The release entries for 1.0.0 and 1.0.1 already have all the data and links we'll want to include there, and we can keep this going for future versions:

https://github.com/ClassicPress/ClassicPress-release/releases

Two issues that come to mind right now:

- GitHub will return this content in Markdown, and we probably don't want to include a full Markdown parser in ClassicPress just for this.
- Servers with large numbers of ClassicPress sites may hit GitHub's API rate limit and experience errors (since the requests for all of these sites will come from the same IP).

I think the solution to both of these problems is to add a "proxy" API endpoint to api-v1.classicpress.net, as we've done for the [petitions widget](https://github.com/ClassicPress/ClassicPress-APIs/blob/master/v1/features/1.0/index.php).  (While we're at it, we should probably add some caching to that endpoint too.)

**Comment by pattonwebz** [comment]
Is there any reason why it couldn't just be a local file?

I don't like the idea of making frequent external requests for arbitrary data just for a changlog that is unlikely to be super useful to users (I can see it be useful one time only).

**Comment by nylen** [comment]
Requests would not be frequent, we could store the result in a very long transient (1 month for example).

2 reasons for this:

- One more place where we need to enter this data for each release, there are already 2. Using an API endpoint would allow this part of the release process to be fully automated instead.
- If we need to update the changelog entries later to make something more clear, we'd be able to do this without requiring a new release. Admittedly not as compelling of an argument as the first point, my main interest here is in avoiding extra steps with each release.

**Comment by nylen** [comment]
Postponing this issue until later, since there is still a lot to do in order to make it work.

>Or, we could take the simplest route and just add a link from the admin dashboard to the releases subforum.

Let's go with this for v1.1.0 &rarr; #449

Another difficulty to consider with the full changelog approach described here is translations.  We would probably be providing the changelogs in English only, which is not ideal.

**Comment by KTS915** [comment]
Like @pattonwebz, I don't see any need for this. Those who want this info will get it from the announcements on the website and in the forum.
