### ISSUE TITLE
Add security page

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#435]
Previously: #368, merged into the `feature/security-page` branch for further development.

Planned work here includes splitting the screen's text into "Users" and "Developers" section and providing examples of how to use the new screen in a couple of small plugins, assigning @invisnet to coordinate this.

**Comment by nylen** [comment]
@invisnet do you have an update on this? We need to see good progress soon in order for this to make it into 1.1.0.

**Comment by szepeviktor** [comment]
I run WordPress site as a full-time job.

We could think about a **high security switch** which enforces some of these https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/WordPress-security.md#application

My biggest concern for WordPress is it lacks protection. I am developing a protection based on actual events (not blog posts)

- https://github.com/szepeviktor/waf4wordpress/tree/master/http-analyzer
- https://github.com/szepeviktor/waf4wordpress/tree/master/core-events

You may consider including some of these draconian measures in CP.

**Comment by nylen** [comment]
@szepeviktor I suggest starting a forum thread for these ideas, this issue is specifically to coordinate the addition of a new security page to ClassicPress core.

The standard way of including most of these "draconian measures" is at the server level. This may be a better idea because they are advanced features that require advanced understanding of the systems in use, and these features can cause people to be locked out of their site and other issues if they break.

**Comment by szepeviktor** [comment]
> The standard way of including most of these "draconian measures" is at the server level.

I agree as far as the HTTP analyzer. The core events part of my WAF is actually really ClassicPress-specific.

BTW a firewall can operate without IP banning, simply refusing a request with HTTP/403.

**Comment by nylen** [comment]
Security page added in #484.
