### ISSUE TITLE
Add PHP upgrade notice

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#438]
We need to add a PHP version update notice to ClassicPress.

In much the same style as WordPress, we want to encourage people to update so that we can bump the major version higher for future versions of PHP.

Previously, from https://petitions.classicpress.net/posts/6/minimum-php-version-should-be-7-x:

> - ***(Done)*** All ClassicPress 1.x versions will support PHP 5.6 and greater.
> - We'll bump the minimum PHP version with each major version of ClassicPress, and use a PHP version check to make sure the site is compatible with the new version. If the version check doesn't pass, then we'll block the upgrade (similar to how the migration plugin works today).
> - When we get closer to version 2 release, we'll take a look at the distribution of PHP versions on ClassicPress 1.x sites.
> - **In a ClassicPress 1.x release, we'll include a prompt to upgrade older PHP versions. This should help move the needle further and push more people to upgrade.**
> - We'll use the results from the active installation numbers, as well as the PHP support timeline, to decide on a minimum PHP version for ClassicPress v2.x.

This issue is to address the fourth bullet point in bold, and this notice should be released in a future 1.x version of ClassicPress.

The easiest starting point for this notice will be to backport what WP has done into a PR.

Brief backport instructions are to look at https://bots.classicpress.net/branches/wp-4.9 https://bots.classicpress.net/branches/wp-5.0 https://bots.classicpress.net/branches/wp-5.1 https://bots.classicpress.net/branches/wp-trunk and soon https://bots.classicpress.net/branches/wp-5.2, and find changesets related to the PHP version notice.  Then port them in order (oldest first) by running `bin/backport-wp-commit.sh -c WP_CHANGESET_NUMBER` for each changeset, and submit the results as a PR.

**Comment by nylen** [comment]
WP commit that introduced this feature: https://core.trac.wordpress.org/changeset/42832

There are several more commits that should be evaluated at the same time. Preparing a list of all commits that have to do with WP's PHP upgrade notice would be a good next step for this issue.

**Comment by bahiirwa** [comment]
Github has closed this and I cannot re-open or continue with this. Seems the issue stems from when this PR was referenced prior to merge of PR 428.

<img width="1019" alt="Screenshot 2020-09-13 at 07 59 08" src="https://user-images.githubusercontent.com/7713923/93010648-7d57e300-f597-11ea-801c-512fa5f8268b.png">

I can only comment for now as seen below in screenshot.

<img width="1048" alt="Screenshot 2020-09-13 at 07 59 20" src="https://user-images.githubusercontent.com/7713923/93010650-82b52d80-f597-11ea-9183-88c971b69c5b.png">

Unless there is a way to reopen this PR,  I am drafting/opening PR 624.

I am not using the links to the numbered PRs to avoid any unexpected issues.

**Comment by bahiirwa** [comment]
Basing on this schedule https://www.php.net/eol.php, we need to probably shoot for 7.4 movement of users to ensure we are not supporting really old versions. 

7.4.x Itself is soon going out of the cycle.

**Comment by viktorix** [comment]
We deprecated PHP 5.6 in 1.6.0, so v2.0 will only support 7.4+
