### ISSUE TITLE
Needless Google+ input on profile editing page?

### ISSUE THREAD

**Issue by johnalarcon** [ClassicPress/ClassicPress#439]
Google+ was closed to the public in April 2019. The input for G+ handle is still in the profile editing page.

## Expected behavior
There is no unexpected behavior.

## Current behavior
The profile editing page has a contact input for Google+.

## Possible solution
Remove the input if it's no longer relevant.

## Context
Having this input (if it's no longer needed) doesn't say "looking to the future". I say "if" because Google says the following. It's not clear (to me) if it is actually needed or not.

> Google+ is only available for G Suite accounts through work or school. Consumer accounts (typically ending in @gmail.com) were shut down on April 2nd, 2019. [Source](https://support.google.com/plus/?hl=en#topic=9259565)

**Comment by Remzi1993** [comment]
@johnalarcon you're right. Google+ should be completely removed everywhere since it's closed some time ago.

**Comment by nylen** [comment]
+1 for removing this.

**Comment by johnalarcon** [comment]
After looking further into this, I find that it's not core that added the G+ input on the profile page. It was an install of Yoast that I didn't realize had been activated. Confirming that `email` and `website` are the only fields added by core. This is a moot issue.

**Comment by nylen** [comment]
Ok, thanks for the update. Closing this then.
