### ISSUE TITLE
Better process for listing/building Twemoji

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#447]
Follow-up to #445 and #446.

https://github.com/ClassicPress/ClassicPress/blob/15ff352490f4000f382564fba17af41237842283/Gruntfile.js#L731-L735

Using `svn ls` to list a directory on GitHub is really weird.  I cannot find this documented anywhere and it only works with certain GitHub URLs.

We need a better way to do this, probably a script that takes a specific version of Twemoji, checks it out using `git`, and saves the list of files.

**Comment by nylen** [comment]
> probably a script that takes a specific version of Twemoji, checks it out using `git`, and saves the list of files

Actually this wouldn't work very well either because the Twemoji download is very large - even a shallow clone or https://github.com/twitter/twemoji/archive/v12.1.2.zip is around 320 MB.

We may need to maintain a git clone of this repository on a ClassicPress.net server and provide a list of files from there.

**Comment by Mte90** [comment]
Probably svn is handy because you don't need to download the entire repo, after all we need only the svg files and I don't think that they are so heavy.
As you suggest maybe we can do a script that is a packer of twemoji for our needs to run only when we need for a major.

**Comment by nylen** [comment]
> Probably svn is handy because you don't need to download the entire repo,

Right, when this works it's nice, but the problem is that using `svn ls https://github.com/...` is unexpected / counter-intuitive, doesn't work consistently with all URLs, and isn't documented anywhere that I can find.

>after all we need only the svg files and I don't think that they are so heavy.

For the build process we really just need the _list_ of svg files, not even the files themselves. For real installs the files are served via https://twemoji.classicpress.net.

**Comment by mattyrob** [comment]
Could we use the GitHub api:
`https://api.github.com/repos/twitter/twemoji/contents/assets/svg/`

**Comment by nylen** [comment]
I am pretty sure I did not see this API endpoint the last time I looked! However it won't work for this purpose. From https://developer.github.com/v3/repos/contents/:

> This API has an upper limit of 1,000 files for a directory. If you need to retrieve more files, use the [Git Trees API](https://developer.github.com/v3/git/trees/#get-a-tree).

So I suppose figuring out how to use their Trees API would be another way to do this.

**Comment by mattyrob** [comment]
The Trees API also needs to use a SHA in the url so it gets quite a lengthy process.

First a call to get the trees URL here:
`https://api.github.com/repos/twitter/twemoji/branches/master`

Then a call to the URL above to fine the URL for the `assets` directory:
`https://api.github.com/repos/twitter/twemoji/git/trees/ea00df89133cb5e14c206a60b3f4ba1a8eab50a3`

Then a call to find the URL for the `sag` directory:
https://api.github.com/repos/twitter/twemoji/git/trees/b0ec6ee80293b0c03dd7ff134d0379da0e9ed110

And at last you have the link you need:
`https://api.github.com/repos/twitter/twemoji/git/trees/75a4de807203ae97a1677a60b9c1f110c80e1b07`

It isn't showing as truncated but that may well change as the directory contents increases.

Also this is a multi-stop process with multiple failure opportunities and each response needs parsing to find the URL needed.

Possible, but perhaps not optimal.

**Comment by nylen** [comment]
Nice investigation! Let's verify the response code from each API call, and also add a check to make sure the `truncated` response is `false`. The GitHub API is very reliable and that is still an easier approach than what I had considered above.
