### ISSUE TITLE
Remove polyfills for php 5.6<

### ISSUE THREAD

**Issue by Mte90** [ClassicPress/ClassicPress#451]
There are 2 tickets about remove polyfills for php 5.6<:

* https://core.trac.wordpress.org/ticket/47698
* https://core.trac.wordpress.org/ticket/47699

Now CP support only php 7.0> so we can simplify, I am not sure if we already removed everything.

**Comment by nylen** [comment]
Thanks for the issue, this is a good, specific ticket that will be fairly easy to work on once the WP patches are finalized.

We have already done some of this removal, but I don't remember touching the specific parts mentioned in these tickets.

Once this is vetted then I see no reason not to merge it in.

I'm changing the labels here as "dead code we can remove" is not a bug that breaks anything.

**Comment by nylen** [comment]
#622 is a good start at this but there are two changesets we shouldn't include until v2.0 because they are breaking changes:

- https://core.trac.wordpress.org/changeset/46206
- https://core.trac.wordpress.org/changeset/46208

**Comment by viktorix** [comment]
Will be included in v2.0.
