### ISSUE TITLE
Add repository client (plugin)

### ISSUE THREAD

**Issue by ginsterbusch** [ClassicPress/ClassicPress#46]
It would do good, also for preparation for v2, to add a proper repository client, which at this point lets one choose from what sources updates for plugins and themes shall be retrieved. As an additional feature, the user could optionally enable Github-based updates for plugins and themes, ie. essentially adding what all Github Update plugins try to achieve.

Of corpse this would also be a great source for the CP update itself, too. With this, one could choose whether one would like the latest "builds" straight from this github repository, or just regular releases  .. and so on.

For the LTS version, it should be implemented as a (feature) plugin, but for the v2, it should be a direct part of CP.

This could also lead to an improved display of available plugins and themes, similar to the Ubuntu / Linux Mint Software Center, or how F-Droid presents its "goods". AFAIK the current view is dominated by Automattic-centric plugins, and next on, by the download numbers of each plugin. 
Plus, thanks to the somewhat worse search function these days - which I'd also like to improve on, because some parts are totally uncipherable even to senior wizards like me - small plugins which would help ones purposes tremendously simple fall down the drain. 

Eg. recently I searched for some kind of system status info, similar to the one of the WooCommerce system status page, but couldnt find anything. Thus I proceeded to write my own, and was already half-way done, when I went on another search for good UI examples .. and by a few twists and jumps through hoops found out: There are already at least THREE plugins which do what I've been happily been hacking together ..

cu, w0lf.

**Comment by scottybo** [comment]
Could you link to the plugins you've found? Still trying to wrap my head around exactly how this might work/look

**Comment by ginsterbusch** [comment]
As already mentioned on slack (mostly #plugins), AFAIK there are no plugins that do exactly as the one detailed above. Yes, there are some who tie into the regular update mechanism, eg. the Github Updater plugin (https://github.com/afragen/github-updater), the EnvatoMarket plugin for stuff bought on ThemeForest, plus other "premium update" plugins, like for ACF Pro.

I also dug a bit around in the wp.org plugin directory, but found only a few plugins pointing into the direction of what I detail above, but none doing the exact same thing. List as follows:

- https://wordpress.org/plugins/plugin-central/ - among other features, lets you "Install plugins directly by typing the name of plugin or the URL to zip file"
- https://wordpress.org/plugins/wpcore/ - "WPCore is a tool that allows you to manage collections of WordPress plugins and then quickly install them on any WordPress site. You can generate your collections at https://wpcore.com"
- https://wordpress.org/plugins/no-longer-in-directory/ - "No Longer in Directory" - as the name exactly says: Checks for installed plugins which are out of some reason (eg. Malware, committing crimes against humanity aka violating the GPL etc.) removed from the Plugin directory - or in some other way disabled 
- https://wordpress.org/plugins/cleaner-plugin-installer/ - "Cleaner Start Page for “Add Plugins” (Installer)" including "A LARGE search box to find plugins for installing more easily and way faster." and removal of the“Featured” tab

cu, w0lf.

**Comment by Mte90** [comment]
We was talking about a repository system but is not easy to do and quickly.
We was thinking for the moment to use the wordpress one for plugins/themes with caching and in the future implement something on our own.

**Comment by ginsterbusch** [comment]
@Mte90 its more like a rudimentary app store / package system of sorts. Also its to document how the inner updating routines of WP and esp. the repositories at WP.org work, thus we may duplicate them for further use. Even if the outcome is "just" the documentation part, its worth the work.

I added this suggestion so its out in the open, to avoid wheel reinventions by others. Essentially my plan is to implement this as a stand-alone, feature plugin anyway. Whether parts of that find its way into the collection of "CP Core Plugin" or not is up to decision.

cu, w0lf.

**Comment by mikeschinkel** [comment]
@ginsterbusch 
> _"Of corpse"_

Of _**corpse**?_  Pretty morbid, don't you think?  😀

But otherwise, a great idea.

**Comment by nylen** [comment]
@ginsterbusch is one of those German death metal guys.

Some discussion about this is also happening at #164.
