### ISSUE TITLE
"Compatibility with ClassicPress 4.9.10" in plugins screen

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#462]
![cp-4-9-10](https://user-images.githubusercontent.com/227022/62555368-50001800-b862-11e9-9386-8dfd958962bf.png)

We should change this "ClassicPress 4.9.10" to more clearly indicate what it really is: the plugin declares compatibility with a specific WordPress version in the 4.9 branch, which corresponds to a specific ClassicPress version.

**Comment by Norskes** [comment]
I think we can't apply "according to its author" to CP version as author originally declared compability with WP and is not responsible for our possible backport issues. He did not claimed that his plugin is compatible with CP actually.

Maybe we should use both WP and CP for now? 
Kinda:
> Compability with Wordpress X.X.X.: 100% (according to plugin's author).
> Compability with ClassicPress X.X.X.: 100% [according to whatever].

Or, alterntively, we can make a FAQ page that explains those compability logic in general. Then just link it here in a short way:
> Compability with ClassicPress X.X.X.: 100% [More info](#).

**Comment by nylen** [comment]
> I think we can't apply "according to its author" to CP version as author originally declared compability with WP and is not responsible for our possible backport issues.

agree, so I think there are 2 things we need to do here.

1. (short-term) Update to say "Expected compatibility with ClassicPress x.x", and remove the "according to plugin's author" wording. This will be based on the WordPress compatibility declared in existing plugin manifests. We can also add a "More info" link, probably to somewhere on docs.classicpress.net.
2. (long-term) Come up with a way for plugins to declare explicit compatibility with ClassicPress and re-add the "according to plugin's author" wording when this is present.
