### ISSUE TITLE
WP-CLI issue with `wp core check-update`

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#470]
https://github.com/xxsimoxx/cpcompatibility/blob/1156ef6d98a86e902a218514bfcc4f196d47a666/cpcompatibility.php#L37-L56

Thoughts on incorporating something like this into core? @xxsimoxx @johnalarcon

Edit: we'd probably want to parse the update response more thoroughly, including showing what new version of ClassicPress is available, and also making the update actually work using WP-CLI would be good.

**Comment by xxsimoxx** [comment]
I'm a big fan of wp-cli, so I'd like to see a fix in the core. The code was written before CP 1.x, and as I can remember `wp core update` works correctly, just `wp core check-update` is buggy.
Just tested now, but not sure this is the right way, by changing values in version.php.
Sure the response could be processed better! This is the response:
```
(
    [0] => stdClass Object
        (
            [response] => latest
            [download] => https://github.com/ClassicPress/ClassicPress-release/archive/1.0.1.zip
            [locale] => en_US
            [packages] => stdClass Object
                (
                    [full] => https://github.com/ClassicPress/ClassicPress-release/archive/1.0.1.zip
                    [no_content] => 
                    [new_bundled] => 
                    [partial] => 
                    [rollback] => 
                )

            [current] => 1.0.1
            [version] => 1.0.1
            [php_version] => 5.6.4
            [mysql_version] => 5.0
            [new_bundled] => 4.7
            [partial_version] => 
            [dismissed] => 
        )
)
```

**Comment by xxsimoxx** [comment]
I've updated the repo. Now the output is much closer than the original.
But I can't figure out how to grab command line options.

**Comment by xxsimoxx** [comment]
In the new version of [CPCompatibility](https://github.com/xxsimoxx/cpcompatibility) this fix is handled pretty well, if it could help.
