### ISSUE TITLE
Update jQuery version after security patch

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#476]
From https://forums.classicpress.net/t/classicpress-1-0-2-release-notes/1553/3:

> although Github says the jQuery 3.4.0 security patch has been applied to jQuery 1.12.4 as used in ClassicPress, when you load a CP 1.0.2 site and view source, the jQuery script tag still shows version 1.12.4. This means two things:
>
> 1. It will not be reloaded for a while on sites that have a cache operating, so the vulnerability will still be present
> 2. Penetration testing tools may not realise the file is patched and would therefore still report a vulnerability.

We should change this to e.g. `1.12.4-wp1` which will address this issue.

**Comment by nylen** [comment]
We can use `1.12.4-wp` which is what appears on the latest version of WP (https://core.trac.wordpress.org/changeset/45342). This part of the change was not backported to WP 4.9.11 (https://core.trac.wordpress.org/changeset/46020).

**Comment by nylen** [comment]
Specifically this part:

![2019-09-16T21 02 02Z](https://user-images.githubusercontent.com/227022/64993322-4a680a00-d8c5-11e9-99ea-e37ab2fd72f5.png)

**Comment by pattonwebz** [comment]
I can grab this one

**Comment by nylen** [comment]
@pattonwebz note that @mattyrob has just submitted a PR for this.

**Comment by pattonwebz** [comment]
Nice, thank you @mattyrob. I'll test the PR in a minute :)

**Comment by mattyrob** [comment]
@pattonwebz @nylen Pretty basic one if I read the thread correctly - happy to get some feedback and save you some time if I did it right :)

I did consider adding a `-cp` suffix but stuck with what WP did.
