### ISSUE TITLE
ClassicPress updates should not overwrite composer.json

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#477]
On sites that use a customized `composer.json`, this file will be overwritten when ClassicPress is updated (manually or automatically). This is not the desired behavior as any dependencies will be lost.

We need to modify the update code to avoid overwriting `composer.json`. A couple of options:

- Never overwrite `composer.json`
- Detect whether `composer.json` has been modified and overwrite it if no customizations have been made

**Comment by nylen** [comment]
> invisnet
> with #477, i remember we looked into that when including composer.json - did we miss something or just get it wrong?
> James Nylen 12:37 AM
> no, we looked into something different (what happens when migrating if composer.json already exists)
> I don't think we really got that case right either
> invisnet 12:38 AM
> ah, that'd be it....
> really goes back to the fundamental problem that it's in the wrong place
> James Nylen 12:39 AM
> composer wants to install from the repo where composer.json lives though, right? if that's the only way then there isn't really a better place to put it
> invisnet 12:43 AM
> there was a convo about subdirs etc iirc to solve that - not something for 1.x obvs
> is there any existing logic for not overwriting files?
> James Nylen 12:50 AM
> I don't remember seeing anything like that.. the simplest fix would just be putting if ( $filename === 'composer.json' ) { continue; } in the right place
> yeah, "if it doesn't exist, write it, otherwise leave it alone"
> this works because composer.json (normally) doesn't change across releases
> invisnet 12:54 AM
> it'll change between v1 and v2 won't it?
> nevermind - it'll change when johnpbloch/wordpress-core-installer changes as we've got a specific version in there
> i think we need to change that to "^1.0"
> James Nylen 1:04 AM
> wfm

**Comment by nylen** [comment]
See also: https://github.com/ClassicPress/ClassicPress-Migration-Plugin/issues/61

**Comment by xxsimoxx** [comment]
Reopening to track tests on the merged PR.

**Comment by xxsimoxx** [comment]
Will test using @mattyrob checklist:

- [ ] 1/ Check composer.json doesn't get updated every night after the change.
- [ ] 2/ Make a local Edit to composer.json and make sure that doesn't get overwritten
- [ ] 3/ Force the API to use the old MD5 hash location and make sure the customised file remains in place.
- [ ] 4/ Revert to an unedited composer.json and check that now it does get updated.

**Comment by xxsimoxx** [comment]
All checks done successfully.
@mattyrob for me this issue can be closed. If you agree in the next days I can delete the test endpoint from the API.

**Comment by mattyrob** [comment]
@xxsimoxx - agreed, I've done some local testing and the results are as follows:

1/ V2 nightly from 8/8/2024 to current nightly - composer.json not over-written
2/ Local customised composer.json and V2 nightly from 8/8/2024 to current nightly - composer.json not over-written
3/ Local customised composer.json and V2 nightly from 8/8/2024 to current nightly using old API - composer.json not over-written
4/ Standard composer.json and V2 nightly from 8/8/2024 to current nightly using old API - composer.json was updated
