### ISSUE TITLE
Guard against duplicate MIME-Version header in emails

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#495]
## Expected behavior
Plugins can specify a MIME-Version email header without causing mail delivery failures.

## Current behavior
This may not be the case.

## Possible solution
Backport the fix from https://core.trac.wordpress.org/ticket/43542.

## Steps to reproduce (for bugs)
TODO. See WP Trac ticket above.

## Context
TODO. Need examples of plugins that don't do this correctly.

**Comment by mattyrob** [comment]
Looking at the WP plugin repository for `X-Mailer` and `MIME-Verison` there are a lot of hits on some very broadly used plugins.

There are some false positives in the search referring to ReadMe files and conditional code that ensures these headers are not set but there is still the possibility of duplicated headers from plugin code.

[Plugins that contain 'X-Mailer'](https://wpdirectory.net/search/01EJ1065TTER9DCKBN28QZMW38)
[Plugins that contains 'MIME-Version'](https://wpdirectory.net/search/01EJ10ACXXXCF2A9CYBY0DD6BR)

**Comment by mattyrob** [comment]
PR has been merged and closed - closing this issue now.
