### ISSUE TITLE
Add a new image setting: "Custom Login Image"

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#499]
When working on this issue, start from the `feature/login-image` branch in this repository which includes the work done in #486.

In that PR we implemented a new feature to allow displaying the site's "Custom Logo" on the login page instead of the ClassicPress logo. This was scheduled to be included in version `1.1.0` but it was reverted because the "Custom Logo" option is not a good fit for usage on the login page: it's not available in all themes. See discussion here: https://forums.classicpress.net/t/classicpress-1-1-0-rc1-release-notes/1582/18

Therefore, this issue tracks the work left to be done on this setting before it can be released:

> add a new field to select an image just for this purpose, and while we are at it we might as well add a way to customize the size of the image. This shouldn’t live in the Customizer because displaying the login page is not the theme’s job. I think Settings > General is still the right place for this, but it’s debatable because this section is going to grow somewhat after these changes.

Any code change for this issue should be submitted as a pull request against the `feature/login-image` branch, instead of the normal `develop`.

**Comment by nylen** [comment]
To be clear: the new setting(s) described in this issue should _replace_ the existing "Custom Login Image" setting.

**Comment by bahiirwa** [comment]
Referencing Closed #424 and reverted approach #486 here. 

Using the base of [6be3d69](https://github.com/ClassicPress/ClassicPress/commit/6be3d69c5e36b5325259d4d40b811607e29badc7)

I am suggesting having the UI look like something like this below.

Before checking the box to allow the new image usage. The image box shows the default CP logo.
![Screenshot 2020-02-15 at 19 45 13](https://user-images.githubusercontent.com/7713923/74591768-b9d85600-502b-11ea-9c7f-e01e08184f1d.png)

Steps to use:
1. Set an empty option in the `schema.php`
2. To keep backward compatibility the CP logo html remains as in WP. This logo is shown on the general settings page as shown in screenshot above.
3. When a new image is uploaded, a new button appears for removing the image.

Thoughts welcome.

**Comment by nylen** [comment]
Hi @bahiirwa 

You can use the `feature/login-image` branch as the base for this feature. Something like this should work:

```
git checkout upstream/feature/login-image -B feature/login-image
git checkout -b update/login-image-mychanges
# make and commit your changes
```

Then when you submit a PR, set it to merge back into the `feature/login-image` branch instead of `develop` (I can also change this after the PR is submitted).

As far as the change itself, the logo box should just be empty before the user sets an image. Otherwise we would probably either need to put the CP logo in every site's media library, or do some other hack. We say "If you set an image below ... then the logo image will be shown ... **instead of the ClassicPress logo**" so I don't think this is confusing.

**Comment by bahiirwa** [comment]
Thank you for the feedback. I had the same request for a new branch to PR too. 
 > Otherwise we would probably either need to put the CP logo in every site's media library, or do some other hack. 

The CP logo already exists in the `wp-admin/images/wordpress-logo.svg`. I will begin some pushes, please consider them as WIP.

**Comment by nylen** [comment]
> The CP logo already exists in the `wp-admin/images/wordpress-logo.svg`.

Yes, but not in the media library. The image does need to be in the media library, and relevant settings should store an attachment ID. See https://github.com/ClassicPress/ClassicPress/pull/561#discussion_r382937734
