### ISSUE TITLE
Update dashboard links to link.classicpress.net

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#501]
With the release of the security screen in 1.1.0 we started using the https://link.classicpress.net/ subdomain as the link target for any new links within the dashboard.

We need to update the majority of the existing links to use this scheme also.

I'm not sure whether we should use link.classicpress.net for links to the main forums like the support section, since they are not going to change any time soon. However, links to documentation, individual website articles, etc should definitely be updated so that we can do things like re-organize our documentation site without also requiring a link-updating effort across multiple releases of ClassicPress.

The code for link.classicpress.net is here: https://github.com/ClassicPress/subdomain-link .

**Comment by mattyrob** [comment]
[links.txt](https://github.com/ClassicPress/ClassicPress/files/3708994/links.txt)

Using the `find ./src/wp-admin/ -iname "*.php" | xargs grep "classicpress.net"` command these are the existing links back to a ClassicPress domain in the wp-admin folder.

Some are already using the `link` subdomain. Others look like they may be API type locations, for example `https://www.classicpress.net/version/%1$s`

I can start the process with a little guidance on which links need updating and where you want them pointing.

**Comment by striebwj** [comment]
@mattyrob I think there may also be a couple stray ones in `./src/wp-includes/`. 

Also looks like the `https://www.classicpress.net/version/%1$s` actually redirects to the GitHub release, so that would probably be a good one to point to the link.classicpress.net. 

I would also maybe include the forum ones just in case in the future we move things around on the forums (like when we consolidated all the support forums).

**Comment by nylen** [comment]
>I would also maybe include the forum ones just in case in the future we move things around on the forums (like when we consolidated all the support forums).

:+1: I guess we might as well change all of these, then (except the places where API URLs are called in code).

Probably the best way to do this is to split the URLs into groups/categories and define a structure for their paths on `link.classicpress.net`, fine to do that in multiple steps also.

Here is a list of unique URLs in the above `links.txt` file:

```
$ cat cp/misc/links.txt | grep -Pv 'social@classicpress.net|https://<' | sed -r "s#^.*(https?:[a-z0-9./%-]+).*\$#\\1#" | sort | uniq -c
      3 https://api.classicpress.net/secret-key/1.0/salt/
      1 https://api-v1.classicpress.net/features/1.0/
      1 https://api-v1.classicpress.net/translations/core/1.0.0/translations.json
      8 https://docs.classicpress.net/faq-support/
      1 https://docs.classicpress.net/installing-classicpress/
      1 https://docs.classicpress.net/testing-classicpress/
      1 https://docs.classicpress.net/updating-classicpress/
      1 https://forums.classicpress.net/c/announcements/release-notes
     58 https://forums.classicpress.net/c/support
      3 https://forums.classicpress.net/c/support/
      1 https://forums.classicpress.net/t/classicpress-1-0-0-aurora-release-notes/910
      1 https://link.classicpress.net/forum/security
      6 https://link.classicpress.net/plugin-compatibility
      1 https://link.classicpress.net/security-page
      1 https://link.classicpress.net/security-page/contact-plugin-authors
      1 https://link.classicpress.net/support/security-page
      1 https://petitions.classicpress.net/
      8 https://www.classicpress.net/
      3 https://www.classicpress.net/blog/
      3 https://www.classicpress.net/blog/2018/10/29/classicpress-for-business-professional-organization-websites/
      2 https://www.classicpress.net/contributors/
      1 https://www.classicpress.net/feed/
      2 https://www.classicpress.net/get-involved/
      1 https://www.classicpress.net/join-slack/
      2 https://www.classicpress.net/translating-classicpress/
      7 https://www.classicpress.net/version/%1
      2 https://www.classicpress.net/version/%s
```

**Comment by viktorix** [comment]
What exactly is the status on this? It's something i can help with now, just need to know where this is.

**Comment by joyously** [comment]
Would this apply to other links in the code, that point to documentation?

**Comment by mattyrob** [comment]
Security screen was removed in ClassicPress `2.0.0` and the links.classicpress.net domain is not longer in use.

Closing but can be reopened if a need is identified.
