### ISSUE TITLE
Add a list of curated working plugins in the admin section 

### ISSUE THREAD

**Issue by bahiirwa** [ClassicPress/ClassicPress#526]
Following [petition](https://petitions.classicpress.net/posts/129/have-a-page-on-the-website-where-plugins-that-support-classicpress-can-be-added-and-rated) and [Curated List ](https://forums.classicpress.net/t/new-plugin-subcategories/1719/2) 

Would it be workable to add this link in the about page (any place suitable) so that when someone installs CP, they can have a preview of what works for them to choose?

**Comment by nylen** [comment]
I guess you mean these two links:

- https://forums.classicpress.net/t/plugins-confirmed-working-on-classicpress-v1/308
- https://forums.classicpress.net/t/plugins-built-specifically-for-classicpress/1011

Sounds like a good idea to me while we are working on v2. I think the best way to solve that petition will be to launch v2 but this will be a good step in the meantime.

**Comment by nylen** [comment]
Also we should point to links.classicpress.net for these links, as described in https://github.com/ClassicPress/ClassicPress/issues/501. For example:

- https://link.classicpress.net/plugins/confirmed-working
- https://link.classicpress.net/plugins/built-for-classicpress

**Comment by nylen** [comment]
Also https://forums.classicpress.net/t/must-have-plugins-list/1163

**Comment by viktorix** [comment]
@bahiirwa do we still need this issue? Since we're working on a directory and possible integration, this might not be necessary anymore.

**Comment by bahiirwa** [comment]
This is good for close so we have efforts in one basket.
