### ISSUE TITLE
Privacy Policy notice persists

### ISSUE THREAD

**Issue by johnalarcon** [ClassicPress/ClassicPress#576]
I can't seem to get this notice to go away. I've re-saved the privacy page settings several times. I did not change the page, just re-saved. There are no changes needed to the policy. The notice persists.

![image](https://user-images.githubusercontent.com/12477319/78709059-e4c28600-78c7-11ea-87ae-aad306400412.png)

## Expected behavior
Irrelevant notifications do not persist.

## Current behavior
Irrelevant notice persists.

**Comment by xxsimoxx** [comment]
Seems that it happens when switching language.
It notices about changes on ClassicPress itself and in plugins having a translation for the privacy policy.

![image](https://user-images.githubusercontent.com/29772709/78989873-2015bc80-7b35-11ea-951e-e6a3f25e4d02.png)

**Comment by nylen** [comment]
Does switching the language always cause this notice to appear?

If not, what are the steps to reproduce this issue from a fresh installation of ClassicPress?

**Comment by xxsimoxx** [comment]
I've been able to reproduce it in a new installation by installing a plugin that add a privacy policy content.
Steps:
- Install CP
- Switch to Italian in site language
- Install a plugin that register privacy (Update Manager)
- Switch user language to english (Notice appears)
- Review privacy page (Notice disappears)
- Switch user language to italian (Notice appears)

**Comment by viktorix** [comment]
@xxsimoxx is this still an issue in v2.0?

**Comment by xxsimoxx** [comment]
I've noticed the bug in none of my sites using nightly builds of ClassicPress 2.

**Comment by viktorix** [comment]
We'll close as fixed in 2.0.
