### ISSUE TITLE
Function get_magic_quotes_gpc() is deprecated in ...

### ISSUE THREAD

**Issue by abdusfauzi** [ClassicPress/ClassicPress#581]
https://github.com/ClassicPress/ClassicPress/blob/09556c42cc8d8c7b226ec9729648dde6da2e5a77/src/wp-includes/ID3/getid3.php#L309

I tried to install ClassicPress for testing, expecting I can replace WP on one of my project. I am using Laravel Valet which updated to PHP 7.4. Even my live server is using 7.4. Maybe, I have to wait for this issue to resolve first. No idea how to fix this. Sorry.

**Comment by bahiirwa** [comment]
This issue is fixed in #541. However, a new release is soon to come with these changes. You can test this tree version on your another dummy local server install and give some feedback. 

https://github.com/ClassicPress/ClassicPress/tree/09556c42cc8d8c7b226ec9729648dde6da2e5a77

**Comment by abdusfauzi** [comment]
thanks @bahiirwa :)

**Comment by nylen** [comment]
[`1.2.0-rc1` has been released](https://forums.classicpress.net/t/classicpress-1-2-0-rc1-release-notes/2479) with the fix for this issue.
