### ISSUE TITLE
Composer installation method

### ISSUE THREAD

**Issue by szepeviktor** [ClassicPress/ClassicPress#582]
Do you plan to make it possible like this?

`composer create-project classicpress/classicpress`

**Comment by szepeviktor** [comment]
Oh! I see!
It is possible.

Although no mention of this on https://www.classicpress.net/get-classicpress/

**Comment by nylen** [comment]
I guess it's fair to say the main download page doesn't have highly technical users as its main audience.

Our current documentation on this is here: https://docs.classicpress.net/installing-classicpress/installing-with-composer/

Of note, creating a full project like this:

```sh
composer create-project roots/bedrock my-site
cd my-site
composer remove roots/wordpress
composer require classicpress/classicpress:~1.0
```

Composer installations are still a pretty complex setup, and if we release our own full-project template I think that would mean we'd have to make a lot of the decisions about how things are set up.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by szepeviktor** [comment]
> Composer installations are still a pretty complex setup

I live with them every day.

**Comment by nylen** [comment]
So, you know a lot more about this topic than I do then :)

Is there anything else we should include on that documentation page? That content is also editable on GitHub (link at the bottom of the page).

**Comment by szepeviktor** [comment]
No, thanks.
