### ISSUE TITLE
Should we remove Twenty Fifteen for our v1 release?

### ISSUE THREAD

**Issue by scottybo** [ClassicPress/ClassicPress#6]
~Need to check whether they're GPL too~ See https://github.com/ClassicPress/ClassicPress/issues/6#issuecomment-423826374

@danieltj27 said: All themes in the theme directory are GPL, so the bundled themes will be as well.

**Comment by marctenax** [comment]
For now I suggest default theme Twenty Seventeen or a fork of it Classic Seventeen.

**Comment by danieltj27** [comment]
All themes in the directory must be compatible with GPL licences, although Twenty Seventeen in particular is marked as GPL v2, so that theme specifically would be fine to fork into a 'Classic Seventeen'.

Source: https://themes.svn.wordpress.org/twentyseventeen/1.7/README.txt

**Comment by chiotis** [comment]
What is the point of bundling all TwentySMTHNG themes with ClassicPress?
It is an extra 6,25MB

Let's keep Seventeen only until we decide on a ClassicPress Basic Theme
(more than willing to help on the theme)

**Comment by dsnid3r** [comment]
I say drop all of the default themes except twentyseventeen, no need for the bloat. People know how to install themes or know how to look it up. Does this need anymore discussion?

**Comment by nylen** [comment]
I'd prefer we keep 2 or 3 default options at least.  I've found Twenty Seventeen more difficult to extend than Twenty Sixteen, for example.

**Comment by dsnid3r** [comment]
We should make a final decision on this. After reading @nylen comment I say keep Sixteen and Seventeen, kill the rest. Any objections?

**Comment by dsnid3r** [comment]
Where I do agree with you on the complications for upgrades part totally and can get behind leaving this alone for v1 I just want to make sure we don’t forget this in v2. Eliminate bloat is important, but again not a hill to die on for v1.

**Comment by nylen** [comment]
Sounds like we're all in agreement to leave Twenty Sixteen and Twenty Seventeen in place.

Question: **Should we remove Twenty Fifteen for our v1 release?**

If yes: **Who can volunteer to test migrating a WP site that uses Twenty Fifteen over to ClassicPress?**

I'm fine with doing that as long as we get the upgrade path tested.

**Comment by senlin** [comment]
I have a site that uses TwentyFifteen, I can test what happens. 

Need to test it with the migration plugin or just replace the files and see what will happen?

**Comment by nylen** [comment]
Good clarifying question. We need to prepare a build of ClassicPress with the Twenty Fifteen theme removed, and a way to use the migration plugin with this special build.

Or just remove it and test after, and re-add it if something breaks, but I'm not a big fan of that approach.

**Comment by senlin** [comment]
I just ran the migration plugin on one of my sites (running a child-theme of twentyfifteen) and it works perfect! :thumbsup: 

Bit of feedback:
* It takes a while though and there could be a message explaining that.
* After installing it is not clear where to find the plugin's admin screen as it is stuck under tools. Maybe make a settings link available on the plugin screen?
* The wp-admin/about.php page with the 4 different tabs (What's New, Credits, Freedoms, Privacy) need a lot of rewriting. Maybe that is still on the todo list?

PS also posted on #migration channel on Slack

**Comment by ginsterbusch** [comment]
@nylen: I'd do a seperate branch for that, and if all works well .. done. Afterwars one still may decide to merge it back into master - or not.

cu, w0lf.

**Comment by nylen** [comment]
Yeah, I agree, we can prepare a PR with Twenty Fifteen removed, do a build from there, migrate to it, and see what happens. It will probably work just fine.

@senlin I believe all 3 of your feedback points are on track to be addressed, if not, let's get a specific issue going about each one.

Here is the issue about the admin screens: https://github.com/ClassicPress/ClassicPress/issues/4

**Comment by senlin** [comment]
@nylen yes, the first 2 are also addressed

**Comment by Nodws** [comment]
Remove ALL themes, start with a generic Skeleton Bootstrap 4 theme! (allow color customization in admin) ez gg

**Comment by nylen** [comment]
Yeah, that's kind of what I have been thinking too. Any theme we include needs to be forked so that it doesn't say WordPress in the footer. I've also learned more about the upgrade process, and we still need to test it but I don't think removing themes from our distribution is going to be an issue.

I think we should include a fork of [Susty](https://sustywp.com), which we have been making extensive use of on our own websites.

@jacklenox we are really enjoying working with Susty, it is not only sustainable but "just works" in many more places because it is so light and fast. What are your thoughts on us including a lightly modified version in ClasicPress?

**Comment by nylen** [comment]
We are probably going to need to leave this as-is for our v1 release (Twenty Fifteen, Sixteen, and Seventeen with child themes that switch the footer text to ClassicPress).

**Comment by nylen** [comment]
> We are probably going to need to leave this as-is for our v1 release (Twenty Fifteen, Sixteen, and Seventeen with child themes that switch the footer text to ClassicPress).

Indeed, this is what we did for 1.0.0.
