### ISSUE TITLE
Browser support policy

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#61]
Let's come up with a well-defined and clearly-communicated browser support policy.  For reference:  https://make.wordpress.org/core/handbook/best-practices/browser-support/

If we stick with this, we'll need someone to make sure everything still works on IE11 especially before release.  iOS Safari is also worth its own testing effort.

**Comment by KTS915** [comment]
Ugh, how I hate the fact we need to tackle this. I no longer test IE11 on any of my sites, so I would love to be able to drop that and say "use Edge (or something else)" instead. And does WP really test support for UC Browser for Android and Baidu, both of which have over 1% of usage? https://caniuse.com/usage-table

**Comment by nylen** [comment]
> I no longer test IE11 on any of my sites, so I would love to be able to drop that and say "use Edge (or something else)" instead

I have no problem with this personally :wink: However I am surprised that IE 11 is at over 2.5% usage still.

The only thing that may have changed browser compatibility so far is the introduction of an inline SVG for the ClassicPress logo in https://github.com/ClassicPress/ClassicPress/pull/32.

**Comment by nylen** [comment]
We will most likely not change this for v1.  Let's get something up on our docs site though, one way or another.

**Comment by nylen** [comment]
Note: In #32 and #149 we've added a couple of inline SVG images to the dashboard, and more related discussion in #212.

**Comment by nylen** [comment]
To-do items for this issue:

- Test ClassicPress and the ClassicPress dashboard in IE11 and iOS Safari.
- Write a brief page similar to https://make.wordpress.org/core/handbook/best-practices/browser-support/ for ClassicPress.  The content can start here or on [our forums](https://forums.classicpress.net/c/team-discussions/documentation).

**Comment by viktorix** [comment]
Any specific version of iOS Safari? 

Maybe my wife's iPhone can finally be useful 😂

**Comment by ginsterbusch** [comment]
The IE usage is probably coming from something like users having to run a specific browser version at work, because their companies are using some (mostly banking or government-based) software which REQUIRES IE11 (or IE 9 - 10).

cu, w0lf.

**Comment by Mte90** [comment]
Maybe we can open a thread on discourse to involve more the contributors for this testing?

**Comment by viktorix** [comment]
Looks like I have IE 11.253 on my PC still. I'll see what I can do.

**Comment by nylen** [comment]
I'm sorry.  Also, thank you.

**Comment by striebwj** [comment]
Forum link: https://forums.classicpress.net/t/classicpress-browser-support/815
Docs link: https://docs.classicpress.net/browser-support/

**Comment by nylen** [comment]
I'm good with this for now, thanks Wade.  Testing in IE11 and iOS :hankey:afari is still welcome, but that can just as well happen during the rc phase.
