### ISSUE TITLE
Invalid password reset link if usernames ends with a dot

### ISSUE THREAD

**Issue by ElisabettaCarrara** [ClassicPress/ClassicPress#614]
## Expected behavior

When requesting the password reset link from the Forgot Password link in login screen for users with username ending in dot (.), the link that is sent to the user via e-mail should be valid.

## Current behavior

When username has an ending dot (.) this is dropped in the password reset link sent by e-mail.
Adding the dot(.) at the end of the URL manually solves the issue. Also using a version of the username without the ending dot (.) solves the issue. Tested with ELI.CA. (invalid link) and ELICA (valid link) usernames.

## Possible solution

I suppose this behavior is caused by a feature ensuring no dangerous parameters can be passed via URL (htaccess file ends with a dot....), I am not sure this should be fixed if this is the case, for safety is more important.
From my research this issue of the invalid password reset link can be caused by a plethora of different reasons like aggressive caching or an old version of the core codebase that was not updated to remove the <> in the function generating the link. As far as I know nobody reported the issue I am seeing now, so I am perhaps the first to experience this.

## Steps to reproduce (for bugs)

- Install ClassicPress creating an user with username with ending dot (.)
- Try asking for reset password link from Forgot Password on login screen
- The link is invalid.
- Add the dot at the end of the link (that should show the username) and try again. The link now works.

## Context

Companies sometimes have names with ending dots and may want to have the corresponding username for branding purposes.

**Comment by mattyrob** [comment]
I am trying to recreate this issue. I'm using Version 1.2.0-rc1+dev of ClassicPress on a localhost install on a Mac.
Apache 2.4.46 (Unix)
PHP 7.4.9
MySQL 8.0.21

I've created a username `dot.test.` and the reset link in the email seems correctly formatted and works for me.

Could this be an issue in link parsing in an email client? Does the same issue arise if any other punctuation is used at the end of the link?

**Comment by ElisabettaCarrara** [comment]
Good question. I am using a gmail as concerns mail client and I have not tested with other punctuation. I will test it this morning and report.
My setting was a clean install at latest stable installed with softaculos.

**Comment by nylen** [comment]
>Could this be an issue in link parsing in an email client?

I think so. The most likely fix would be to URL-encode any trailing dots.
