### ISSUE TITLE
Remove PHP <=5.5 compatibility code

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#63]
There is a bunch of compatibility code that we can remove after bumping the PHP version to 5.6:

https://gist.github.com/nylen/6972a7a7bbeaa5a53818c224fc6c5b41

I think we can accept PRs that remove this code for v1, but I don't think we should make it a requirement - we've got enough tasks that _have_ to get done for the release on our plate already.

**Comment by senlin** [comment]
@nylen - I just noticed https://github.com/ClassicPress/ClassicPress-APIs/blob/master/core/version-check/1.0/index.php#L17 shouldn't that line be changed to 5.6?

**Comment by nylen** [comment]
Yes, indeed that should be `5.6.0`.

**Comment by senlin** [comment]
can we do that directly in core or should we do that in a PR?

**Comment by nylen** [comment]
I think it's ok to push directly to `master` on the API repo for now, but we'll probably want to lock that down once we start getting more activity there.

**Comment by senlin** [comment]
here you are :)

**Comment by senlin** [comment]
not sure about this one:
https://gist.github.com/nylen/6972a7a7bbeaa5a53818c224fc6c5b41#file-version_compare_php_version-sh-L11

**Comment by nylen** [comment]
agreed, that one needs to stay.  I think I just did some kind of search for `version_compare` and `PHP_VERSION`.

**Comment by senlin** [comment]
So although a few PRs have been merged, there are 4 more lines that need editing.

Please see my comment from #151:

> In this PR I left out the 4 conditions of the src/wp-includes/class-phpmailer.php-file see L25-28 of the Gist. Especially the last one of that file (L3794) needs some looking at as I am not sure how to go ahead there. 

Perhaps @nylen can take a look?

**Comment by nylen** [comment]
I'd probably leave that alone, to avoid further divergence between PHPMailer upstream and our copy.  I know WordPress has modified this library fairly heavily.

At this point I think we can create a new issue for each of these bundled libraries ("Upgrade PHPMailer", "Upgrade SimplePie", etc), and then close this one.

**Comment by Mte90** [comment]
I don't know if is the case to update that libraries for 1.0.0, if we want to do a LTS better to keep them in that way and for 2.0.0 to change it.

**Comment by nylen** [comment]
Yes, those will definitely be for v2 or later.  It'll be a lot of work with a risk for breaking changes.
