### ISSUE TITLE
Available Widgets section has invisible toggle indicator

### ISSUE THREAD

**Issue by joyously** [ClassicPress/ClassicPress#637]
https://github.com/ClassicPress/ClassicPress/blob/b8e69651c03d019fc8de790499341c7db8469dd7/src/wp-admin/css/widgets.css#L293-L295

If this rule could be removed, then the toggle would be visible and much more accessible.

**Comment by mattyrob** [comment]
This impacts the Appearance > Widgets page in the admin area and unhiding this allows users to collapse the display area listing all Available Widgets.

It seems it **may** be intentionally hidden for use by screen readers but I'm not certain here.

I'm also not sure why I would ever want to use this, not being visually impaired and not ever making huge use of this admin page.

Pinging @MarcoZehe for an opinion on whether this needs any attention.

**Comment by joyously** [comment]
> It seems it may be intentionally hidden for use by screen readers 

When using `display:none`, screen readers don't see it either. That's why accessible things don't use `display:none`.
I think it was a choice that it is not visible by default. If you hover the right spot, it shows and you can use it. It would just make more sense that it shows by default. 
(I use it often, but had no idea it was there until I saw it in a video.)

**Comment by mattyrob** [comment]
I've located the upstream ticket:
https://core.trac.wordpress.org/ticket/37013

It seems there was discussion that some content on that page is not keyboard navigable so perhaps that's why it is intentionally hidden.

Looking at the CSS more though:
```
#widgets-left .sidebar-name .toggle-indicator {
	display: none;
}

#widgets-left .widgets-holder-wrap.closed .sidebar-name .toggle-indicator,
#widgets-left .sidebar-name:hover .toggle-indicator,
#widgets-left .sidebar-name .handlediv:focus .toggle-indicator {
	display: block;
}

```

We could remove all of this. The Toggle is hidden by default when the section is expanded but becomes visible if the section is collapsed, when hovered with a mouse and when the parent element is in keyboard focus.

**Comment by joyously** [comment]
I just tried it with the keyboard and it does show the blue circle on focus.
I agree that removing that CSS would be good since the goal is to have it visible all the time like all the other ones are. (Well, the Inactive Widgets container also has a hidden arrow when open, so it needs the same fix.)
I think you might have to make a change to JS though since it has `aria-hidden="true"` by default.
