### ISSUE TITLE
Support `Requires PHP:` tag in style.css

### ISSUE THREAD

**Issue by benlumia007** [ClassicPress/ClassicPress#640]
We should support `Require PHP` tag in the style.css so that we don't have to create a function to check php versions. This just allows the theme itself to recongized which PHP is required.

**Comment by viktorix** [comment]
The new directory requirements state that Require PHP must be a header in the main PHP file. Core already supports checking it:

https://github.com/xxsimoxx/ClassicPress/blob/b7bf3977d1901ab6539ae1b13532518de69e701a/src/wp-admin/includes/plugin.php#L89

This issue will be closed.

**Comment by smileBeda** [comment]
The line of code you shared is for plugins.
Wp, afaik, adds the RequiresPHP to the theme _style.css_ and that was only added after wp 5.x, so I’m not sure this is actually in cp yet.

if it is, then, afaik the right place to add it is the style css, not php main file (themes do not have a php main file(

**Comment by viktorix** [comment]
You're right, I was thinking about one thing and wrote about a different thing. The [new directory's requirements](https://docs.classicpress.net/plugin-guidelines/directory-requirements/) for themes include `Requires PHP` and `Requires CP` in the style.css. So technically this request is getting implemented.

>that was only added after wp 5.x

If that's the case, the issue still can be closed as that will be included in v2.0.
