### ISSUE TITLE
Unable to create a CP Network (WP Multisite) succesfully

### ISSUE THREAD

**Issue by kubo6472** [ClassicPress/ClassicPress#642]
## Expected behavior
I will follow the provided guide and after saving the changes to wp_config.php and .htaccess multisite will work.

## Current behavior
After following the guide in my site on creating the CP Network, my site will get stuck in 302 redirect loop.

## Possible solution
I was unable to find a working solution on the internet, as nobody seems to cover the exact meaning and rationale behind the individual .htaccess commands.

## Steps to reproduce (for bugs)
1. Add define( 'WP_ALLOW_MULTISITE', true ); to wp_config.php
2. Disable all plugins and open tools -> create CP Network
3. Follow the steps and save them
4. Reload your site

## Context
I am using NGINX on a Debian 10 Server and a site that was not migrated using your migration plugin, but a fresh install with backup getting all files in place. AFAIK no conflicts were present during this process. And I was able to reproduce my error on a fresh install in WNMP. (Windows, Nginx, Mariadb, Php)

Any help appreciated.

**Comment by nylen** [comment]
> I will follow the provided guide

As far as I know, ClassicPress does not provide a multisite guide, since this should be the same as in WordPress. What guide did you follow?

> my site will get stuck in 302 redirect loop.

When I have seen this issue before, it has been because the site URL defined in the database is not exactly the same as the site URL that is visited in the browser.

What URLs are involved in the redirect loop? (you visit URL 1, it redirects to URL 2, etc.)

**Comment by kubo6472** [comment]
> What guide did you follow?

The interactive description when creating the network.

> What URLs are involved in the redirect loop?

Just one https://mysite.eu looping though. I've found somewhere, that root domain doesn't work for this, and I haven't tried moving the main website to www. since I don't want it like that.

**Comment by mattyrob** [comment]
@kubo6472 

Did you ever get this working? Did it work in WordPress.

I wonder if you were trying to create a `Sub-domain` multisite rather than a `Sub-directory` - if your root URL did not contain `www.` then this will fail in both WordPress and ClassicPress.

**Comment by kubo6472** [comment]
Thanks for reminding me, I successfully solved this, but did a ton of things at once, so I am not sure which one was the problem.

**Comment by mattyrob** [comment]
Just for completeness I tested and managed to create both a sub-domain and sub-directory multisite installs from fresh install.
