### ISSUE TITLE
Tiny MCE tooltip for adding links in classic editor disappears and is not clickable.

### ISSUE THREAD

**Issue by james0r** [ClassicPress/ClassicPress#650]
## Expected behavior

Tooltip pops up, lets you add link and click the return icon button.

## Current behavior

Tiny MCE tooltip for adding links in classic editor disappears and is not clickable. This occurs with certain window heights and widths and not others. Bug seems to occur above window height of around 800px.

https://user-images.githubusercontent.com/34731936/104221823-d6d20080-5417-11eb-870a-aaded8f8dc14.mp4

## Possible solution

Probably an errant onmouseleave event handler?

## Steps to reproduce (for bugs)

Install fresh copy of Classic Press

Edit Hello World Post.

Try and make a link out of 'writing' in the post content and save it.

## Context

Confirmed in

Chrome 88.0.4324.77 (Official Build) beta (x86_64) on MacOS Big Sur 11.1 (20C69)

and 

Safari Version 14.0.2 (16610.3.7.1.9) on MacOS Big Sur 11.1 (20C69)

**Comment by james0r** [comment]
Anyone able to reproduce this?

**Comment by timbocode** [comment]
Not so far. I've tested on Chrome (Windows) and FF (Linux) in various window sizes and it's worked as expected. The only thing I haven't done is to test on a Mac which I hope to do later today (Thurs 14 Jan).

**Comment by timbocode** [comment]
I'm afraid I've not been able to reproduce this on a Mac either. However, this was on a Mac running MacOS 10.14.6 (Mojave), Safari 14.0.2 and Chrome 87.0.4280.141 so it's not an exact match for your set up. The only thing that is the same is the Safari version.

Could someone else have a go at testing this please? Someone with a device that matches the OP's spec.

**Comment by james0r** [comment]
I grabbed a performance profile recording in the Chrome devtools. Hoping someone who understands this better than myself might see something.


[tiny-mce-tooltip-perf-profile.json.zip](https://github.com/ClassicPress/ClassicPress/files/5831453/tiny-mce-tooltip-perf-profile.json.zip)

**Comment by timbocode** [comment]
I asked on [Slack](https://www.classicpress.net/join-slack/) if someone could test this. So far, one person has responded and said:

> I just tested on Big sur, I highlighted ClassicPress, click on the link, type whatever, and enter, and click somewhere else and the pop up thing disappear, i can edit fine too. by clicking on ClassicPress and the popup appears.
> 
> So it seems perfectly fine for me

It does seem however that Big Sur is still generally quite buggy.

I've found a couple of possibly related mouse issues here which may or may not help:

https://developer.apple.com/forums/thread/658180

https://answers.microsoft.com/en-us/msoffice/forum/all/how-can-i-prevent-my-mouse-cursor-from-flickering/dd7aff81-c366-49e4-9d4f-53ce222e4ff8

I'll try to take a look through the performance profile when I get chance.
