### ISSUE TITLE
Function that is missing from ClassicPress

### ISSUE THREAD

**Issue by InkyQuill** [ClassicPress/ClassicPress#652]
It seems that some plugins use the function which was removed from wp-includes/link-template.php
This one: https://developer.wordpress.org/reference/functions/is_avatar_comment_type/

Plugins affected: Leira Letter Avatar. 

## Expected behavior
Comment avatars are showing in admin console

## Current behavior
Fatal error.

## Possible solution
Return the function to the file. I just copied the aforementioned function from wordpress dev site and it works.

**Comment by timbocode** [comment]
Thanks for reporting this.

That particular function was first introduced in WP 5.1.0. CP is based on WP 4.9 so afaiaa, it's never been included in CP. But we'll take a look and then consider it for inclusion in the CP codebase.

**Comment by nylen** [comment]
@InkyQuill Which plugin(s) are you experiencing this error with?

**Comment by nylen** [comment]
> Plugins affected: Leira Letter Avatar.

[This plugin states](https://wordpress.org/plugins/leira-letter-avatar/) that they are compatible with WP 4.7 and above, but this is wrong - it will fail in any WP version 5.0 or below. You should report this issue to the plugin developers and ask them to remove the call to this function, keeping compatibility with WP 4.9 and also ClassicPress.

**Comment by InkyQuill** [comment]
But as I can see in developer.wordpress.org snippet for aforementioned function, it is present since WP 3.0.0, or is their PHPDoc comment incorrect? 

As for the plugin, I'll contact them. Thanks.

**Comment by timbocode** [comment]
If you look on the page you linked to (https://developer.wordpress.org/reference/functions/is_avatar_comment_type/), under the **Changelog** heading, you'll see that `is_avatar_comment_type` was introduced to WordPress in version 5.1.0.

Just to satisfy my own curiosity, I just "grepped" (searched) for `is_avatar_comment_type` in WP4.9 and WP5.1 and this is the result:

![grep-is_avatar_comment_type-func](https://user-images.githubusercontent.com/4199514/104959648-97348700-59ca-11eb-8355-e8f030435ca8.jpg)


As you can see, nothing was found in WP 4.9 but it was found in 5.1.

I also installed Letter Avatar on WP 4.9 and got  this error:

```
PHP Fatal error:  Uncaught Error: Call to undefined function is_avatar_comment_type() in .../wp-content/plugins/leira-letter-avatar/public/class-leira-letter-avatar-public.php:174
```

So, as @nylen says, to make this plugin compatible with CP, the dev will need to remove that function and update the details on the WP repo.

**Comment by mattyrob** [comment]
> But as I can see in developer.wordpress.org snippet for aforementioned function, it is present since WP 3.0.0, or is their PHPDoc comment incorrect?
> 
> As for the plugin, I'll contact them. Thanks.

I just had to look twice at the inline PHP documentation to realise that it is the filter that was introduced in 3.0.0 and that it has been included in this new function introduced in WP 5.1.0.

This does look to me like the theme is incorrectly reporting compatibility with lower levels of base code than it actually supports.

**Comment by timbocode** [comment]
Whatever it is, the developer has issued a fix now https://github.com/arielhr1987/leira-letter-avatar/issues/1

**Comment by nylen** [comment]
Closing this, the solution is to upgrade to the latest version of the Leira Letter Avatar plugin.
