### ISSUE TITLE
Petitions Link not working

### ISSUE THREAD

**Issue by ridesirat** [ClassicPress/ClassicPress#664]
Hi guys
Great work around here!
First time exploring and I'm very interested in keep doing so.
Just to let you know I come across several links to this page (https://petitions.classicpress.net) that is not working.
Links here (GitHub > Read me), on the website, etc?
All the best

**Comment by bahiirwa** [comment]
Hi @ridesirat, This is a nice catch we need to address in the redirects, however, petitions have been moved to https://forums.classicpress.net/c/governance/petitions/77

Please check them out on the forums.

**Comment by ridesirat** [comment]
Yep, I imagined so.
Thanks!
