### ISSUE TITLE
Required extensions for ClassicPress v2 support

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#704]
Alternative to ClassicPress/ClassicPress#397. ClassicPress version 2 will require the cURL HTTP transport and deprecate/remove support for the streams transport. Installing ClassicPress v2 (whether a fresh install or an upgrade from 1.x) should be blocked if cURL support is not present.

**Comment by nylen** [comment]
Update - we also need to do the same for the JSON extension, and include the changesets mentioned in https://github.com/ClassicPress/ClassicPress/issues/451#issuecomment-824452066. Here is a start at how to do that during the upgrade process: https://core.trac.wordpress.org/ticket/47699#comment:29 (and subsequent comments)

**Comment by viktorix** [comment]
With re-fork work getting underway, we should consider closing backporting issues such as this.
