### ISSUE TITLE
Corporate support

### ISSUE THREAD

**Issue by ashgoodman** [ClassicPress/ClassicPress#73]
This may be the wrong place to post this?

I believe for this project to remain viable in the long term it needs financial backing in a way that doesn't cede control. I've seen too many great open source projects die for lack of funding. Community will only get us so far. A project like this needs a core, dedicated, full-time team. And that doesn't happen without funding. 

To me the logical choice would be WordPress development firms that have a vested interest in avoiding having to rebuild loads of client websites and in having a stable LTS version.

Are there plans to set up a marketing division to seek either financial backing or dedicated dev time from some of the bigger WordPress development firms?

**Comment by Mte90** [comment]
The best way is discuss on Slack https://www.classicpress.net/get-involved/

We are evaluating now for sponsors (check the website) but all this kind of discussions happen on slack.
Better to leave this github repo to the technical stuff of the project.
