### ISSUE TITLE
Remove Hello Dolly during build process

### ISSUE THREAD

**Issue by ashgoodman** [ClassicPress/ClassicPress#74]
Can we finally get rid of the Hello Dolly plugin now?

**Comment by Mte90** [comment]
Already discussed there https://github.com/ClassicPress/ClassicPress/pull/60

**Comment by senlin** [comment]
@ashgoodman 
Thanks for your input. We have a petitions websites where feature requests are made and voted on: https://petitions.classicpress.net/

As the list there is growing, we recommend doing a search, before writing a feature request.

There are also a few feature requests that have already been voted on and implemented (filter on completed) and removing Hello Dolly is one of them.

You are more than welcome to join our Slack channels and get involved.

Hope that helps.

**Comment by nylen** [comment]
Reopening this - we don't have an issue yet for removing Hello Dolly from the build, and we need to track this for v1.
