### ISSUE TITLE
Unable to load plugin preview iframe on plugin search page

### ISSUE THREAD

**Issue by scottybo** [ClassicPress/ClassicPress#77]
## Expected Behavior
After searching for a plugin in the directory I click on its title to learn more about it. I expect a modal to appear with more information

## Current Behavior
Nothing happens when clicking on the link

## Possible Solution
n/a

## Steps to Reproduce (for bugs)
1. Search for a plugin
2. Click on the plugin name

## Context
I want to learn more about a plugin before installing it

**Comment by stefanos82** [comment]
@scottybo That's a common behavior from WordPress's API.

Add `198.143.164.251 api.wordpress.org` inside your `/etc/hosts` and try again.

In case the IP changes in the near future, run `dig +short api.wordpress.org` and add the new IP inside `/etc/hosts`.

**Comment by nylen** [comment]
@stefanos82 any insight into what may be going wrong there / why this happens?  Would it be an easy fix?

**Comment by stefanos82** [comment]
My assumption is that **it cannot always** establish a secured connection; when you add it the IP though, it works as expected.

For instance, I have just disabled the IP from my `/etc/hosts` and plugin preview works now as expected.

Another possible issue could be the use of IFRAME which to preview the plugin which again depends on secured connection.

I could be wrong, but this is what others speculate as well, so...

**Comment by ginsterbusch** [comment]
Yeah, iframes as an overlay with non-secure vs. secure connections always fail. It works in Firefox, but not in Chrome + related browsers. AFAIK Its a security feature to avoid sniffing / man-in-the-middle attacks

**Comment by stefanos82** [comment]
If you mean the plugin preview, it works for me on both Firefox and Chromium.

**Comment by nylen** [comment]
Huh, yep, that would do it, though I would think the page from wp.org would be served over https. Why does this fail sometimes?

Is there a wp core Trac ticket about this issue?

**Comment by stefanos82** [comment]
I don't remember seeing any ticket open, but I know for sure many folks have had this issue for a couple of years now and can be found all over the internet.

As of what causing it, again I have no idea.

**Comment by ginsterbusch** [comment]
My guess would be, if its related to SSL vs. Non-SSL, that the remote server needs more processing time for SSL (thats generally the case) and thus sometimes is taking too long. Or when there is a bad connection, or some sharks or fisher accidently ripped out the atlantic cable connection again ... Maybe a higher timeout might solve this?

cu, w0lf.

**Comment by nylen** [comment]
We need exact repro steps for this bug, or at least access to a site where it's consistently broken, in order to do anything about it.  Marking as "needs more info".
