### ISSUE TITLE
Upgrade from REST for GraphQL

### ISSUE THREAD

**Issue by bahiirwa** [ClassicPress/ClassicPress#78]
Feature request. This could be future/planned. REST API is currently bloated with so much information one seldom needs and could be improved in speed relatively. I suggest running with GraphlQL.

## Expected Behavior
- Improved speed on API.
- Query only information needed by user.

## Possible Solution
This could be a start. https://github.com/wp-graphql/wp-graphql

**Comment by Mte90** [comment]
We have the approach to discuss with the community and vote the features before open an issue for that.
Check https://petitions.classicpress.net/ to follow our workflow :-)

**Comment by epakrat** [comment]
Ideally, REST and GraphQL should both be implemented and available as plugins rather than being part of core IMHO.

**Comment by senlin** [comment]
@epakrat thanks for your input. You can actually make your voice heard by voting on these and other features via our https://petitions.classicpress.net/ website.

**Comment by nylen** [comment]
Summarizing my comment at https://petitions.classicpress.net/posts/72/upgrade-rest-to-graphql: there is a `_fields` parameter which satisfies the original need for this issue, and we are probably about 3 years too late to decide not to include the REST API.
