### ISSUE TITLE
Update jQuery to latest version to avoid "Best Practice" audit issues

### ISSUE THREAD

**Issue by smileBeda** [ClassicPress/ClassicPress#783]
Currently ClassicPress loads jQuery v1.12.4 and that throws a warning in LightHouse (and possibly other) tool.
It will state there are security issues due to the outdated script

<img width="763" alt="Screenshot 2021-08-26 at 13 35 33" src="https://user-images.githubusercontent.com/11800236/130974537-2844b4b9-f536-4e94-869f-b3a558d2cce8.png">

This will 
A) Decrease search engine ranking of the website
B) Surely not help our statement of being a secure CMS.

I think on new installs we should simply ship 3.x jQuery. 
On Existing installs (update) we may ship a migration script.

Changeset:
https://core.trac.wordpress.org/changeset/49101

**Comment by ginsterbusch** [comment]
> This will
> A) Decrease search engine ranking of the website
> B) Surely not help our statement of being a secure CMS.
> 
> I think on new installs we should simply ship 3.x jQuery.
> On Existing installs (update) we may ship a migration script.


I wouldn't "just replace it". ClassicPress 1.x tries to be a drop-in replacement for WP 4.9.x - and the jQuery version certainly is a big part of that, too.

ESPECIALLY I wouldnt touch jQuery. That's dependency hell and the most "sacred" part. It would mean breaking A LOT of plugins, and that is what ClassicPress 2.x is for, but not CP 1.x :)

But there is a snippet collection @striebwj mentioned in the forums, which might be a better place for this. On the other hand, I wanted to start working on a WP 5.x compatiblity plugin, so maybe thats another option?

cu, w0f.

**Comment by TukuToi** [comment]
Most plugins and themes have had to live with jQuery 3.x since WP updated those.
Anyway, yes this is probably a 2.x release thing.
I am not sure what you mean with "just replace it"

I did not replace - I back ported the WP commits and now it is about fixing the deprecations inside CP.

**Comment by TukuToi** [comment]
Next step https://core.trac.wordpress.org/ticket/51812
Will be on this ASAP 

seems like we’ll be skipping compatibility mode

**Comment by KTS915** [comment]
Since the beginning of the year, I have been running ClassicPress on production sites with jQuery v1 disabled. In fact, I have been using this script, hooked into `wp_enqueue_scripts`, to load v3 instead from a local folder:
```
wp_deregister_script( 'jquery' );
if ( current_user_can( 'manage_options' ) ) {
	wp_enqueue_script( 'jquery', $domain . '/panzoom/jquery-3.6.0.min.js', null, null, true);
}
```
I have had no breakages at all during this period, including none from any plugins I use, though should change the deprecated opening `jQuery(document).ready(function($) {` to `jQuery(function($) {`

So it seems to me that it's safe for core to change to jQuery v3.

(As you may infer from this, I don't use jQuery on the front-end of those sites — just plain JavaScript — except when I'm logged in as an administrator, and then it's only because the plugin, Query Monitor, requires it.)

**Comment by Loggercod** [comment]
The PymSEO Plugin has an option that updates jquery in an excellent way.

**Comment by Loggercod** [comment]
The PymSEO Plugin has an option that updates jquery in an excellent way. Despite not being updated 2 years ago, all the functions of this plugin work perfectly in the current version of ClassicPress. I got excellent results with it.

**Comment by bahiirwa** [comment]
> ESPECIALLY I wouldnt touch jQuery. That's dependency hell and the most "sacred" part. It would mean breaking A LOT of plugins, and that is what ClassicPress 2.x is for, but not CP 1.x :)

Unfortunately, the web is breaking on its self. See: https://blog.jquery.com/2022/12/13/jquery-3-6-2-released/
As CSS and other languages grow in their implementations, we are stuck in the past and will have to offer support for broken themes and plugins in such cases.

Maybe this should the part we bring in version 2. Start with the none complicated but essential parts that need to move.

**Comment by smileBeda** [comment]
I think you have better chances to win the lottery than finding _one single plugin or theme_ that still uses and relies upon jQuery 1.8, and does that _on purpose_. If any, it will be either because it is abandoned, or developed _specifically_ for the (outdated) CP.
Basically all plugins do NOT enqueue jQuery on their own but use Core jQuery. And thus, _every single plugin out there_ (again, unless specifically developed for an outdated CMS) would already be jQuery 3.x ready, making the whole migration phase totally obsolete, as I pointed out here:
https://github.com/ClassicPress/ClassicPress/issues/783#issuecomment-910279466

**Comment by KTS915** [comment]
Yes, I think we could now safely update jQuery to bundle whatever is the latest code — there probably is a backport that could do this — in a regular new release, e.g. v.1.6.0.

**Comment by bahiirwa** [comment]
Pinging @mattyrob @xxsimoxx 
Upstream took the following:

Step one
- [ ] [Ticket 37110](https://core.trac.wordpress.org/ticket/37110)
  - [ ] [Changeset 48323](https://core.trac.wordpress.org/changeset/48323)
  - [ ] [Changeset 48324](https://core.trac.wordpress.org/changeset/48324)
  - [ ] [Changeset 48753](https://core.trac.wordpress.org/changeset/48753)
  - [ ] [Changeset 48754](https://core.trac.wordpress.org/changeset/48754)

Step Two
- [ ] [Ticket 50564](https://core.trac.wordpress.org/ticket/50564)
  - [ ] [Changeset 49101](https://core.trac.wordpress.org/changeset/49101)
  - [ ] [Changeset 49134](https://core.trac.wordpress.org/changeset/49134)
  - [ ] [Changeset 49338](https://core.trac.wordpress.org/changeset/49338)
  - [ ] [Changeset 49615]https://core.trac.wordpress.org/changeset/49615)
  - [ ] [Changeset 49649]https://core.trac.wordpress.org/changeset/49649)
  - [ ] [Changeset 49667]https://core.trac.wordpress.org/changeset/49667)

Step Three
- [ ] [Ticket 51812](https://core.trac.wordpress.org/ticket/51812)
  - [ ] [Changeset 50001](https://core.trac.wordpress.org/changeset/50001)
  - [ ] [Changeset 50270](https://core.trac.wordpress.org/changeset/50270)
  - [ ] [Changeset 50367](https://core.trac.wordpress.org/changeset/50367)
  - [ ] [Changeset 50383](https://core.trac.wordpress.org/changeset/50383)
  - [ ] [Changeset 50410](https://core.trac.wordpress.org/changeset/50410)
  - [ ] [Changeset 50420](https://core.trac.wordpress.org/changeset/50420)
  - [ ] [Changeset 50429](https://core.trac.wordpress.org/changeset/50429)
  - [ ] [Changeset 50437](https://core.trac.wordpress.org/changeset/50437)
  - [ ] [Changeset 50547](https://core.trac.wordpress.org/changeset/50547)
  - [ ] [Changeset 50627](https://core.trac.wordpress.org/changeset/50627)
  - [ ] [Changeset 52429](https://core.trac.wordpress.org/changeset/52429)

Follow up
- [ ] [Ticket 56743](https://core.trac.wordpress.org/ticket/56743)

Update the jQuery library from 3.6.1 to 3.6.3.
- [ ] [Ticket 57324](https://core.trac.wordpress.org/ticket/57324)
  - [ ] [Changeset 55012](https://core.trac.wordpress.org/changeset/55012)

**Comment by viktorix** [comment]
With re-fork work getting underway, we should consider closing backporting issues such as this.

**Comment by viktorix** [comment]
With the upcoming v2.0, this issue will be closed.
