### ISSUE TITLE
Update login page links

### ISSUE THREAD

**Issue by johnalarcon** [ClassicPress/ClassicPress#796]
## Enhancement
It would be nice if the links on the login page were tidied up. There was a [lot of discussion](https://forums.classicpress.net/t/center-lost-password-back-links-on-login-page/3563/3) about this on the forum. I'm opening this issue so it can be tracked. PR #795 implements this change.

### Current display
![image](https://user-images.githubusercontent.com/12477319/133015052-fba6b607-ba69-49ef-bfaa-9c4760630342.png)

### Proposed change (when Privacy Policy active)
![image](https://user-images.githubusercontent.com/12477319/133015086-f3f07197-7dec-48f3-aecf-3c2bc7d8e05e.png)

### Proposed change (when Privacy Policy inactive)
![image](https://user-images.githubusercontent.com/12477319/133019199-cdf2da9e-7c4d-4ccb-aad0-47c5d63e9fda.png)

**Comment by viktorix** [comment]
@nylen I'm working on the forms, as per [discussion in the forums](https://forums.classicpress.net/t/center-lost-password-back-links-on-login-page/3613/39), and I stumbled on an issue.

There is a function that we will no longer use once we switch to the new form design and I want to deprecate it, in case someone used it. The function is [login_link_separator](https://docs.classicpress.net/reference/hooks/login_link_separator/). By default, it uses `|` to add a separator between links below the forms. With a new form design, there's no need for a separator. 

![image](https://user-images.githubusercontent.com/1692600/137645362-c41c2a65-1e23-4091-82f5-89f6756ab4f2.png)

With a new, improved design we won't have separators:

![image](https://user-images.githubusercontent.com/1692600/137645377-6b640cfd-63d4-49e1-afbd-ac3949028d2d.png)

I want to use `_deprecated_function` to mark `login_link_separator` as deprecated. This function is only used in `wp-login.php` to allow users to filter and change the separator. So there shouldn't be any problems.

What do you think?

**Comment by viktorix** [comment]
I was the one working on this. Closing this ticket as updated forms will be included in the re-fork.
