### ISSUE TITLE
Further improvements to dashboard Petitions widget

### ISSUE THREAD

**Issue by nylen** [ClassicPress/ClassicPress#809]
Feedback raised on the Petitions widget in the dashboard from https://github.com/ClassicPress/ClassicPress-APIs/pull/33.

---

From @simplycomputing:

> Looks good. Works well for me. The only thing I noticed is a line height issue in the background colours. It doesn't look as bad on your screenshots so may be my browser? (Brave).
>
> <img src="https://user-images.githubusercontent.com/46998578/135700970-d1e3bed3-b767-4949-9214-c2eff466162b.jpg" width="420">

From @johnalarcon:

> Because the status is enclosed in a box, there's no need for a hyphen/endash between it and the anchor.
> 
> <img src="https://user-images.githubusercontent.com/12477319/135703536-5cadda08-886e-49ca-8822-85855a74c024.png" width="300">

The format of this is supposed to be `title - status` where `status` can be either the age of an open petition or (currently) "started" or "planned", so I would keep the dash.

Still, I would fix both of these issues at once by changing this text to have a foreground color instead of a background color. I think this also improves the overall look a bit:

<img src="https://user-images.githubusercontent.com/227022/135871259-8c1d22ec-cbe0-47c6-91ed-6f84390714dc.png" width="270">

---

From @johnalarcon:

> The font size of the widget isn't consistent with the other widgets. Adding `font-size:inherit;` to the table's CSS rule brings it consistent.
> 
> ```
> table.cp_petitions {
> 	width: 100%;
> 	padding: 0;
> 	border-spacing: 0;
> 	font-size: inherit;
> }
> ```

The font sizes are as expected for me (have a look at my screenshots here and on https://github.com/ClassicPress/ClassicPress-APIs/pull/33), and adding `font-size: inherit` here has no effect on my site. Your site must have some extra CSS from a plugin or other third-party code that is causing this issue. If you can identify it then we can determine whether this rule should still be added or whether that CSS should be updated to be more specific.

**Comment by simplycomputing** [comment]
New format looks much better. I like the text colour rather than background.

I also agree that full petition titles should be shown.  It could be they put the critical word in the petition right at the very end, eg "Make improvements to the layout and styling of error messages in..."

**Comment by bahiirwa** [comment]
Can we capitalize the status? To give it some emphasis?

**Comment by simplycomputing** [comment]
Like this? It does look better I think.
![capitals](https://user-images.githubusercontent.com/46998578/135971863-190e94bb-346a-46b8-8831-9a158bf1ff11.png)

**Comment by johnalarcon** [comment]
The status was already _emphasized_ with a block of color. Capitalization here serves no real purpose.

>Like this? It does look better I think.

It looks more like a wall of text that way. IMO, those color blocks should be kept, but the saturation should be taken down several notches.

**Comment by simplycomputing** [comment]
I don't mind the colour block approach either, as long as it doesn't push up into the line above.

**Comment by johnalarcon** [comment]
Yeah, I like the "approach", just not the "implementation". I've recently rebuilt this widget (and the other core widgets) for a project – the additional texts and tags didn't make the cut. I'm not sure how, but, I'm going to work in the blocks somehow.

![image](https://user-images.githubusercontent.com/12477319/135973057-d41388da-3fa9-4b9a-8773-4f7fc3b77a49.png)

**Comment by simplycomputing** [comment]
OK. I have to tell you... I really, _really_ don't like the truncation.

"At installation leave a choice between adding d..." 

???

**Comment by johnalarcon** [comment]
Yeah. I hear you. I also really, really dislike when they span more than one line. I'm already dealing with poor grammar, punctuation, and capitalization in my dashboard... ;)

**Comment by simplycomputing** [comment]
Good luck with that. :-)

**Comment by viktorix** [comment]
Closing this issue as we have an updated issue:
https://github.com/ClassicPress/ClassicPress/issues/1069
