### ISSUE TITLE
Drop support for IE11

### ISSUE THREAD

**Issue by viktorix** [ClassicPress/ClassicPress#837]
IE11 is far below 1% usage now, so it's time to drop it and backport changes from WordPress. [Discussion](https://forums.classicpress.net/t/classicpress-browser-support/815/).

## Expected behavior
IE11 no longer supported.

## Current behavior
IE11 supported.

## Possible solution
Backport changes from WordPress.

- https://core.trac.wordpress.org/ticket/52941
   - https://core.trac.wordpress.org/changeset/51146
   - https://core.trac.wordpress.org/changeset/51212
- https://core.trac.wordpress.org/ticket/53077
   - https://core.trac.wordpress.org/changeset/50784
- https://core.trac.wordpress.org/ticket/53078
   - https://core.trac.wordpress.org/changeset/50934

And a notice to discourage IE11 use:
- https://meta.trac.wordpress.org/ticket/4863
   - https://meta.trac.wordpress.org/changeset/9446

I think that covers it. If anyone knows of any other tickets or changesets, please do comment.

**Comment by nylen** [comment]
https://core.trac.wordpress.org/changeset/50784 is the only one to backport here. https://meta.trac.wordpress.org/changeset/9446 is on the wordpress.org servers and the rest are Gutenberg-related code that we don't have.

When backporting 50784, the key change is located in the `.browserslistrc` file for us, instead of in `package.json` for WP. This part will need to be done manually.

**Comment by viktorix** [comment]
@nylen submitted PR to drop IE support.

**Comment by mattyrob** [comment]
On a quick search through the source code, there is legacy support for ie8 and ie9 in:
`src/wp-admin/includes/template.php`
`src/wp-includes/class-wp-admin-bar.php`
`src/wp-login.php`

And also in the `TwentySixteen` and `TwentySeventeen` themes that we should at least consider for removal.

**Comment by viktorix** [comment]
One issue with template.php:

WordPress did remove some IE-specific code, which CP still has. However, they still do have code to include `X-UA-Compatible: IE=edge` header. This header was deprecated in IE11, I believe. Should we go ahead and remove it even though WP still has it?

---

The rest of the changes are here related to tickets 17232 and 46015:
https://core.trac.wordpress.org/changeset/47771

And this one fixes a minor issue from the previous changeset:
https://core.trac.wordpress.org/changeset/48380

The 2 questions are:

1. What should I do with the IE code in template.php that WP hasn't removed yet?
2. Should I include 47771 changeset in the current PR or a separate PR?

**Comment by joyously** [comment]
There is `src/wp-admin/css/ie.css` and wherever it is loaded.
There are a few places in the editor code also. It seems more likely to be CSS or JS for browser support, although PHP might load the polyfills.

**Comment by steamboatid** [comment]
any final decision on this ?

+1 from dropping all of IE support all together
