### ISSUE TITLE
error message for updating WordPress

### ISSUE THREAD

**Issue by joyously** [ClassicPress/ClassicPress#879]
In the admin plugin page, after a search you can click to View Details of a plugin.
The error message shown when there is a version mismatch refers to WordPress, with a link to update, which is a local link to update-core.php, but it says WordPress.

![Add Plugins ‹ Classicly Pressed — ClassicPress-26](https://user-images.githubusercontent.com/7957680/145505952-21bd5f0e-767e-4126-9355-a9ed654f97f3.jpg)

**Comment by mattyrob** [comment]
We could simply fix this string to state that the plugin is declaring it is not compatible with ClassicPress.

A deeper fix would do that as well as blocking the installation and / or activation. Currently, with the example plugin above, I am able to install and activate it, so clearly we cannot rely too much on plugins doing the checks themselves.

**Comment by mattyrob** [comment]
<img width="772" alt="Screenshot 2021-12-23 at 16 30 52" src="https://user-images.githubusercontent.com/1280733/147268497-1e074d13-c86e-48a3-8e52-a4732bf6a374.png">

**Comment by joyously** [comment]
"This plugin requires a newer version of WordPress and may not be compatible with ClassicPress."
