### ISSUE TITLE
Consider further enhancements to plugin handling

### ISSUE THREAD

**Issue by mattyrob** [ClassicPress/ClassicPress#889]
## Expected behavior
Plugins are broadly currently served from the WordPress repository. A ClassicPress repository is planned. Plugins can also come from differentiated server locations including plugin developer self-hosted solutions and code platforms like Github.

## Current behavior
Currently the installation and activation plugins displays information about compatibility but that needs to be improved, Additionally there are more checks that we can backport to provide a better user experience.
There is also the possibility of allowing plugin to define in the header the endpoint for updates.

## Possible solution
We need to review and consider the following tickets (and their changesets):
https://core.trac.wordpress.org/ticket/43992
https://core.trac.wordpress.org/ticket/46938
https://core.trac.wordpress.org/changeset/50921

## Steps to reproduce (for bugs)
N/A

## Context
This Issue and any discussion needs to consider the user experience on installation and activation as well as the user messages displayed when these actions are disallowed / disabled.

**Comment by joyously** [comment]
I thought those tickets were already backported.
46938 is in #546 and the compatibility checks are in #621.
The 50921 change is still needed, with a bit of additional code to handle the CP directory.

**Comment by mattyrob** [comment]
Thanks Joy, I was looking at the backport script output for 50921 as it was pulling in more changes that the upstream commit alone.

We have made a start, and there is another PR (#546) that includes some more changes, but we are still missing some I think 45546 being one such changeset.

**Comment by joyously** [comment]
Remember that the parsing of the readme was removed in WP 5.8.

**Comment by bahiirwa** [comment]
> Remember that the parsing of the readme was removed in WP 5.8.
Ticket: https://core.trac.wordpress.org/ticket/48520
Changeset: https://core.trac.wordpress.org/changeset/51092

**Comment by xxsimoxx** [comment]
I've merged 50921 [in my fork](https://github.com/xxsimoxx/ClassicPress/tree/merge/wp-r50921) to do some tests.
- `Update URI` solves conflicts when a plugin has a slug that is similar to a WP one
- Using `update_plugins_{$hostname}` filter I was able to update a plugin from an `Update Manager` endpoint (without including the `UpdateClient` class)
- `View details` link with that filter in place leads to an error

As an example the filter I've used:
```php
add_filter('update_plugins_educatorecinofilo.dog', 'xsxupd', 10, 4);

function xsxupd( $update, $plugin_data, $plugin_file, $locales ) {
	$raw               = wp_remote_get( 'https://educatorecinofilo.dog/?update=plugin_information&plugin=' . $plugin_file . '&site_url' . get_bloginfo( 'url' ) );
	$update            = json_decode( $raw['body'], true );
	$update['package'] = $update['download_link']; // Fix wrong name
	return $update;
}
```

Seems this can help to easily integrate with updates coming from the directory and also from other places.

**Comment by xxsimoxx** [comment]
See #1124.
