### ISSUE TITLE
Introduce Improve DateTime Handling from Upstream

### ISSUE THREAD

**Issue by dshanske** [ClassicPress/ClassicPress#903]
## Expected behavior

https://make.wordpress.org/core/2019/09/23/date-time-improvements-wp-5-3/

The behavior is described in this blog post from 2019 and the related fixes.

## Current behavior

Date and Time handling in the existing code is inconsistent at best. The upstream proposal from WordPress would not solve all the problems with it, but it would clean them all up.

## Possible solution

I see no reason why the functions and unit tests could not be incorporated as is from the commits, as they would not break any sort of compatibility, as older functions became wrappers around the newer enhancements.

## Context

I deal a lot in my code with date handling and related timezone issues. This simplifies the consistency of time display immensely.

**Comment by KTS915** [comment]
I'm not sure that the post listed above refers to all the relevant changesets. I agree that it would be good to get them included in CP and have been making a list of them. Some are very extensive; others are simpler. The full list I have is as follows:

43387
43434
43562
44592
44710
44809
45805
45375
45855
45856
45876
45882
45883
45887
45900
45902
48340
48718
49001

**Comment by mattyrob** [comment]
We may need to review these searched tickets:
https://core.trac.wordpress.org/query?component=Date%2FTime&resolution=fixed&time=01%2F01%2F2018..01%2F19%2F2022&col=id&col=summary&col=type&col=milestone&order=id

And I am not 100% sure on the list above, the last 3 for example seem not to be change sets related to date/time.
