### ISSUE TITLE
Pass EXIF Data to the wp_read_image_metadata filter

### ISSUE THREAD

**Issue by dshanske** [ClassicPress/ClassicPress#904]
## Expected behavior

Filtering of EXIF data should available without having to reparse that data. This was implemented in WordPress 5.0 and wish to port it here.

## Possible solution

https://core.trac.wordpress.org/changeset/43750

## Context

I currently have a conditional in my code to cover this circumstance for versions less than 5.0, where I reparse the exif data.

**Comment by viktorix** [comment]
@dshanske do you have a sample code that can be used to test this?

**Comment by dshanske** [comment]
I have the code I use to parse out GPS from EXIF data. Would that help?

**Comment by viktorix** [comment]
Yes, please. I tried generic code to test it, but I'm getting an error and I'm curious if there's more that needs to be backported or if it's my test code.

```
require_once ABSPATH . '/wp-admin/includes/image.php';
$path = '/path/to/file.jpg';
wp_read_image_metadata( $path );
```

**Comment by dshanske** [comment]
```
add_action( 'wp_read_image_metadata', 'exif_data', 10, 5 );
function exif_data( $meta, $file, $image_type, $iptc = null, $exif = null ) {
		// If there is no Exif Version set return.
		if ( $exif['ExifVersion'] ) {
			$meta['test_filter'] = 'Yes!';
		}
               return $meta;
}
```

Try this, then check for the Yes. It should work if you pick any file that has EXIF data.

**Comment by viktorix** [comment]
It would help if my exif php extension was enabled :joy: Looks like it's working. I'll submit a PR, feel free to test it on your instance.

![image](https://user-images.githubusercontent.com/1692600/175763112-9c782f39-f09e-4ff1-9710-1122ee8f4102.png)
