### ISSUE TITLE
Enable third-party endpoints for plugin and theme updates

### ISSUE THREAD

**Issue by mattyrob** [ClassicPress/ClassicPress#908]
## Expected behavior
It would be great for plugin anthem authors to be able to specify an endpoint URL to access for update checks in a simple header in the plugin / theme header.

This already exists upstream for plugins and there are plans to expand this to include Themes.

## Current behavior
Currently a lot of code needs deploying to enable this in plugins and in themes I suspect it would prove very challenging.

## Possible solution
https://core.trac.wordpress.org/changeset/50921

## Steps to reproduce (for bugs)
N/A

## Context
Enhancement to plugin and theme upstage process for non directory code and may prove useful when the CP directory launches.

**Comment by viktorix** [comment]
I was doing a backport for this changeset and ran into a small issue. Everything seems to be OK, merge conflicts resolved, but I keep seeing this notice in debug.log:

`PHP Notice:  Undefined index: UpdateURI in C:\xampp\htdocs\classicpress\wp-includes\update.php on line 366`

This is that line:

```
if ( ! $plugin_data['UpdateURI'] || isset( $updates->response[ $plugin_file ] ) ) {
    continue;
}
```

The notice is generated when CP performs an update check or an actual update of a plugin to a new version.

**Comment by bahiirwa** [comment]
@viktorix Do you have a draft branch/PR we can look at? 

There is a possibility of this being connected to [#546](https://github.com/ClassicPress/ClassicPress/pull/546)

**Comment by xxsimoxx** [comment]
See #1124.
